/** Individually authored, immutable lesson 79 source records. */
export const purityCases = {
  identity: {
    oxygen: {
      title: "Only oxygen molecules",
      source:
        "The complete supplied sample contains O₂ molecules only. The label says ‘chemically pure oxygen’.",
      category: "element",
      label: "chemical",
    },
    water: {
      title: "One compound, two elements",
      source:
        "The complete supplied sample contains H₂O molecules only. The label says ‘chemically pure water’.",
      category: "compound",
      label: "chemical",
    },
    air: {
      title: "Two uncombined gases",
      source:
        "The supplied sample contains both N₂ and O₂ molecules, not joined together. It has no purity label.",
      category: "mixture",
      label: "none",
    },
    milk: {
      title: "Everyday pure milk",
      source:
        "The label says ‘pure milk: nothing added’. The supplied composition includes water, fats and dissolved sugars.",
      category: "mixture",
      label: "everyday",
    },
    groundwater: {
      title: "Minerals remain",
      source:
        "The label says ‘pure spring water: in its natural state’. The supplied water contains dissolved sodium and chloride ions.",
      category: "mixture",
      label: "everyday",
    },
    advertised: {
      title: "A chemical claim and a known mixture",
      source:
        "The label says ‘chemically pure water’. The complete supplied sample contains water plus dissolved sodium chloride.",
      category: "mixture",
      label: "chemical",
      contradictedClaim: true,
    },
    clear: {
      title: "Appearance alone",
      source:
        "A clear, colourless liquid has no composition or purity measurements supplied. Its label says only ‘sample A’.",
      category: "unknown",
      label: "none",
    },
    alloy: {
      title: "Designed metal mixture",
      source:
        "The sample contains copper and zinc atoms together as an alloy. No purity claim is supplied.",
      category: "mixture",
      label: "none",
    },
  },
  melting: {
    matching: {
      title: "Narrow interval at the reference",
      substance: "solid P",
      reference: 80,
      start: 79.8,
      finish: 80.2,
      resolution: 0.2,
      uncertainty: 0.2,
      conclusion: "consistent",
      low: 74,
      high: 86,
      step: 0.2,
    },
    depressed: {
      title: "Lower and wider interval",
      substance: "solid P",
      reference: 80,
      start: 75,
      finish: 78,
      resolution: 0.2,
      uncertainty: 0.2,
      conclusion: "impure",
      low: 74,
      high: 86,
      step: 0.2,
    },
    other: {
      title: "Sharp at a different temperature",
      substance: "solid P",
      reference: 80,
      start: 84.8,
      finish: 85.2,
      resolution: 0.2,
      uncertainty: 0.2,
      conclusion: "other",
      low: 74,
      high: 86,
      step: 0.2,
    },
    negative: {
      title: "Read a negative-temperature interval",
      substance: "solid Q",
      reference: -6,
      start: -10,
      finish: -7,
      resolution: 0.2,
      uncertainty: 0.2,
      conclusion: "impure",
      low: -12,
      high: 0,
      step: 0.2,
    },
    narrow: {
      title: "Do not round away the width",
      substance: "solid R",
      reference: 52,
      start: 51.8,
      finish: 52.2,
      resolution: 0.2,
      uncertainty: 0.2,
      conclusion: "consistent",
      low: 46,
      high: 58,
      step: 0.2,
    },
    incomplete: {
      title: "No completion reading",
      substance: "solid P",
      reference: 80,
      start: 79.8,
      finish: null,
      resolution: 0.2,
      uncertainty: 0.2,
      conclusion: "insufficient",
      low: 74,
      high: 86,
      step: 0.2,
    },
  },
  boiling: {
    match: {
      title: "Same-pressure water reference",
      reference: 100,
      referencePressure: 101,
      measured: 100,
      measuredPressure: 101,
      uncertainty: 0.3,
      nonvolatile: false,
      conclusion: "consistent",
    },
    salt: {
      title: "Nonvolatile dissolved material",
      reference: 100,
      referencePressure: 101,
      measured: 103,
      measuredPressure: 101,
      uncertainty: 0.3,
      nonvolatile: true,
      conclusion: "inconsistent",
    },
    pressure: {
      title: "Different pressure",
      reference: 100,
      referencePressure: 101,
      measured: 95,
      measuredPressure: 85,
      uncertainty: 0.3,
      nonvolatile: false,
      conclusion: "insufficient",
    },
    missing: {
      title: "Pressure was not recorded",
      reference: 100,
      referencePressure: 101,
      measured: 98,
      measuredPressure: null,
      uncertainty: 0.3,
      nonvolatile: false,
      conclusion: "insufficient",
    },
    tolerance: {
      title: "Within stated measurement uncertainty",
      reference: 100,
      referencePressure: 101,
      measured: 100.2,
      measuredPressure: 101,
      uncertainty: 0.3,
      nonvolatile: false,
      conclusion: "consistent",
    },
  },
  formulation: {
    ink: {
      title: "A deliberately designed ink",
      source:
        "The maker combines measured ingredients to obtain a specified colour. The target recipe is 85% yellow dye and 15% blue dye by mass.",
      total: 200,
      components: [
        { name: "Yellow dye", purpose: "Colour", percent: 85 },
        { name: "Blue dye", purpose: "Colour", percent: 15 },
      ],
      category: "formulation",
    },
    cleaner: {
      title: "A supplied cleaning formulation",
      source:
        "The supplied recipe specifies a carrier, cleaning agent and fragrance in measured proportions for the required product properties. These are generic roles, not a proprietary recipe.",
      total: 250,
      components: [
        {
          name: "Carrier",
          purpose: "Carries the other ingredients",
          percent: 92,
        },
        { name: "Cleaning agent", purpose: "Cleaning action", percent: 6 },
        { name: "Fragrance", purpose: "Odour", percent: 2 },
      ],
      category: "formulation",
    },
    paint: {
      title: "A supplied paint formulation",
      source:
        "The target recipe deliberately combines a pigment, binder and carrier for colour, a lasting film and application.",
      total: 400,
      components: [
        { name: "Pigment", purpose: "Colour", percent: 25 },
        { name: "Binder", purpose: "Forms the lasting film", percent: 35 },
        { name: "Carrier", purpose: "Supports application", percent: 40 },
      ],
      category: "formulation",
    },
    accidental: {
      title: "An accidental mixture is not a designed recipe",
      source:
        "Yellow and blue dye solutions are accidentally mixed. Their amounts were measured afterwards. The mixture was not designed for a useful product.",
      total: 120,
      components: [
        {
          name: "Yellow dye solution",
          purpose: "Accidental spill",
          percent: 75,
        },
        { name: "Blue dye solution", purpose: "Accidental spill", percent: 25 },
      ],
      category: "mixture",
    },
  },
  method: {
    sand: {
      title: "Collect the insoluble solid",
      mixture: "Sand and water",
      properties:
        "Sand is insoluble and its grains are larger than the supplied filter pores.",
      target: "Collect sand on the supplied filter paper without heating",
      method: "filtration",
      location: "residue",
    },
    water: {
      title: "Collect the solvent",
      mixture: "Sodium chloride solution",
      properties:
        "Water is volatile; sodium chloride is nonvolatile under the supplied conditions. No other volatile solutes are present.",
      target:
        "Collect liquid water in a separate receiving vessel using a condenser and no fractionating column",
      method: "simple",
      location: "distillate",
    },
    crystals: {
      title: "Grow a soluble solid",
      mixture: "Solution of solid S in water",
      properties:
        "S is soluble in hot water but much less soluble in cold water. It remains chemically unchanged under the supplied conditions.",
      target: "Crystals formed by cooling a concentrated solution",
      method: "crystallisation",
      location: "crystals",
    },
    evaporate: {
      title: "Retain a stable dissolved solid",
      mixture: "Salt solution",
      properties:
        "The salt remains stable under the stated conditions. The water does not need to be collected.",
      target:
        "Remove water without collecting it, leaving stable dry salt in the original vessel at the stated ideal endpoint",
      method: "evaporation",
      location: "vessel",
    },
    liquids: {
      title: "Separate close-boiling miscible liquids",
      mixture: "Two miscible liquids",
      properties:
        "The supplied ideal comparison has two miscible liquids with close but different boiling points. The given results show improved separation using repeated vaporisation and condensation in a fractionating column.",
      target: "Better separation than the supplied simple-distillation setup",
      method: "fractional",
      location: "fractions",
    },
    dyes: {
      title: "Separate dissolved colours",
      mixture: "Mixture of soluble dyes",
      properties:
        "The dyes travel differently with the supplied solvent on paper. All dissolve; an ordinary filter does not retain them.",
      target: "Separate dye spots",
      method: "chromatography",
      location: "paper",
    },
    dissolved: {
      title: "A filter cannot recover dissolved salt",
      mixture: "Clear sodium chloride solution",
      properties:
        "Dissolved ions pass with water through an ordinary filter. No insoluble solid is supplied.",
      target:
        "Determine whether ordinary filtration alone separates salt from water",
      method: "none",
      location: "together",
    },
  },
  filtration: {
    complete: {
      title: "Salt fully dissolved",
      sand: 8,
      salt: 2,
      water: 40,
      dissolvedSalt: 2,
      retainedWater: 0,
      retainedDissolvedSalt: 0,
    },
    damp: {
      title: "Mother liquor remains with the sand",
      sand: 6,
      salt: 4,
      water: 40,
      dissolvedSalt: 4,
      retainedWater: 2,
      retainedDissolvedSalt: 0.2,
    },
    incomplete: {
      title: "Some salt has not dissolved",
      sand: 5,
      salt: 3,
      water: 30,
      dissolvedSalt: 2,
      retainedWater: 0,
      retainedDissolvedSalt: 0,
    },
    washed: {
      title: "Washed residue, supplied ideal result",
      waterNote:
        "50g is the total water input: 30g original water plus 20g wash water. The stated ideal washed residue retains 1g water and no salt.",
      sand: 7,
      salt: 3,
      water: 50,
      dissolvedSalt: 3,
      retainedWater: 1,
      retainedDissolvedSalt: 0,
    },
    solution: {
      title: "Only a solution was filtered",
      sand: 0,
      salt: 5,
      water: 50,
      dissolvedSalt: 5,
      retainedWater: 0,
      retainedDissolvedSalt: 0,
    },
  },
  recovery: {
    dry: {
      title: "Dry product with no supplied contamination",
      sourceProduct: 10,
      productCollected: 8,
      contaminant: 0,
      water: 0,
    },
    wet: {
      title: "A wet collection is not all product",
      sourceProduct: 10,
      productCollected: 8,
      contaminant: 0,
      water: 3,
    },
    contaminated: {
      title: "High recovery, contaminated collection",
      sourceProduct: 10,
      productCollected: 9,
      contaminant: 1,
      water: 0,
    },
    purer: {
      title: "Purity and recovery need separate comparisons",
      sourceProduct: 10,
      productCollected: 6,
      contaminant: 0,
      water: 0,
    },
    decimal: {
      title: "Retain decimal mass readings",
      sourceProduct: 8,
      productCollected: 6,
      contaminant: 0.5,
      water: 1.5,
    },
  },
} as const;
