import type { LearningTask, LessonJourney, TaskModel } from "../types";
import { choice, number } from "./helpers";
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...choice(
    `cc-v1-${id}`,
    prompt,
    answer,
    errors,
    explanation,
    hint,
    title,
    model,
  ),
  title,
});
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...number(`cc-v1-${id}`, prompt, answer, unit, explanation, hint, title),
  title,
});
const guided = [
  c(
    "g-factors",
    "Combine two changes",
    "Solute mass doubles; final solution volume halves. Find the concentration factor.",
    "4",
    {
      "1": "Equal scaling would preserve concentration, but these changes are opposite.",
      "1/4": "This reverses the mass and volume factors.",
    },
    "Concentration factor=2÷.5=4. Compare both quantities.",
    "Divide the mass factor by the volume factor.",
    {
      kind: "changing-concentration",
      mode: "factors",
      instruction: "Change both factors, then predict concentration.",
    },
  ),
  c(
    "g-dilute",
    "Retain solute during dilution",
    "All 10 g dissolved solute in 250 cm³ solution is retained while pure solvent increases final volume to 500 cm³. What is the new concentration?",
    "20 g/dm³",
    {
      "40 g/dm³": "The final volume has doubled at fixed solute mass.",
      "10 g/dm³": "10 g in .5 dm³ gives 20, not 10.",
    },
    "10÷.5=20 g/dm³. No solute is removed; concentration halves because volume doubles.",
    "Keep all dissolved-solute grams.",
    {
      kind: "changing-concentration",
      mode: "dilution",
      instruction:
        "Predict retained solute mass and concentration at the supplied final volume.",
    },
  ),
  c(
    "g-portion",
    "Separate sampling from dilution",
    "A homogeneous solution contains 10 g in 500 cm³. A 250 cm³ portion is retained. What concentration remains?",
    "20 g/dm³",
    {
      "40 g/dm³": "The retained portion does not keep all 10 g.",
      "10 g/dm³": "Mass and volume both halve; their quotient stays unchanged.",
    },
    "The retained 250 cm³ contains 5 g, so 5÷.25=20 g/dm³. The other 5 g is in the removed 250 cm³.",
    "Account for both retained and removed portions.",
    {
      kind: "changing-concentration",
      mode: "portion",
      instruction:
        "Predict the retained portion's solute mass, concentration and reason.",
    },
  ),
  c(
    "g-target",
    "Distinguish final and added volume",
    "10 g dissolved solute in 250 cm³ is diluted to 20 g/dm³. Under the supplied additive-volume approximation, how much pure solvent is added?",
    "250 cm³",
    {
      "500 cm³": "500 cm³ is the final solution volume, not the addition.",
      "750 cm³": "This would give 1000 cm³ final volume and 10 g/dm³.",
    },
    "Final volume=10÷20=.5 dm³=500 cm³. Added=500−250=250 cm³ under the stated approximation.",
    "Find final volume, then subtract the original volume.",
    {
      kind: "changing-concentration",
      mode: "target",
      instruction:
        "Predict final solution volume and the separate added solvent amount.",
    },
  ),
];
guided[0].openingHint = true;
export const changingConcentrationJourney: LessonJourney = {
  version: 1,
  introduction:
    "Explain concentration changes by tracking dissolved-solute mass and final solution volume separately.",
  scopeNote:
    "Higher explanation of mass/volume relationships (AQA4.3.2.5 and Trilogy5.3.2.5). Same solute, fully dissolved, no reaction or unaccounted loss; sample-removal examples assume homogeneity. Added-volume tasks explicitly supply an additive-volume approximation. These are reasoning models, not laboratory instructions; molarity, acid strength and titration remain separate lessons.",
  outcomes: [
    "Use mass factor ÷ final-volume factor to compare concentration.",
    "Explain dilution at retained solute mass and distinguish it from homogeneous sample removal.",
    "Construct final-volume and added-solvent working with stated assumptions.",
    "Account for all solute across retained and removed portions.",
  ],
  warmup: [
    n(
      "w-core",
      "Recall mass concentration",
      "8 g dissolved solute in 200 cm³ final solution: calculate g/dm³.",
      40,
      "g/dm³",
      "200 cm³=.2 dm³; 8÷.2=40.",
      "Convert final volume to dm³.",
    ),
    n(
      "w-factor",
      "Recall dividing by a fraction",
      "Calculate 3÷0.5.",
      6,
      "",
      "3÷.5=6.",
      "How many halves are in 3?",
    ),
  ],
  refresher: [
    c(
      "r-fixed",
      "State what stays fixed",
      "When comparing concentration with increasing dissolved mass alone, what must remain fixed for direct proportionality?",
      "Final solution volume",
      {
        Nothing: "Two changing quantities need both factors.",
        Concentration: "That is the quantity being compared.",
      },
      "At fixed final volume, doubling dissolved mass doubles concentration.",
      "Inspect the denominator.",
    ),
    c(
      "r-inverse",
      "Identify the inverse relationship",
      "At fixed dissolved-solute mass, doubling final solution volume does what to concentration?",
      "Halves it",
      {
        "Doubles it": "Volume is the denominator.",
        "Leaves it unchanged": "Mass has not increased with volume.",
      },
      "The same solute mass is shared over twice the volume.",
      "Keep the numerator fixed.",
    ),
    c(
      "r-retain",
      "Identify what dilution retains",
      "Pure solvent is added to an entire solution with no reaction or loss. What remains unchanged?",
      "Dissolved-solute mass",
      {
        "Final solution volume": "Added solvent increases the final volume.",
        "Solute concentration": "It falls as final volume increases.",
      },
      "Solvent addition does not remove the dissolved solute.",
      "Track solute separately from solution.",
    ),
    c(
      "r-homogeneous",
      "Use the sampling assumption",
      "Why does removing half a homogeneous solution also remove half its dissolved solute?",
      "Equal solution volumes have equal solute concentration",
      {
        "All solute must remain in the original vessel":
          "Solute is present throughout the homogeneous solution.",
        "Every solute particle must be in the removed half":
          "Both portions contain solute.",
      },
      "Homogeneous concentration makes dissolved mass proportional to the portion's volume.",
      "Use equal concentration across the solution.",
    ),
  ],
  guided,
  practice: [
    n(
      "p-mass",
      "Change only the numerator",
      "At fixed final volume, dissolved mass changes from 6 g to 18 g. What is the concentration factor?",
      3,
      "",
      "18÷6=3; the volume factor is 1.",
      "Divide new mass by original mass.",
    ),
    n(
      "p-volume",
      "Change only the denominator",
      "All solute is retained while final volume changes from 200 to 800 cm³. What is the concentration factor?",
      0.25,
      "",
      "Volume factor 4; concentration factor 1÷4=.25.",
      "Use the inverse factor.",
    ),
    n(
      "p-opposite",
      "Combine opposite changes",
      "The same solute's mass is tripled and final solution volume is halved. What is the concentration factor?",
      6,
      "",
      "3÷.5=6.",
      "Divide, do not multiply the factors.",
    ),
    n(
      "p-equal",
      "Scale both quantities equally",
      "Dissolved mass and final solution volume are both tripled. What is the concentration factor?",
      1,
      "",
      "3÷3=1; the quotient is unchanged.",
      "Compare both scale factors.",
    ),
    n(
      "p-compete",
      "Compare competing changes",
      "Dissolved mass doubles and final solution volume quadruples. What is the concentration factor?",
      0.5,
      "",
      "2÷4=.5: greater solute mass can still accompany lower concentration.",
      "Mass alone cannot decide.",
    ),
    n(
      "p-quarter",
      "Halve mass while doubling volume",
      "The same solute's mass halves and final solution volume doubles. What is the concentration factor?",
      0.25,
      "",
      ".5÷2=.25.",
      "Track numerator and denominator separately.",
    ),
    n(
      "p-diluted",
      "Calculate a diluted solution",
      "All 6 g dissolved solute in 150 cm³ solution is retained. Final volume becomes 600 cm³. Calculate concentration.",
      10,
      "g/dm³",
      "6÷.6=10 g/dm³; original 40 becomes one quarter.",
      "Use final 600 cm³, not added volume.",
    ),
    n(
      "p-solute",
      "Preserve dissolved mass",
      "All 12 g dissolved solute is retained during dilution from 300 to 900 cm³. How many grams of dissolved solute are present afterwards?",
      12,
      "g",
      "No solute loss or reaction occurs; 12 g remains.",
      "Dilution is solvent addition.",
    ),
    n(
      "p-target",
      "Find a target final volume",
      "All 9 g solute is retained. What final solution volume in cm³ gives 15 g/dm³?",
      600,
      "cm³",
      "9÷15=.6 dm³=600 cm³.",
      "Find dm³ first.",
    ),
    n(
      "p-added",
      "Find the separate added amount",
      "9 g in 200 cm³ is diluted to 15 g/dm³. Assume solution and added solvent volumes are additive. How much solvent is added?",
      400,
      "cm³",
      "Final 600 cm³; 600−200=400 cm³ added.",
      "Subtract the original volume from the final one.",
    ),
    n(
      "p-portion-mass",
      "Account for a homogeneous sample",
      "A homogeneous solution contains 18 g in 600 cm³. A 200 cm³ portion is retained. Find its dissolved-solute mass.",
      6,
      "g",
      "Retained fraction 200/600=1/3; 18/3=6 g.",
      "Scale mass with retained volume.",
    ),
    n(
      "p-portion-c",
      "Check concentration after sampling",
      "A homogeneous solution contains 18 g in 600 cm³. A 200 cm³ portion is retained. Find its concentration.",
      30,
      "g/dm³",
      "6 g in .2 dm³=30 g/dm³, equal to 18/.6.",
      "Both mass and volume reduce proportionally.",
    ),
    n(
      "p-removed",
      "Include the removed solute",
      "A homogeneous solution contains 8 g in 400 cm³. 100 cm³ is removed. What dissolved-solute mass is in the removed portion?",
      2,
      "g",
      "Removed fraction 100/400=1/4; 8/4=2 g.",
      "The removed solution also contains solute.",
    ),
    c(
      "p-evidence",
      "Recognise insufficient evidence",
      "Solution B contains more dissolved mass of the same solute than A, but their final volumes are unknown. Can B be identified as more concentrated?",
      "No; compare both final volumes as well",
      {
        "Yes; more dissolved mass always means more concentration":
          "A larger denominator may offset the mass increase.",
        "No; more mass always means less concentration":
          "At fixed volume, more dissolved mass increases concentration.",
      },
      "Concentration is mass divided by final volume; mass alone is insufficient.",
      "Identify the missing denominator.",
    ),
    c(
      "p-not-strength",
      "Distinguish amount per volume from acid strength",
      "Diluting an acid decreases its concentration. Does this alone mean a strong acid becomes a weak acid?",
      "No; concentration and acid strength describe different things",
      {
        "Yes; dilute always means weak":
          "Weak/strong concerns ionisation, not simply amount per volume.",
        "Yes; less solute means a different acid substance":
          "Dilution does not by itself change the acid identity.",
      },
      "Concentration concerns amount per solution volume. Strong/weak concerns ionisation and is taught separately.",
      "Keep the meaning of each term separate.",
    ),
    c(
      "p-final",
      "Avoid assuming volume additivity",
      "A solution is diluted, but no final volume or additive-volume approximation is supplied. Can the exact final volume always be found by adding starting solution and solvent volumes?",
      "No; use measured final volume or a supplied approximation",
      {
        "Yes; volumes of all mixtures are exactly additive":
          "Mixing need not preserve the sum of separate volumes.",
        "Yes; added solvent alone is final solution volume":
          "It excludes the original solution.",
      },
      "The concentration denominator is final solution volume. Do not silently assume additivity.",
      "Check the stated assumptions.",
    ),
    {
      ...c(
        "p-inventory",
        "Construct both portions",
        "A homogeneous solution contains 12 g dissolved solute in 600 cm³. Retain 150 cm³ and remove the rest. Enter retained solute grams, removed solute grams and retained concentration in g/dm³.",
        JSON.stringify({ retained: "3", removed: "9", concentration: "20" }),
        {},
        "150/600=1/4: retained 3 g, removed 9 g. 3/.15=20 g/dm³; 3+9=12 g.",
        "Account for both portions before dividing.",
      ),
      options: undefined,
      partLegend: "Account for retained and removed solute",
      parts: [
        { id: "retained", label: "Retained solute / g", answer: 3 },
        { id: "removed", label: "Removed solute / g", answer: 9 },
        {
          id: "concentration",
          label: "Concentration / g/dm³",
          answer: 20,
        },
      ],
    },
    n(
      "p-evaporate",
      "Track selective solvent removal",
      "All 5 g non-volatile solute remains dissolved when solvent evaporation reduces final solution volume from 500 to 200 cm³. Find final concentration.",
      25,
      "g/dm³",
      "5÷.2=25 g/dm³. The assumptions specify no solute loss or precipitation.",
      "This removes solvent, not a homogeneous portion.",
    ),
    {
      ...c(
        "p-explain",
        "Explain two different operations",
        "Compare diluting an entire 10 g/500 cm³ solution to 1000 cm³ with retaining 250 cm³ of the original homogeneous solution. Explain mass, volume and concentration for each.",
        "Dilution retains 10 g in 1 dm³, so 10 g/dm³. Sampling retains 5 g in .25 dm³, so 20 g/dm³; removed 5 g is in 250 cm³. Dilution increases volume at fixed solute mass; sampling reduces mass and volume together.",
        {},
        "Identify the different solute inventories, not just the liquid levels.",
        "Calculate both quotients and account for removed solute.",
      ),
      options: undefined,
      rubric: [
        "Dilution retains 10 g in 1000 cm³ and gives 10 g/dm³.",
        "The retained homogeneous 250 cm³ contains 5 g and remains 20 g/dm³.",
        "Explains fixed mass on dilution versus proportional mass/volume removal and accounts for removed solute.",
      ],
    },
    {
      ...c(
        "p-justify",
        "Explain competing factors",
        "A learner says doubling dissolved-solute mass must double concentration, even when final volume is tripled. Explain and correct this claim.",
        "Concentration depends on both mass and final volume. Its factor is 2÷3=2/3, so it decreases to two thirds. Doubling concentration from doubled mass requires fixed final volume.",
        {},
        "State the condition needed for the claimed direct proportion.",
        "Divide the two factors.",
      ),
      options: undefined,
      rubric: [
        "Identifies the quotient of mass and final volume.",
        "Calculates concentration factor 2/3 and identifies a decrease.",
        "States that doubling mass doubles concentration only at fixed final volume.",
      ],
    },
  ],
  checkForms: [
    [
      n(
        "ca-factor",
        "Compare new factors",
        "Dissolved mass increases by factor 5 and final solution volume by factor 2. What is the concentration factor?",
        2.5,
        "",
        "5÷2=2.5.",
        "Divide mass factor by volume factor.",
      ),
      n(
        "ca-dilute",
        "Calculate retained-solute dilution",
        "All 7.2 g dissolved solute is retained when final solution volume becomes 900 cm³. Find concentration.",
        8,
        "g/dm³",
        "7.2÷.9=8.",
        "Use the supplied final volume.",
      ),
      n(
        "ca-portion",
        "Calculate a retained portion",
        "A homogeneous solution contains 15 g in 750 cm³. Retain 300 cm³. How many solute grams remain?",
        6,
        "g",
        "15×300/750=6.",
        "Scale by the retained fraction.",
      ),
      n(
        "ca-added",
        "Separate added from final",
        "6 g solute in 150 cm³ is diluted to 12 g/dm³. Assume additive volumes. How much pure solvent is added?",
        350,
        "cm³",
        "Final 6/12=.5 dm³=500 cm³; added 350.",
        "Calculate final volume first.",
      ),
      c(
        "ca-condition",
        "State the fixed quantity",
        "Concentration halves when final volume doubles provided what is unchanged?",
        "Dissolved-solute mass",
        {
          "Whole-solution mass":
            "Adding solvent generally changes total solution mass.",
          "Final solution volume": "The question states that it changes.",
        },
        "An inverse relationship requires a fixed numerator.",
        "Name the numerator.",
      ),
    ],
    [
      n(
        "cb-factor",
        "Combine unfamiliar factors",
        "Dissolved-solute mass increases by factor 1.5 and final solution volume by factor 3. What is the concentration factor?",
        0.5,
        "",
        "1.5÷3=.5.",
        "Divide the factors.",
      ),
      n(
        "cb-dilute",
        "Use a different final volume",
        "All 4.8 g solute is retained after dilution to 1200 cm³ final solution. Find concentration.",
        4,
        "g/dm³",
        "4.8÷1.2=4.",
        "Convert 1200 cm³ to dm³.",
      ),
      n(
        "cb-removed",
        "Account for removed sample",
        "A homogeneous solution contains 21 g in 700 cm³. Remove 200 cm³. What solute mass is removed?",
        6,
        "g",
        "21×200/700=6.",
        "Use the removed volume fraction.",
      ),
      {
        ...c(
          "cb-volumes",
          "Construct final and added volumes",
          "All 8 g solute in 100 cm³ is diluted to 16 g/dm³. Assume additive volumes. Enter final solution cm³ and added solvent cm³.",
          JSON.stringify({ final: "500", added: "400" }),
          {},
          "Final 8/16=.5 dm³=500 cm³; added 500−100=400 cm³.",
          "Subtract only after finding final volume.",
        ),
        options: undefined,
        partLegend: "Distinguish final solution from added solvent",
        parts: [
          { id: "final", label: "Final solution / cm³", answer: 500 },
          { id: "added", label: "Added solvent / cm³", answer: 400 },
        ],
      },
      c(
        "cb-equal",
        "Explain equal scaling",
        "The same solute's dissolved mass and final solution volume both increase by factor 4. What happens to concentration?",
        "It stays unchanged",
        {
          "It becomes four times greater":
            "The denominator also increases fourfold.",
          "It becomes sixteen times greater":
            "Concentration divides the factors.",
        },
        "4÷4=1.",
        "Compare numerator and denominator factors.",
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "ra-factor",
        "Retrieve a combined change",
        "Dissolved-solute mass halves and final solution volume quadruples. What is the concentration factor?",
        0.125,
        "",
        ".5÷4=.125.",
        "Divide the factors.",
      ),
      n(
        "ra-dilute",
        "Retrieve retained solute",
        "All 3 g solute is retained during dilution to 750 cm³ final solution. Find concentration.",
        4,
        "g/dm³",
        "3÷.75=4.",
        "Use final solution dm³.",
      ),
      n(
        "ra-portion",
        "Retrieve a portion inventory",
        "A homogeneous solution contains 24 g in 800 cm³. Retain 300 cm³. Find retained dissolved-solute mass.",
        9,
        "g",
        "24×300/800=9.",
        "Scale mass with sample volume.",
      ),
    ],
    [
      n(
        "rb-factor",
        "Retrieve unequal scaling",
        "Dissolved-solute mass doubles and final solution volume increases by factor 8. What is the concentration factor?",
        0.25,
        "",
        "2÷8=.25.",
        "Divide the two factors.",
      ),
      n(
        "rb-added",
        "Retrieve added versus final",
        "All 5 g solute in 100 cm³ is diluted to 10 g/dm³. Assume additive volumes. How much solvent is added?",
        400,
        "cm³",
        "Final 5/10=.5 dm³=500 cm³; added 400.",
        "Final minus original.",
      ),
      n(
        "rb-portion",
        "Retrieve concentration after sampling",
        "A homogeneous solution contains 16 g in 400 cm³. Retain 50 cm³. Find retained concentration.",
        40,
        "g/dm³",
        "Retained 2 g/.05 dm³=40, equal to 16/.4.",
        "Both mass and volume scale by the same fraction.",
      ),
    ],
  ],
};
changingConcentrationJourney.practice.find(
  (q) => q.id === "cc-v1-p-inventory",
)!.followUp = "cc-v1-r-homogeneous";
changingConcentrationJourney.practice.find(
  (q) => q.id === "cc-v1-p-compete",
)!.followUp = "cc-v1-r-fixed";

import { extendChangingWriting } from "./changing-writing";
extendChangingWriting(changingConcentrationJourney);
