import {
  choice as c,
  number as n,
  written as w,
  drawing as d,
  type ChromaTask,
} from "./chromatography-tasks";
export const chromatographyPractice: ChromaTask[] = [
  c(
    "p-pencil",
    "Protect the origin reference",
    "The supplied baseline ink dissolves in water. Why replace it with pencil?",
    "The pencil line will not dissolve and travel with the solvent",
    {
      "Ink cannot contain a mixture": "Ink can contain several soluble dyes.",
      "The line must become invisible":
        "Its position is needed to measure travel.",
    },
    "Soluble baseline ink can add extra components and stop being a reliable origin line.",
    "Keep the origin and sample components distinguishable.",
    { mode: "setup", record: "ink-line", focus: "lineMaterial" },
  ),
  c(
    "p-immersed",
    "Diagnose an immersed sample",
    "The fixed origin is 18 mm high and the reservoir is 24 mm high. Why is this invalid?",
    "The sample can dissolve directly into the reservoir",
    {
      "The paper is too short to have a stationary phase":
        "The supplied error concerns sample immersion, not paper length.",
      "The solvent is prevented from contacting the paper":
        "The water level is above both the paper bottom and sample.",
    },
    "The origin must stay above the reservoir so the solvent can carry the sample up through the stationary phase.",
    "Compare the original level with the origin.",
    { mode: "setup", record: "immersed", focus: "solventLevel" },
  ),
  c(
    "p-touch",
    "Treat contact with the origin as an error",
    "The solvent level is exactly equal to the sample origin. What should change?",
    "Lower it below the origin while retaining paper contact",
    {
      "Raise it farther above the sample": "That increases immersion.",
      "Nothing: equality leaves the sample above the liquid":
        "A level equal to the origin touches the sample rather than leaving it above the liquid.",
    },
    "A valid level is strictly below the origin, while still contacting the paper.",
    "Above is a strict height comparison.",
    { mode: "setup", record: "touching-origin", focus: "solventLevel" },
  ),
  c(
    "p-phase-paper",
    "Identify a stationary phase",
    "Paper is held in place and water travels through it. Which is the stationary phase in this GCSE example?",
    "Paper",
    {
      Water: "Water is the moving solvent here.",
      "The moving dye": "The dye distributes between the phases.",
    },
    "The paper provides the stationary phase in the supplied paper-chromatography example.",
    "Distinguish sample from phase.",
    { mode: "phases", record: "paper-water", focus: "stationary" },
  ),
  c(
    "p-phase-saline",
    "Use a specified mobile phase",
    "The supplied practical uses paper and a dilute salt solution as the solvent. What is the mobile phase?",
    "The salt solution",
    {
      "The paper": "The paper stays fixed.",
      "The beaker": "Apparatus is not a phase carrying the sample.",
    },
    "The specified solvent solution moves through the paper.",
    "Identify the actual moving liquid.",
    { mode: "phases", record: "paper-saline", focus: "mobile" },
  ),
  c(
    "p-tlc",
    "Transfer phase vocabulary to supplied apparatus",
    "A supplied extension uses a fixed silica layer on glass and moving ethanol. Which is the stationary phase?",
    "The silica layer",
    {
      Ethanol: "Ethanol is the moving solvent.",
      "Glass alone":
        "The source identifies silica as the separating layer; glass supports it.",
    },
    "The stationary separating layer is silica. This supplied apparatus example extends phase vocabulary; naming all TLC materials is not assumed as a core requirement.",
    "Read the explicitly supplied layer.",
    { mode: "phases", record: "silica-plate", focus: "stationary" },
  ),
  n(
    "p-origin",
    "Correct an offset measurement",
    "Origin: 15 mm; centre: 45 mm; front: 75 mm above the paper bottom. Find the spot travel distance.",
    "30",
    "mm",
    "45 − 15 = 30 mm. The travel starts at the origin.",
    "Use centre position minus origin position.",
    { mode: "measurement", record: "second-origin", focus: "spotDistance" },
  ),
  n(
    "p-centre",
    "Reject a spot-edge measurement",
    "The origin is at 12 mm. A circular spot has centre 60 mm and radius 4 mm. Find its travel distance.",
    "48",
    "mm",
    "Use the centre: 60 − 12 = 48 mm. Neither 44 nor 52 mm measures centre travel.",
    "Ignore radius when locating centre travel.",
    { mode: "measurement", record: "spot-centre", focus: "spotDistance" },
  ),
  n(
    "p-front",
    "Measure solvent travel",
    "The fixed origin is 20 mm and the marked front 100 mm above the paper bottom. Find the front travel distance.",
    "80",
    "mm",
    "100 − 20 = 80 mm. Both numerator and denominator use the same origin.",
    "Subtract the origin offset.",
    { mode: "measurement", record: "high-origin", focus: "frontDistance" },
  ),
  c(
    "p-missing-front",
    "Respect an incomplete record",
    "The original front was not marked before it disappeared. Origin and spot centre remain recorded. Which result is supported?",
    "Spot travel can be measured, but Rf is unavailable",
    {
      "Rf is zero": "No front reading is not a zero reading.",
      "Rf is the spot coordinate above the paper bottom":
        "That is a coordinate, not a dimensionless ratio.",
    },
    "A front distance is necessary for Rf. Do not replace missing data with the paper edge.",
    "Identify the absent denominator.",
    { mode: "measurement", record: "missing-front", focus: "conclusion" },
  ),
  n(
    "p-direct",
    "Calculate a dimensionless ratio",
    "The spot travels 28 mm and the front 80 mm from the origin. Calculate Rf.",
    "0.35",
    "",
    "28 ÷ 80 = 0.35, without a unit.",
    "Use spot over solvent-front travel.",
    { mode: "ratio", record: "forward", focus: "rf" },
  ),
  n(
    "p-inverse",
    "Recover the numerator",
    "Rf = 0.575 and solvent-front travel = 80 mm. Find spot travel from the origin.",
    "46",
    "mm",
    "0.575 × 80 = 46 mm.",
    "Multiply the ratio by the denominator.",
    { mode: "ratio", record: "inverse", focus: "spotDistance" },
  ),
  n(
    "p-find-front",
    "Recover the denominator",
    "A spot travels 45 mm and its Rf is 0.75. Find the solvent-front travel.",
    "60",
    "mm",
    "Front travel = 45 ÷ 0.75 = 60 mm.",
    "Rearrange the ratio, keeping the quantities in their roles.",
    { mode: "ratio", record: "find-front", focus: "frontDistance" },
  ),
  n(
    "p-mixed-units",
    "Use consistent units",
    "Spot travel is 30 mm; solvent-front travel is 6 cm. Find Rf.",
    "0.5",
    "",
    "Convert 6 cm to 60 mm, then divide 30 by 60.",
    "Convert either distance so both units agree.",
    { mode: "ratio", record: "mixed-units", focus: "rf" },
  ),
  {
    ...n(
      "p-two-sf",
      "Report the requested precision",
      "Spot travel is 3 cm and solvent-front travel 7 cm. Give Rf to two significant figures.",
      "0.43",
      "",
      "3 ÷ 7 = 0.428571…; to two significant figures it is 0.43.",
      "Round using the next significant digit.",
      { mode: "ratio", record: "two-sf", focus: "rf" },
    ),
    rounding: { kind: "significant-figures", digits: 2 },
  },
  n(
    "p-zero",
    "Allow the origin endpoint",
    "A supplied spot remains at the origin while the front travels 75 mm. Calculate Rf.",
    "0",
    "",
    "0 ÷ 75 = 0. A zero ratio does not by itself explain why the spot remained there.",
    "Use the recorded zero travel.",
    { mode: "ratio", record: "zero", focus: "rf" },
  ),
  n(
    "p-one",
    "Allow the front endpoint",
    "The supplied spot centre and its front each travel 80 mm. Calculate Rf.",
    "1",
    "",
    "80 ÷ 80 = 1. The ideal supplied endpoint is within the inclusive range 0 to 1.",
    "Equal nonzero distances give a ratio of one.",
    { mode: "ratio", record: "at-front", focus: "rf" },
  ),
  c(
    "p-invalid",
    "Preserve inconsistent measurements",
    "The record gives spot travel 88 mm and front travel 80 mm. How should the arithmetic ratio 1.1 be interpreted?",
    "Check the measurements or labels: the ordinary record is inconsistent",
    {
      "Silently change 88 mm to 80 mm":
        "This erases the original error rather than diagnosing it.",
      "Accept 1.1 as a normal Rf for this ordinary experiment":
        "The centre is recorded beyond its own solvent front.",
    },
    "Keep the original figures visible and investigate their measurement or labelling.",
    "Assess the physical record as well as the division.",
    { mode: "ratio", record: "past-front", focus: "conclusion" },
  ),
  c(
    "p-retention-reverse",
    "Infer from the evidence, not the letter",
    "For one dye with controlled solvent and conditions, Rf is 0.70 on paper A and 0.30 on paper B. Which paper retains it more?",
    "Paper B",
    {
      "Paper A":
        "The larger relative travel on A is evidence of less retention there.",
      "Neither can retain a dye because both are stationary":
        "Stationary phases interact with sample components.",
    },
    "The lower Rf on B supports more stationary retention in the stated comparison.",
    "Find the smaller relative travel.",
    { mode: "affinity", record: "paper-b", focus: "moreStationaryRetention" },
  ),
  w(
    "p-explain",
    "Write the separation mechanism",
    "Two soluble dyes have different relative attractions to the same paper and moving solvent. Explain how this separates them.",
    "The dyes distribute between the stationary phase and the mobile solvent. A dye retained more in the stationary phase spends more time there and travels a smaller fraction of the solvent-front distance; a dye spending more time in the moving solvent travels farther relative to the front.",
    [
      "Identify both phases.",
      "Link relative attraction to time/distribution between phases.",
      "Connect greater stationary retention with smaller relative travel.",
    ],
    "Use a chain of causes, not molecular size or boiling point.",
  ),
  n(
    "p-count",
    "State a minimum component count",
    "The original uncontaminated sample produces three distinct resolved spots. What is the minimum number of detected components?",
    "3",
    "",
    "Three resolved spots support at least three detected components. Additional components could overlap or escape detection.",
    "Count resolved spots without assuming completeness.",
    {
      mode: "interpretation",
      record: "three-resolved",
      focus: "minimumComponents",
    },
  ),
  c(
    "p-mixture-matches",
    "Use known lanes cautiously",
    "The supplied same-condition unknown has two spots matching references P and Q. What identification is supported among the supplied candidates?",
    "Components consistent with P and Q",
    {
      "One pure reference R":
        "The unknown has two resolved spots, and R occupies a different position.",
      "Exactly every possible substance with that colour":
        "Colour and position do not uniquely identify arbitrary substances.",
    },
    "The unknown is a mixture with matches to the supplied P and Q candidates under the same conditions.",
    "Compare lanes and preserve the scope of the references.",
    { mode: "interpretation", record: "known-mixture", focus: "matches" },
  ),
  c(
    "p-inventory-pure",
    "Predict the result of a supplied pure compound",
    "The complete sample contains only compound Q, supplied as soluble and detectable in this valid run. Which chromatogram is expected?",
    "One Q spot",
    {
      "A separate spot for each element inside Q":
        "Those elements are chemically combined in one compound; chromatography does not separate them as sample components.",
      "No spot because a pure substance cannot be detected":
        "The source explicitly supplies Q as detectable and soluble.",
    },
    "The complete source supplies one soluble, detectable compound, so one spot is expected. The reverse inference for an unknown needs care because several compounds may overlap.",
    "Count substances in the complete supplied inventory.",
    {
      mode: "interpretation",
      record: "known-pure",
      focus: "minimumComponents",
    },
  ),
  c(
    "p-coelution",
    "Keep an unresolved match unresolved",
    "References A and B both have the same Rf as the unknown’s single spot in this solvent. What is supported?",
    "A, B or an unresolved mixture of both remain possible",
    {
      "A is uniquely identified":
        "B and an unresolved mixture are also compatible with this chromatogram.",
      "B is ruled out because only one spot is visible":
        "B can occupy that same position.",
    },
    "One co-eluting spot cannot distinguish the supplied alternatives. Another suitable solvent may resolve them.",
    "List all candidates consistent with the evidence.",
    { mode: "interpretation", record: "one-unresolved", focus: "matches" },
  ),
  c(
    "p-colour",
    "Avoid identification from colour alone",
    "On the same paper and in the same solvent, two pink spots have Rf values 0.30 and 0.70. Does colour support the proposed reference match?",
    "No: their relative travel differs under the same conditions",
    {
      "Yes: every pink dye is the same compound":
        "Different dyes can share a visible colour.",
      "Yes: Rf cannot vary between substances":
        "Different phase distributions can give different Rf values.",
    },
    "The supplied positions disagree with the proposed match; colour alone cannot override them.",
    "Compare positions as well as appearance.",
    { mode: "interpretation", record: "same-colour", focus: "matches" },
  ),
  c(
    "p-unmatched",
    "Leave an unsupported component unnamed",
    "The unknown’s lower spot matches P. Its upper spot matches neither supplied P nor Q. What is supported?",
    "A P-consistent component and another unidentified component",
    {
      "P and Q are both established": "The second position does not match Q.",
      "A pure P sample": "The unknown has another resolved spot.",
    },
    "A reference match can support one component while leaving another unnamed.",
    "Do not force every sample spot onto the reference list.",
    { mode: "interpretation", record: "unnamed-second", focus: "matches" },
  ),
  c(
    "p-solvent",
    "Choose from actual observations",
    "The supplied solvent S1 gives A and B Rf = 0.40. Solvent S2 gives A = 0.20 and B = 0.70 on the same paper. Which better resolves these two components?",
    "S2",
    {
      S1: "Both components co-elute at 0.40 there.",
      "Neither: a solvent cannot change separation":
        "The supplied observations show different results.",
    },
    "Different relative travel in S2 separates the two candidate components.",
    "Use the supplied observations rather than the solvent name.",
    { mode: "conditions", record: "resolve-solvent", focus: "choice" },
  ),
  c(
    "p-confounded",
    "Separate observation from cause",
    "The same dye gives Rf = 0.30 on paper A in water and 0.70 on paper B in ethanol. Can this isolate which paper attracts it more?",
    "No: paper and solvent both changed",
    {
      "Yes: paper B must attract it less independently of solvent":
        "Changing the solvent confounds that causal comparison.",
      "The observed relative travel cannot be compared numerically":
        "0.70 is greater than 0.30; the problem is attributing the cause.",
    },
    "The numerical relative travel differs, but the cause cannot be assigned to paper alone.",
    "Identify every changed condition.",
    {
      mode: "affinity",
      record: "confounded",
      focus: "moreStationaryRetention",
    },
  ),
  n(
    "p-proportions",
    "Distinguish amount from relative travel",
    "Under the stated same solvent, paper and temperature, below overload, the dye proportions change from 85:15 to 75:25. Yellow previously had Rf = 0.60. What is its expected Rf?",
    "0.60",
    "",
    "The same dye retains its relative travel under the supplied controlled dilute conditions. Spot intensity may change with amount.",
    "The proportion is not the ratio of travel distances.",
    { mode: "conditions", record: "different-amounts", focus: "newRf" },
  ),
  n(
    "p-longer",
    "Compare ratios across run distances",
    "Under the same conditions, the first run gives spot/front = 30/50 mm; the second gives 60/100 mm. What is the second Rf?",
    "0.60",
    "",
    "60 ÷ 100 = 0.60, the same as 30 ÷ 50. Both distances increased proportionally.",
    "Compare relative, not absolute, travel.",
    { mode: "conditions", record: "longer-run", focus: "newRf" },
  ),
  d(
    "p-draw-plot",
    "Construct a calibrated chromatogram",
    "Use the supplied paper-bottom origin of 10 mm and front of 90 mm. Sample A has two soluble resolved components with Rf = 0.25 and 0.75; sample B is supplied as one soluble compound with Rf = 0.50. Propose the origin, front, spot centres and phase labels.",
    { mode: "chromatogram", record: "plotPractice" },
    "The front travels 80 mm. A travels 20 and 60 mm, giving centres at 30 and 70 mm above the paper bottom. B travels 40 mm, giving centre 50 mm. Origin is 10 mm, front 90 mm; paper is stationary, water mobile and the origin line is pencil.",
    [
      "Preserve origin 10 mm and front 90 mm.",
      "Calculate centre coordinates 30, 70 and 50 mm by adding the origin offset.",
      "Keep two A spots and one B spot in the supplied lanes.",
      "Label paper, water and pencil consistently.",
    ],
  ),
  d(
    "p-draw-setup",
    "Repair an actual arrangement proposal",
    "Use the supplied fixed paper bottom of 3 mm and sample origin of 28 mm. The original soluble-ink line is at the origin and reservoir level 34 mm. Propose a valid water level, baseline material, phases, sample handling and front recording.",
    { mode: "setup", record: "setupPractice" },
    "Choose a level reaching the paper but strictly below 28 mm, for example 12 mm. Replace the soluble-ink line with pencil. Paper is stationary and water mobile. Use small separate spots and clean applicators. Mark the solvent front while still visible after removal.",
    [
      "Keep the original paper and origin fixed.",
      "Choose a level at least 3 mm and strictly less than 28 mm; no unique height is required.",
      "Use pencil, paper stationary and water mobile.",
      "Use uncontaminated small spots and record the front while visible.",
    ],
  ),
];
