import type { LearningTask, LessonJourney, TaskModel } from "../types";
import { choice, number } from "./helpers";
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...number(
    `gv-v1-${id}`,
    prompt,
    answer,
    unit,
    explanation,
    hint,
    title,
    {},
    model,
  ),
  title,
});
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...choice(`gv-v1-${id}`, prompt, answer, errors, explanation, hint, title),
  title,
});
const p = (
  id: string,
  title: string,
  prompt: string,
  parts: { id: string; label: string; answer: number }[],
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  id: `gv-v1-${id}`,
  title,
  prompt,
  parts,
  partLegend: title,
  answer: JSON.stringify(
    Object.fromEntries(parts.map((v) => [v.id, String(v.answer)])),
  ),
  explanation,
  hint,
  purpose: title,
  model,
});
const w = (
  id: string,
  title: string,
  prompt: string,
  explanation: string,
  rubric: string[],
): LearningTask => ({
  id: `gv-v1-${id}`,
  title,
  prompt,
  answer: explanation,
  explanation,
  rubric,
  hint: "Name the measured conditions, identify gases and link quantities to the equation.",
  purpose: title,
});
const model = (
  mode: "molar" | "mass" | "ratio" | "remaining" | "phases",
  instruction: string,
): TaskModel => ({ kind: "gas-volumes", mode, instruction });
export const gasVolumesJourney: LessonJourney = {
  version: 1,
  introduction:
    "Use amount and balanced equations to calculate gas volumes, including unused reactants.",
  scopeNote:
    "Higher separate Chemistry, AQA 4.3.5. Use the supplied 24 dm³/mol at room temperature and pressure (RTP: 20 °C and 1 atmosphere). Convert grams, kilograms, cm³ and dm³ explicitly; V=n×24 and n=V/24 use dm³. Equal gas moles occupy equal volumes only under matching temperature and pressure; equal gas mass need not mean equal volume. Gas coefficient ratios work at matching T/P without assuming RTP. Only species labelled (g) contribute to a gas-volume total. Liquid or solid material still has volume and mass, but its volume cannot be calculated using the molar GAS volume. Dry-methane records measure starting gases at RTP and final dry gases at RTP after complete reaction and collection of all water as liquid. Steam/disilane records instead explicitly keep H2O(g) at their supplied common T/P; do not assume RTP or use 24 for these ratio calculations. Real conversion, gas dissolution, leakage and collection loss may change measured results; ideal complete reactions are stated assumptions. The 3D inventory is illustrative, not one mole, atom trajectories or a laboratory procedure; liquid-water tray size does not encode liquid volume. Original solution questions on this saved legacy route remain recoverable; molar concentration is now taught separately. Written explanations are self-reviewed, never machine evidence.",
  outcomes: [
    "Apply the supplied RTP molar volume with correct mass and cubic units.",
    "Distinguish equal gas amounts, equal mass and matching conditions.",
    "Use gaseous equation coefficients to scale known volumes forwards or backwards.",
    "Include unused gases when finding the final gas inventory.",
    "Exclude solids/liquids from gas totals while conserving all atoms and mass.",
  ],
  warmup: [
    n(
      "w-unit",
      "Recall cubic conversion",
      "Convert 800 cm³ to dm³.",
      0.8,
      "dm³",
      "800/1000=0.800 dm³.",
      "One dm³ contains 1000 cm³.",
    ),
    n(
      "w-amount",
      "Recall the whole molecular mass",
      "N2 has molar mass 28 g/mol. Find the amount in 2.8 g N2.",
      0.1,
      "mol",
      "2.8/28=0.10 mol N2 molecules.",
      "Use N2, not an isolated N atom.",
    ),
  ],
  refresher: [
    c(
      "r-rtp",
      "Choose the applicable conditions",
      "When is the supplied GCSE24 dm³/mol used?",
      "At the stated room temperature and pressure",
      {
        "At any temperature and pressure":
          "Gas volume depends on both conditions.",
        "For a liquid or solid as well":
          "This is a molar gas volume, not a universal material volume.",
      },
      "AQA's stated RTP is 20 °C and 1 atmosphere; use the supplied rounded 24 dm³/mol.",
      "Read the conditions and state of matter.",
    ),
    n(
      "r-volume",
      "Recall gas amount to volume",
      "At RTP, find the volume in cm³ of 0.18 mol gas, using 24 dm³/mol.",
      4320,
      "cm³",
      "0.18×24=4.32 dm³;×1000=4320 cm³.",
      "Find dm³ first, then convert to cm³.",
    ),
    n(
      "r-mass",
      "Convert gas grams to amount",
      "CO2 has molar mass 44 g/mol. Find the amount in 4.4 g.",
      0.1,
      "mol",
      "4.4/44=0.10 mol CO2.",
      "The full molecular formula determines molar mass.",
    ),
    c(
      "r-ratio",
      "Identify the ratio",
      "For N2(g)+3H2(g)→2NH3(g), all gas volumes measured at matching T/P, which volume ratio applies?",
      "1:3:2",
      {
        "14:1:17":
          "Those are not the gaseous coefficients; mass ratios differ.",
        "1:1:1": "Different gases do not all react in equal amounts.",
      },
      "Matching gas conditions make volume proportional to amount; coefficients give1: 3: 2.",
      "Use coefficients, not atomic masses.",
    ),
    c(
      "r-conditions",
      "Check comparability",
      "Equal moles of two gases are measured at different temperatures and pressures. Must their measured volumes be equal?",
      "No: matching conditions are required",
      {
        "Yes: equal moles always means equal volume":
          "The gas-volume relation is conditional on T and P.",
        "Yes: 24 dm³/mol applies everywhere":
          "24 is the supplied RTP value only.",
      },
      "Without matching conditions or further information, equal volume cannot be concluded.",
      "Keep the condition attached to the claim.",
    ),
  ],
  guided: [
    p(
      "g-molar",
      "Moles to gas volume",
      "Initial record: 0.30 mol gas at RTP. Using 24 dm³/mol, find volume in dm³ and cm³.",
      [
        { id: "dm3", label: "Gas volume / dm³", answer: 7.2 },
        { id: "cm3", label: "Gas volume / cm³", answer: 7200 },
      ],
      "V=0.30×24=7.2 dm³=7200 cm³. One mole occupies 24 dm³, not 24 cm³.",
      "Multiply by 24, then match the answer unit.",
      model(
        "molar",
        "Predict volume and test the cubic unit change without changing gas amount.",
      ),
    ),
    p(
      "g-mass",
      "Gas mass to volume",
      "Initial record: 8.8 g O2 at RTP; molar mass 32 g/mol and gas molar volume 24 dm³/mol. Find moles and gas volume.",
      [
        { id: "n", label: "O2 amount / mol", answer: 0.275 },
        { id: "volume", label: "Gas volume / dm³", answer: 6.6 },
      ],
      "n=8.8/32=0.275 mol; V=0.275×24=6.6 dm³. Equal CO2 mass would have different n because its molar mass is 44.",
      "Convert mass to moles before applying molar gas volume.",
      model(
        "mass",
        "Compare equal gas mass with a changed molecular formula, or the same mass expressed in kg.",
      ),
    ),
    p(
      "g-ratio",
      "Scale gaseous coefficients",
      "N2(g)+3H2(g)→2NH3(g), ideal complete conversion. Initial known N2 volume 15 cm³. All gas volumes measured at matching T/P. Find H2 required and NH3 produced.",
      [
        { id: "h2", label: "H2 volume / cm³", answer: 45 },
        { id: "nh3", label: "NH3 volume / cm³", answer: 30 },
      ],
      "The coefficients 1: 3: 2 give H2=3×15=45 cm³ and NH3=2×15=30 cm³.",
      "Find the volume represented by one coefficient part.",
      model(
        "ratio",
        "Use any stated gas volume to reconstruct the 1: 3: 2 equation ratio; do not use a mass ratio.",
      ),
    ),
    p(
      "g-remaining",
      "Count all final dry gases",
      "CH4(g)+2O2(g)→CO2(g)+2H2O(l). Initial 30 cm³ CH4 and 40 cm³ O2 at RTP. Complete reaction; all water collected as liquid; final dry gases measured at RTP. Find CO2 and total final dry gas.",
      [
        { id: "co2", label: "CO2 volume / cm³", answer: 20 },
        { id: "total", label: "Total dry gas / cm³", answer: 30 },
      ],
      "40 cm³ O2 consumes 20 cm³ CH4, producing 20 cm³ CO2. 10 cm³ CH4 remains. Dry total=20+10=30 cm³. The liquid water retains atoms but is not part of gas volume.",
      "Find which gas runs out, then add products and unused gases.",
      model(
        "remaining",
        "Identify unused methane or oxygen as well as product gas. The 3D inventory retains collected water and all atoms.",
      ),
    ),
    p(
      "g-phases",
      "Read the physical states",
      "2Si2H6(g)+7O2(g)→4SiO2(s)+6H2O(g). Initial 20 cm³ Si2H6 and 100 cm³ O2. Complete reaction; water remains vapour. All gas volumes measured at the same supplied T/P. Find steam and total final gas.",
      [
        { id: "steam", label: "Steam volume / cm³", answer: 60 },
        { id: "total", label: "Total final gas / cm³", answer: 90 },
      ],
      "One equation part is 20/2=10 cm³. O2 used 70, leftover 30; steam 60. Total gas=60+30=90 cm³. SiO2 is solid, excluded from the gas total. No RTP or 24 assumption is required.",
      "Use the (g) labels and count unused reactants too.",
      model(
        "phases",
        "Distinguish solid product from gaseous water and include every final gas; these are supplied non-RTP steam records.",
      ),
    ),
  ],
  practice: [
    n(
      "p-molar",
      "Apply RTP molar volume",
      "Using 24 dm³/mol at RTP, find the volume of 0.40 mol gas.",
      9.6,
      "dm³",
      ".40×24=9.6.",
      "Multiply gas moles by the supplied molar volume.",
    ),
    n(
      "p-inverse",
      "Find amount from dm³",
      "At RTP, 1.8 dm³ gas uses 24 dm³/mol. Find moles.",
      0.075,
      "mol",
      "1.8/24=.075.",
      "Divide volume by molar volume.",
    ),
    n(
      "p-cubic",
      "Find amount from cm³",
      "At RTP, 900 cm³ gas uses 24 dm³/mol. Find moles.",
      0.0375,
      "mol",
      "900 cm³=0.900 dm³; n=0.900/24=0.0375.",
      "Do not divide 900by24 and call the answer moles.",
    ),
    n(
      "p-formula",
      "Use O2 molecular mass",
      "Find volume at RTP of 0.64 g O2, M=32 g/mol, using 24 dm³/mol.",
      0.48,
      "dm³",
      "0.64/32=0.020 mol;×24=0.480 dm³.",
      "An oxygen molecule has two oxygen atoms.",
    ),
    n(
      "p-kg",
      "Convert kilograms first",
      "Find RTP volume of 0.142 kg Cl2; M=71 g/mol; 24 dm³/mol.",
      48,
      "dm³",
      "0.142 kg=142 g; n=142/71=2 mol; V=48 dm³.",
      "The molar mass is grams per mole.",
    ),
    n(
      "p-reverse-mass",
      "Find gas mass from volume",
      "At RTP, 1200 cm³ CO2 has molar mass 44 g/mol. Using 24 dm³/mol, find its mass.",
      2.2,
      "g",
      "V=1.2 dm³; n=1.2/24=0.05 mol; m=0.05×44=2.2 g.",
      "Convert volume, find n, then multiply by M.",
    ),
    n(
      "p-reacting-mass",
      "Gas from a solid reactant",
      "Mg+2HCl→MgCl2+H2. Excess HCl; 2.4 g Mg with M=24 g/mol reacts completely. Find H2 volume at RTP, using 24 dm³/mol.",
      2.4,
      "dm³",
      "nMg=2.4/24=0.10 mol; ratio Mg: H2=1: 1; nH2=0.10; V=2.4 dm³.",
      "Convert the solid mass to moles, use the equation ratio, then gas volume.",
    ),
    {
      ...n(
        "p-round",
        "Final gas volume",
        "Find the RTP volume of 27.93 g CO₂. Use M = 44 g/mol and 24 dm³/mol. Give 3 significant figures.",
        15.2,
        "dm³",
        "27.93 ÷ 44 × 24 = 15.234545…; to 3 significant figures, the gas volume is 15.2 dm³.",
        "Round only the final volume.",
      ),
      rounding: { kind: "significant-figures", digits: 3 },
    },
    n(
      "p-titanium",
      "Use mass and a different coefficient",
      "TiO2+2Cl2+2C→TiCl4+2CO. 5.0 kg TiO2 reacts completely; M=80 g/mol. Find required Cl2 volume at RTP, using 24 dm³/mol.",
      3000,
      "dm³",
      "5000/80=62.5 mol TiO2; nCl2=125 mol; V=125×24=3000 dm³.",
      "Cl2 has coefficient 2 for every 1 TiO2.",
    ),
    n(
      "p-nitrogen",
      "Scale known nitrogen volume",
      "N2(g)+3H2(g)→2NH3(g), complete conversion.5 cm³ N2 with enough H2. All gas volumes at matching T/P. Find NH3 volume.",
      10,
      "cm³",
      "5×2/1=10 cm³.",
      "Use NH3: N2=2: 1.",
    ),
    n(
      "p-hydrogen",
      "Work back from hydrogen",
      "N2(g)+3H2(g)→2NH3(g). 60 cm³ H2 reacts completely with enough N2. All gas volumes at matching T/P. Find required N2.",
      20,
      "cm³",
      "60/3×1=20 cm³.",
      "Known gas volume is 3equation parts.",
    ),
    c(
      "p-liquid",
      "Do not use gas volume for liquid",
      "2H2(g)+O2(g)→2H2O(l). Can the liquid water's volume be found by multiplying its moles by 24 dm³/mol?",
      "No: 24 is a molar gas volume",
      {
        "Yes: all substances have the same molar volume":
          "Liquid volume depends on its own physical properties.",
        "No: the liquid has zero volume":
          "It has volume, but is excluded from a GAS-volume total.",
      },
      "A liquid still has mass and volume; the molar gas-volume rule does not give its volume.",
      "Read the state symbol and the quantity requested.",
    ),
    n(
      "p-fractional",
      "Continuous volume ratios",
      "2CO(g)+O2(g)→2CO2(g). 22.5 cm³ CO reacts completely. At matching gas T/P, find O2 required.",
      11.25,
      "cm³",
      "22.5/2×1=11.25 cm³. Do not round the ratio to whole volume units.",
      "Coefficients are whole numbers; volumes need not be.",
    ),
    n(
      "p-backwards",
      "Gas product to reactant",
      "2NO(g)+O2(g)→2NO2(g). 18 cm³ NO2 is produced by ideal complete reaction. All gases measured at matching T/P. Find O2 used.",
      9,
      "cm³",
      "18/2×1=9 cm³.",
      "Use the product coefficient as the known part.",
    ),
    n(
      "p-oxygen-excess",
      "Include excess oxygen",
      "CH4(g)+2O2(g)→CO2(g)+2H2O(l). Initially 12 cm³ CH4 and 40 cm³ O2; complete conversion of the limiting reactant, all water collected as liquid, and initial/final dry gases measured at RTP. Find final dry gas cm³.",
      28,
      "cm³",
      "O2 used 24, left 16; CO2 formed12; total 12+16=28.",
      "Unused oxygen remains a gas.",
    ),
    n(
      "p-methane-excess",
      "Include excess methane",
      "CH4(g)+2O2(g)→CO2(g)+2H2O(l). Initially 20 cm³ CH4 and 30 cm³ O2; complete conversion of the limiting reactant, all water collected as liquid, and initial/final dry gases measured at RTP. Find final dry gas cm³.",
      20,
      "cm³",
      "30 cm³ O2 reacts with 15 cm³ CH4; CO2=15, CH4 left 5; total 20.",
      "Compare V/coefficient before constructing the final inventory.",
    ),
    n(
      "p-stoichiometric",
      "No unused reactant",
      "CH4(g)+2O2(g)→CO2(g)+2H2O(l). Initially 5 cm³ CH4 and 10 cm³ O2; complete conversion of both reactants, all water collected as liquid, and initial/final dry gases measured at RTP. Find final dry gas cm³.",
      5,
      "cm³",
      "Both reactants are in the 1: 2ratio; CO2=5 and no unused gas remains.",
      "Water is collected liquid, not final dry gas.",
    ),
    n(
      "p-steam",
      "Count gaseous water",
      "2Si2H6(g)+7O2(g)→4SiO2(s)+6H2O(g). 12 cm³ Si2H6 reacts with 60 cm³ O2; water remains vapour; gas volumes at one common supplied T/P. Find final total gas.",
      54,
      "cm³",
      "One part 6 cm³; O2used42, left18; steam36; total54.",
      "Include steam and unused oxygen; exclude solid SiO2.",
    ),
    n(
      "p-unit-ratio",
      "Match cubic units across a ratio",
      "N2(g)+3H2(g)→2NH3(g). 0.018 dm³ N2 reacts completely. At matching gas T/P, find H2 required in cm³.",
      54,
      "cm³",
      "N2=18 cm³; H2=3×18=54 cm³.",
      "Convert to a common volume unit before using coefficients.",
    ),
    w(
      "p-equal-volume",
      "Explain equal volumes",
      "Compare equal volumes of CH4 and O2 at the same T/P. Explain their molecule counts and masses, given molar masses 16 and 32 g/mol.",
      "Equal gas volumes at the same T/P contain equal moles and equal numbers of molecules. They do not have equal masses: with the same n, m=nM gives twice the mass for O2. They also contain different total atom counts per molecule, 5 for CH4 and 2 for O2.",
      [
        "Link equal volumes to equal moles under matching conditions.",
        "Distinguish molecules from total atoms.",
        "Use molar mass to explain unequal masses.",
      ],
    ),
    w(
      "p-conservation",
      "Explain volume versus conserved mass",
      "In the methane model, initial 7 gas molecules become 3 dry-gas molecules plus 4 water molecules collected as liquid. Explain why the dry gas volume falls although all atoms remain.",
      "At the matching initial/final gas T/P, dry gas volume tracks gas amount, which falls from 7to3illustrative units. Four intact water molecules are retained as liquid and excluded from gas amount. All C, H, O atoms and total mass remain in the complete inventory; gas volume and gas-only mass need not be conserved.",
      [
        "Count only gaseous species for gas volume.",
        "Retain the collected liquid water in atom/mass accounting.",
        "State matching gas T/P and distinguish total mass from gas-only quantities.",
      ],
    ),
  ],
  checkForms: [
    [
      p(
        "ca-mass",
        "Independent molecular mass transfer",
        "2.56 g SO2 at RTP has M=64 g/mol. Using 24 dm³/mol, find gas amount and volume.",
        [
          { id: "n", label: "SO2 amount / mol", answer: 0.04 },
          { id: "v", label: "Gas volume / dm³", answer: 0.96 },
        ],
        "2.56/64=0.040 mol;×24=0.960 dm³.",
        "Use the named molecule and the supplied conditions.",
      ),
      n(
        "ca-inverse",
        "Independent cubic inverse",
        "At RTP, 720 cm³ gas uses 24 dm³/mol. Find moles.",
        0.03,
        "mol",
        "0.720/24=0.030.",
        "Convert cm³ to dm³ first.",
      ),
      n(
        "ca-ratio",
        "Independent new equation",
        "4NH3(g)+5O2(g)→4NO(g)+6H2O(g). 32 cm³ NH3 reacts completely. At matching gas T/P, find O2 required.",
        40,
        "cm³",
        "32/4×5=40 cm³.",
        "Use gas coefficients, not the sum of all coefficients.",
      ),
      n(
        "ca-dry",
        "Independent dry inventory",
        "CH4(g)+2O2(g)→CO2(g)+2H2O(l). Initially 8 cm³ CH4 and 22 cm³ O2; complete conversion of the limiting reactant, all water collected as liquid, and initial/final dry gases measured at RTP. Find total final dry gas.",
        14,
        "cm³",
        "O2used16,left6;CO2=8;total14.",
        "Add every final gas, not just CO2.",
      ),
      w(
        "ca-proof",
        "Independent volume comparison",
        "Equal 0.24 dm³ volumes of CH4 and O2 are measured at RTP. M values 16 and 32 g/mol; 24 dm³/mol. Explain their amounts, masses and why equal volume does not mean equal mass.",
        "Each gas has n=0.24/24=0.010 mol. CH4 mass=0.010×16=0.160 g; O2 mass=0.010×32=0.320 g. Equal volume under matching T/P ensures equal gas amount, but mass also depends on molar mass.",
        [
          "Show both gas amounts are.010 mol.",
          "Find.160 g and.320 g.",
          "Explain the condition and molar-mass distinction.",
        ],
      ),
    ],
    [
      p(
        "cb-mass",
        "Independent changed gas",
        "0.84 g N2 at RTP; M=28 g/mol; 24 dm³/mol. Find amount and volume.",
        [
          { id: "n", label: "N2 amount / mol", answer: 0.03 },
          { id: "v", label: "Gas volume / dm³", answer: 0.72 },
        ],
        "0.84/28=0.030 mol;×24=0.720 dm³.",
        "Keep amount and volume units distinct.",
      ),
      n(
        "cb-inverse",
        "Independent changed cubic volume",
        "At RTP, 1680 cm³ gas uses 24 dm³/mol. Find moles.",
        0.07,
        "mol",
        "1.680/24=0.070.",
        "Convert first, then divide by 24.",
      ),
      n(
        "cb-ratio",
        "Independent reverse gas ratio",
        "2CO(g)+O2(g)→2CO2(g). 20 cm³ CO2 is formed by complete conversion. At matching gas T/P, find O2 used.",
        10,
        "cm³",
        "20/2×1=10 cm³.",
        "Use the known gas product coefficient.",
      ),
      n(
        "cb-steam",
        "Independent supplied steam inventory",
        "2Si2H6(g) + 7O2(g) → 4SiO2(s) + 6H2O(g). 16 cm³ Si2H6 reacts completely with 70 cm³ O2; water remains gas; all gas volumes measured at one common supplied T/P. Find final total gas.",
        62,
        "cm³",
        "One part 8; O2used56, left14; steam48; total62.",
        "SiO2 is solid; steam and unused oxygen are gases.",
      ),
      w(
        "cb-proof",
        "Independent conditions review",
        "A student uses 24 dm³/mol for a gas sample whose temperature and pressure are not given, then uses the same rule to calculate liquid-water volume. Explain both limitations.",
        "24 dm³/mol is the supplied RTP gas value; without applicable conditions or a supplied molar volume it cannot be assumed. Gas volume depends on temperature and pressure. Liquid water has its own molar volume and density; the molar GAS-volume rule does not determine its volume, and it is excluded from a gas-volume total.",
        [
          "Restrict 24 dm³/mol to its specified conditions.",
          "State that gas volume depends on T/P.",
          "Distinguish liquid volume from gas molar volume without claiming liquid has zero volume.",
        ],
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "ra-molar",
        "Retrieve molar volume",
        "At RTP, find the volume of 0.35 mol gas using 24 dm³/mol.",
        8.4,
        "dm³",
        ".35×24=8.4.",
        "Multiply amount by molar volume.",
      ),
      n(
        "ra-mass",
        "Retrieve full formula mass",
        "4.48 g SO2 at RTP; M=64 g/mol; 24 dm³/mol. Find gas volume.",
        1.68,
        "dm³",
        "4.48/64=.07mol;V=1.68.",
        "Use mass→amount→gas volume.",
      ),
      n(
        "ra-dry",
        "Retrieve unused gas",
        "CH4(g)+2O2(g)→CO2(g)+2H2O(l). Initially 25 cm³ CH4 and 40 cm³ O2; complete conversion of the limiting reactant, all water collected as liquid, and initial/final dry gases measured at RTP. Find final dry gas.",
        25,
        "cm³",
        "20 cm³ CH4 reacts;CO2=20,CH4 left 5;total 25.",
        "Identify the unused gas before adding the final inventory.",
      ),
    ],
    [
      n(
        "rb-molar",
        "Retrieve cubic inverse",
        "At RTP, 2640 cm³ gas uses 24 dm³/mol. Find moles.",
        0.11,
        "mol",
        "2.640/24=0.110.",
        "Match volume units with molar volume.",
      ),
      n(
        "rb-mass",
        "Retrieve solid-to-gas transfer",
        "Zn+2HCl→ZnCl2+H2. 3.25 g Zn, M=65 g/mol, reacts completely with excess HCl. Find H2 at RTP using 24 dm³/mol.",
        1.2,
        "dm³",
        "nZn=0.05; nH2=0.05; V=1.2 dm³.",
        "Use the equation mole ratio after finding amount.",
      ),
      n(
        "rb-ratio",
        "Retrieve gaseous scaling",
        "N2(g)+3H2(g)→2NH3(g). 8 cm³ N2 reacts completely with enough H2. Matching gas T/P. Find NH3 volume.",
        16,
        "cm³",
        "8×2=16.",
        "Use gas coefficients at matching conditions.",
      ),
    ],
  ],
};
gasVolumesJourney.guided[0].openingHint = true;
gasVolumesJourney.practice.find((q) => q.id === "gv-v1-p-cubic")!.followUp =
  "gv-v1-r-volume";
gasVolumesJourney.practice.find((q) => q.id === "gv-v1-p-formula")!.followUp =
  "gv-v1-r-mass";
gasVolumesJourney.practice.find((q) => q.id === "gv-v1-p-liquid")!.followUp =
  "gv-v1-r-rtp";
