import type { LearningTask, LessonJourney, TaskModel } from "../types";
import type { HalfEquationKey, HalfMode } from "../../lib/half-equations";
import { choice, number } from "./helpers";
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...choice(
    "he-v1-" + id,
    prompt,
    answer,
    errors,
    explanation,
    hint,
    title,
    model,
  ),
  title,
});
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...number(
    "he-v1-" + id,
    prompt,
    answer,
    unit,
    explanation,
    hint,
    title,
    {},
    model,
  ),
  title,
});
const e = (
  id: string,
  title: string,
  prompt: string,
  reaction: HalfEquationKey,
  answer: string,
  explanation: string,
  hint: string,
  model?: TaskModel,
  simplest = false,
): LearningTask => ({
  id: "he-v1-" + id,
  title,
  prompt,
  answer,
  explanation,
  hint,
  purpose: title,
  inputMode: "text",
  electronEquation: { reaction, simplest },
  model,
});
const w = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  points: string[],
): LearningTask => ({
  id: "he-v1-" + id,
  title,
  prompt,
  answer,
  explanation: answer,
  hint: points[0],
  rubric: points,
  purpose: title,
});
const m = (mode: HalfMode, instruction: string): TaskModel => ({
  kind: "electron-redox",
  mode,
  instruction,
});
export const halfEquationsJourney: LessonJourney = {
  version: 1,
  introduction:
    "Track electron gain and loss, then balance fixed chemical species using both atom counts and signed charge.",
  scopeNote:
    "Higher/shared AQA 4.4.1.4, the specified metal/acid redox in 4.4.2.1 and electrode half equations 4.4.3.5; related visibly bold Pearson Combined 3.27–3.29. Foundation aqueous products and active/inert electrode practical reasoning are taught separately in the preceding lesson. Oxidation is electron loss; reduction is electron gain. Electrons have charge −1 and are not new atoms or protons. Gaining electrons makes the represented species charge more negative; losing electrons makes it more positive, with nuclear identity unchanged. A positive ion can be oxidised, as Fe2+ → Fe3+ +e−: charge sign alone does not name oxidation or reduction. In electrolytic cells cathode is negative/reduction and anode positive/oxidation. Mobile ions carry charge through electrolyte; electrons flow through the external circuit and electrodes, not as the ionic current carrier in solution. Half equations must retain each element and total charge; balance fixed formulas using coefficients, not by changing subscripts or ionic charges. Diatomic H2/Cl2/Br2/O2 products require two atoms per molecule. Hydroxide oxidation needs water: 4OH− → O2 +2H2O +4e− retains O4H4, charge −4 including electrons. The true selected-atom asset shows four hydroxide ions before and O2 plus two bent 104.5° water molecules afterwards; eight atomic IDs retained. Background solvent and hydration shells are omitted. Product atoms have charge 0; four electrons leave into the external circuit, retaining total charge −4 when external transfer is included. Electrons are separately accounted charge, not atomic meshes or dissolved classical spheres. Comparison positions and frames are not migration paths, kinetics or a complete apparatus. Atom and charge balance can fail independently. Positive balanced multiples are accepted, as actual AQA 2019 Higher 07.3 explicitly allows; only tasks explicitly requiring smallest integers reject an unsimplified multiple. Typed equations accept common charged ASCII/caret and Unicode forms, reordered terms, appropriate optional states and AQA’s equivalent oxidation notation subtracting charged electrons on the left; an uncharged e is not accepted. This is specific equation checking, not automatic partial examiner marks or readiness evidence. Full ionic redox equations cancel electron transfer; spectators retain their species and are omitted from the net ionic equation. Zinc/copper sulfate and copper/silver nitrate cases are supplied; Mg/Zn/Fe acid redox is limited to the stated HCl/H2SO4 GCSE cases, with Fe2+ supplied rather than invented Fe3+. Six written explanations remain self-reviewed.",
  outcomes: [
    "Use electron gain/loss to explain signed charge change without changing protons.",
    "Write charged half equations that conserve atoms and total charge.",
    "Retain diatomic products and water in hydroxide oxidation.",
    "Distinguish atom balance, charge balance and their independent failures.",
    "Write supplied net ionic displacement/acid equations and identify spectators.",
  ],
  warmup: [
    n(
      "w-charge",
      "Recall total signed charge",
      "A Cu2+ ion combines with two electrons of charge −1 each. What is the resulting total charge?",
      0,
      "",
      "2 + 2 × (−1) = 0.",
      "Add signed charges.",
    ),
    n(
      "w-atoms",
      "Recall a diatomic formula",
      "How many hydrogen atoms are represented by one H2 molecule?",
      2,
      "atoms",
      "The subscript 2 counts two H atoms.",
      "Keep the product formula fixed.",
    ),
  ],
  refresher: [
    c(
      "r-direction",
      "Use electron charge",
      "What happens to a species' charge when it gains one electron, with its nucleus unchanged?",
      "The charge decreases by 1",
      {
        "The charge increases by 1": "An electron contributes −1.",
        "Its proton count decreases by 1":
          "Electron gain does not remove a proton.",
      },
      "Adding negative charge decreases the signed total.",
      "Electrons have charge −1.",
      m(
        "electrons",
        "Gain or lose one electron at a time; follow charge and classify redox.",
      ),
    ),
    n(
      "r-count",
      "Count the transferred electrons",
      "How many electrons must Cu2+ gain to become neutral Cu?",
      2,
      "electrons",
      "Two −1 electron charges balance +2.",
      "Keep the nuclear identity.",
    ),
    n(
      "r-diatomic",
      "Count chloride constituents",
      "How many chloride ions supply the two chlorine atoms in one Cl2 molecule?",
      2,
      "ions",
      "Two Cl− ions provide the two Cl atoms.",
      "Ion and product have different charges, not different elements.",
    ),
    e(
      "r-water",
      "Restore missing water",
      "Write the balanced oxidation half equation for OH− giving O2, H2O and electrons.",
      "hydroxide",
      "4OH- -> O2 + 2H2O + 4e-",
      "Four oxygen and four hydrogen atoms are retained; both sides have total charge −4.",
      "Balance H and O, then charge.",
      m(
        "anion",
        "Build the hydroxide equation with fixed species, including water.",
      ),
    ),
    c(
      "r-two-checks",
      "Check atoms and charge",
      "Cu2+ + e− → Cu has which balance?",
      "Atoms only",
      {
        "Charge only": "Copper atoms match, but+2−1 does not equal 0.",
        "Both atoms and charge": "The left charge is +1, not 0.",
      },
      "One Cu is on each side; charges +1 and 0 differ.",
      "Compute both totals.",
      m("diagnose", "Classify atom and charge balance independently."),
    ),
    c(
      "r-spectator",
      "Find an unchanged ion",
      "In Zn + CuSO4(aq) → ZnSO4(aq) + Cu, which supplied dissolved ion is a spectator?",
      "Sulfate, SO4²−",
      {
        "Copper ion, Cu2+": "It becomes copper metal.",
        "Zinc, Zn": "It becomes zinc ions.",
      },
      "Sulfate retains its identity while the metals change charge.",
      "Find what remains unchanged.",
      m(
        "ionic",
        "Identify oxidised/reduced species and an unchanged counter-ion.",
      ),
    ),
  ],
  guided: [
    {
      ...n(
        "g-electrons",
        "Gain electrons",
        "Cu2+ → Cu: how many electrons are gained?",
        2,
        "electrons",
        "Cu2+ gains two electrons to reach charge 0; this is reduction.",
        "Each gained electron lowers the charge by 1.",
        m("electrons", "Gain or lose one electron per step."),
      ),
      openingHint: true,
    },
    e(
      "g-cation",
      "Write the cathode half equation",
      "Write the reduction half equation for Cu2+ becoming Cu at the negative cathode.",
      "copper",
      "Cu2+ + 2e- -> Cu",
      "One Cu on each side; +2 +2(−1)=0. Electrons are reactants.",
      "Balance atoms, then charge.",
      m(
        "cation",
        "Set each coefficient and the electron side; positive balanced multiples are valid.",
      ),
    ),
    e(
      "g-anode",
      "Keep the hydrogen in water",
      "Write the oxidation half equation for hydroxide ions producing O2 and H2O at a positive inert anode.",
      "hydroxide",
      "4OH- -> O2 + 2H2O + 4e-",
      "O4H4 is conserved and both sides have charge −4.",
      "Water retains the H atoms.",
      m(
        "anion",
        "Use the real selected-atom reference and account for electrons leaving the anode into the external circuit.",
      ),
    ),
    c(
      "g-diagnose",
      "Separate the two constraints",
      "Initial diagnostic: Cu2+ + e− → Cu. Which statement is correct?",
      "Atoms balance but charge does not",
      {
        "Charge balances but atoms do not":
          "One Cu is on each side, while left charge +1 differs from 0.",
        "Both balance": "One electron is insufficient to balance +2.",
      },
      "Atom balance alone is insufficient.",
      "Compare element totals and signed charge separately.",
      m("diagnose", "Test valid, atom-only, charge-only and neither cases."),
    ),
    e(
      "g-ionic",
      "Write the net ionic reaction",
      "Zinc displaces copper from copper sulfate solution. Write the net ionic equation; sulfate is unchanged.",
      "netZinc",
      "Zn + Cu2+ -> Zn2+ + Cu",
      "Zn loses two electrons while Cu2+ gains them; sulfate is omitted as spectator.",
      "Use the species that change.",
      m(
        "ionic",
        "Predict oxidation, reduction and spectator identity before writing the fixed question's equation.",
      ),
    ),
  ],
  practice: [
    n(
      "p-count",
      "Scale transferred electrons",
      "Three Cu2+ ions each become neutral Cu. How many electrons are gained in total?",
      6,
      "electrons",
      "3 × 2 = 6 electrons.",
      "Count electrons for every ion.",
      m(
        "electrons",
        "The native model tracks one representative ion; this question scales to three.",
      ),
    ),
    e(
      "p-silver",
      "Reduce a single-charge ion",
      "Write the cathode half equation for Ag+ becoming Ag.",
      "silver",
      "Ag+ + e- -> Ag",
      "One +1 charge is balanced by one −1 electron.",
      "Retain one Ag atom.",
    ),
    e(
      "p-aluminium",
      "Reduce a three-charge ion",
      "Write the half equation for Al3+ becoming Al in the supplied molten extraction cell.",
      "aluminium",
      "Al3+ + 3e- -> Al",
      "Three electrons balance +3.",
      "The starting species is an ion.",
      m(
        "cation",
        "Explore the aluminium record, then answer the stated equation.",
      ),
    ),
    e(
      "p-hydrogen",
      "Balance a diatomic cathode gas",
      "Write the supplied GCSE half equation for H+ producing H2 at cathode.",
      "hydrogen",
      "2H+ + 2e- -> H2",
      "Two H atoms and total charge 0 on each side.",
      "Do not change H2 into H.",
      m("cation", "A diatomic product changes the required ion coefficient."),
    ),
    c(
      "p-ions",
      "Name the gaining species",
      "During aluminium electrolysis, which statement describes the cathode process?",
      "Aluminium ions gain electrons",
      {
        "Aluminium atoms gain electrons to form Al3+":
          "Gain makes charge more negative, not +3.",
        "Aluminium ions lose electrons":
          "That would be oxidation, not the cathode reduction.",
      },
      "Al3+ gains electrons to become Al.",
      "Distinguish ion from atom.",
    ),
    e(
      "p-chloride",
      "Oxidise a halide",
      "Write the half equation for Cl− producing Cl2 at anode.",
      "chloride",
      "2Cl- -> Cl2 + 2e-",
      "Two chloride atoms remain and charges−2 match.",
      "The electrons are products.",
      m("anion", "Explore chloride, keeping its neutral diatomic product."),
    ),
    e(
      "p-bromide",
      "Transfer the halide pattern",
      "Write the half equation for Br− producing Br2 at anode.",
      "bromide",
      "2Br- -> Br2 + 2e-",
      "Two Br atoms and charge −2 on each side.",
      "Keep Br2 and electron charge.",
    ),
    e(
      "p-oxide",
      "Distinguish oxide from oxygen",
      "Monatomic oxide ions have charge 2−. Write their oxidation half equation producing O2.",
      "oxide",
      "2O^2- -> O2 + 4e-",
      "Two oxide ions supply two O atoms and charge −4; four electrons retain that charge.",
      "O^2- is monatomic oxide; O2 is the neutral molecule.",
      m(
        "anion",
        "Read the supplied oxide record, not the aqueous hydroxide case.",
      ),
    ),
    e(
      "p-hydroxide",
      "Retain both elements",
      "Write the oxidation half equation for OH− producing O2 and water.",
      "hydroxide",
      "4OH- -> O2 + 2H2O + 4e-",
      "The four H atoms remain in two water molecules; four O atoms and charge −4 are retained.",
      "Do not discard H atoms.",
      m(
        "anion",
        "The reference shows products and the external electron account.",
      ),
    ),
    c(
      "p-water",
      "Locate the retained hydrogen",
      "In 4OH− → O2 +2H2O +4e−, where are the four starting H atoms?",
      "In the two water molecules",
      {
        "In the electron terms": "Electrons are not H atoms.",
        "They disappear when oxygen forms": "Atoms are conserved.",
      },
      "Two H2O molecules contain four H atoms.",
      "Read the water coefficient and subscript.",
    ),
    e(
      "p-sodium-oxidation",
      "Oxidise a neutral metal",
      "Sodium atoms become Na+ in a supplied displacement reaction. Write the oxidation half equation.",
      "sodiumOxidation",
      "Na -> Na+ + e-",
      "Losing one electron gives +1; right-side charges +1−1=0.",
      "Use charged e−, not uncharged e.",
    ),
    e(
      "p-iron-ion",
      "Oxidise an already positive ion",
      "Write the half equation for Fe2+ becoming Fe3+.",
      "ironOxidation",
      "Fe2+ -> Fe3+ + e-",
      "One electron is lost; +3−1=+2.",
      "A positive ion can lose an electron.",
      m(
        "anion",
        "The oxidation mode also includes metal atoms and positive-ion oxidation.",
      ),
    ),
    c(
      "p-multiple",
      "Recognise a valid multiple",
      "Is 4Cl− → 2Cl2 +4e− balanced when the question does not demand the smallest coefficients?",
      "Yes: atoms and charge balance",
      {
        "No: only 2Cl− → Cl2 +2e− is ever valid":
          "The supplied equation is a positive multiple.",
        "No: its electrons should be reactants":
          "Chloride oxidation releases electrons.",
      },
      "Four Cl atoms and charge −4 are on each side.",
      "Check totals before simplifying.",
    ),
    e(
      "p-minimum",
      "Follow an explicit smallest-ratio demand",
      "Write Cu2+ → Cu reduction using the smallest whole-number coefficients.",
      "copper",
      "Cu2+ + 2e- -> Cu",
      "Coefficients 1, 2, 1 are the simplest; an unsimplified multiple is balanced but does not meet this explicit demand.",
      "Balance first, then simplify.",
      undefined,
      true,
    ),
    c(
      "p-charge-only",
      "Spot a different failure",
      "Cu2+ +2e− → 2Cu has which balance?",
      "Charge only",
      {
        "Atoms only": "There is one Cu before and two after.",
        Both: "Charge balance cannot fix the extra Cu atom.",
      },
      "Both charges are 0, but copper counts 1 and 2 differ.",
      "Do not stop after checking charge.",
      m("diagnose", "Select the charge-only record."),
    ),
    c(
      "p-displacement",
      "Identify both redox changes",
      "In Zn +Cu2+ → Zn2+ +Cu, which species are oxidised and reduced?",
      "Zn oxidised; Cu2+ reduced",
      {
        "Zn reduced; Cu2+ oxidised": "Zn loses electrons and Cu2+ gains them.",
        "Sulfate oxidised; Zn reduced":
          "Sulfate is unchanged in the supplied solution reaction.",
      },
      "Zn goes 0→+2 through loss; Cu2+ goes +2→0 through gain.",
      "Follow electron transfer.",
      m("ionic", "Separate reactive species from the sulfate spectator."),
    ),
    e(
      "p-magnesium",
      "Write acid redox ionically",
      "Magnesium reacts with hydrochloric acid, giving Mg2+ and H2. Write the net ionic equation; chloride is unchanged.",
      "netMagnesium",
      "Mg + 2H+ -> Mg2+ + H2",
      "Mg loses two electrons, two H+ gain them; charge +2 and Mg1H2 remain.",
      "Keep the diatomic gas and omit chloride.",
    ),
    e(
      "p-iron-acid",
      "Keep the supplied iron ion",
      "Iron reacts with sulfuric acid in this GCSE case, forming Fe2+ and H2. Write the net ionic equation.",
      "netIron",
      "Fe + 2H+ -> Fe2+ + H2",
      "Fe2+ is supplied; one Fe and two H atoms remain, charge +2 each side.",
      "Do not invent Fe3+.",
      m("ionic", "Explore the iron/acid record."),
    ),
    w(
      "p-carriers",
      "Explain current carriers",
      "Explain why electrons in a half equation should not be described as the mobile ionic charge carriers in the electrolyte.",
      "Electrons are transferred at electrodes and flow through the external conducting circuit. Mobile ions carry charge through the electrolyte. Electron terms account for gain/loss, not dissolved classical electron spheres.",
      [
        "Distinguish ions in solution from electrons in the circuit.",
        "Connect electrode electron gain/loss to the half equation.",
        "Do not change nuclear identity.",
      ],
    ),
    w(
      "p-definition",
      "Use the Higher redox definition",
      "Zinc displaces copper from copper sulfate without transferring oxygen between these metal species. Explain why it is still redox.",
      "Zinc loses electrons and is oxidised, while copper ions gain electrons and are reduced. Electron gain/loss establishes redox even without oxygen transfer between the metals.",
      [
        "State zinc electron loss.",
        "State copper-ion electron gain.",
        "Use the Higher electron definition rather than requiring oxygen transfer.",
      ],
    ),
  ],
  checkForms: [
    [
      e(
        "a-nickel",
        "Independent supplied reduction",
        "Given Ni2+ gains electrons to become Ni, write that reduction half equation. This is a supplied reaction, not a request to predict aqueous products.",
        "nickel",
        "Ni2+ +2e- -> Ni",
        "One Ni atom and total charge 0 remain.",
        "Keep the supplied species and balance charge.",
      ),
      e(
        "a-iodide",
        "Independent supplied oxidation",
        "Write the supplied oxidation half equation for I− producing I2.",
        "iodide",
        "2I- -> I2 +2e-",
        "Two I atoms and charge −2 remain.",
        "Keep the neutral diatomic product.",
      ),
      c(
        "a-diagnose",
        "Independent balance claim",
        "Al3+ +2e− → Al has which balance?",
        "Atoms only",
        {
          "Charge only": "There is one Al each side.",
          "Both atoms and charge": "Left charge +1 differs from 0.",
        },
        "Al counts match; charge does not.",
        "Check both constraints.",
      ),
      c(
        "a-ionic",
        "Independent displacement",
        "In supplied Mg +Cu2+ → Mg2+ +Cu, which species is oxidised?",
        "Mg",
        {
          "Cu2+": "Copper ions gain electrons and are reduced.",
          Sulfate: "A supplied sulfate counter-ion remains unchanged.",
        },
        "Mg loses electrons to become Mg2+.",
        "Identify the electron donor.",
      ),
      w(
        "a-explain",
        "Independent charge explanation",
        "Explain why an ion becoming more positively charged can indicate oxidation without changing its element.",
        "Loss of negative electrons makes its charge more positive and is oxidation. Its proton number and element identity remain unchanged.",
        [
          "Use electron loss.",
          "Explain the signed charge change.",
          "Keep proton number unchanged.",
        ],
      ),
    ],
    [
      e(
        "b-zinc",
        "Independent molten cathode",
        "Write the half equation for Zn2+ producing Zn at the cathode in supplied molten zinc chloride.",
        "zincReduction",
        "Zn2+ +2e- -> Zn",
        "One Zn atom and charge 0 remain.",
        "Use the supplied molten case.",
      ),
      n(
        "b-hydroxide-count",
        "Independent hydroxide charge",
        "In 8OH− → 2O2 +4H2O +n e−, what value of n balances the total charge?",
        8,
        "electrons",
        "Left charge −8 requires eight −1 electrons on the right.",
        "Water and oxygen are neutral.",
      ),
      e(
        "b-iron-metal",
        "Independent metal oxidation",
        "In a supplied acid reaction, Fe becomes Fe2+. Write its oxidation half equation.",
        "ironMetalOxidation",
        "Fe -> Fe2+ +2e-",
        "Charges 0 and +2−2 agree.",
        "Keep the supplied iron-ion charge.",
      ),
      e(
        "b-zinc-acid",
        "Independent ionic acid reaction",
        "Zinc reacts with hydrochloric acid, forming Zn2+ and H2. Write the net ionic equation; chloride remains unchanged.",
        "netZincAcid",
        "Zn +2H+ -> Zn2+ +H2",
        "Zn1H2 and charge +2 remain.",
        "Omit the unchanged chloride.",
      ),
      w(
        "b-explain",
        "Independent retained-water explanation",
        "Explain why 4OH− → O2 +4e− is not a balanced half equation even though its charges match.",
        "The starting ions contain four O and four H atoms. O2 contains only two O and no H. Adding two H2O retains the missing two O and four H; charge must also be checked.",
        [
          "Identify matching charge −4.",
          "Count O and H independently.",
          "Explain the required two water molecules.",
        ],
      ),
    ],
  ],
  reviewForms: [
    [
      e(
        "ra-sodium",
        "Delayed molten reduction",
        "Write the half equation for Na+ forming Na in supplied molten sodium chloride.",
        "sodium",
        "Na+ +e- -> Na",
        "One Na atom and charge 0 remain.",
        "This supplied melt has no water.",
      ),
      c(
        "ra-iron",
        "Delayed ion oxidation",
        "Fe2+ → Fe3+ +e− represents which process?",
        "Oxidation",
        {
          Reduction: "An electron is lost, not gained.",
          "Neither, because Fe2+ is already positive":
            "Charge sign does not define redox.",
        },
        "Electron loss defines oxidation.",
        "Follow the electron term.",
      ),
      w(
        "ra-explain",
        "Delayed dual constraint",
        "Explain why balancing element counts alone cannot guarantee a correct half equation.",
        "Element counts can match while the electron coefficient or electron side leaves unequal total charge. Each electron contributes −1, so atom conservation and charge conservation must both be checked.",
        [
          "Check each element.",
          "Check signed total charge including electrons.",
          "Keep species formulas fixed.",
        ],
      ),
    ],
    [
      e(
        "rb-iron",
        "Delayed ion reduction",
        "Given Fe3+ becomes Fe2+, write the supplied reduction half equation.",
        "ironReduction",
        "Fe3+ +e- -> Fe2+",
        "An electron lowers +3 to +2; Fe remains Fe.",
        "Keep both supplied ionic charges.",
      ),
      e(
        "rb-silver",
        "Delayed net displacement",
        "In the supplied copper/silver nitrate displacement, Cu becomes Cu2+ and Ag+ becomes Ag. Write the net ionic equation.",
        "netSilver",
        "Cu + 2Ag+ -> Cu2+ + 2Ag",
        "One Cu and two Ag atoms remain; total charge +2 each side.",
        "Match the transferred electrons and omit nitrate.",
      ),
      w(
        "rb-explain",
        "Delayed external charge account",
        "The selected hydroxide model has charge −4 before and neutral molecular products after. Explain how charge is retained when electron transfer is included.",
        "Four electrons of total charge −4 leave the anode into the external circuit. Neutral O2 and two H2O have charge 0, so products plus that external electron transfer retain total −4; the electrons are not additional atoms.",
        [
          "Account for four electrons and their −4 charge.",
          "Include the external circuit rather than dissolved electrons.",
          "Retain all O4H4 atomic identities.",
        ],
      ),
    ],
  ],
};
const follow: Record<string, string> = {
  "p-count": "r-count",
  "p-silver": "r-count",
  "p-aluminium": "r-count",
  "p-hydrogen": "r-diatomic",
  "p-ions": "r-direction",
  "p-chloride": "r-diatomic",
  "p-bromide": "r-diatomic",
  "p-oxide": "r-two-checks",
  "p-hydroxide": "r-water",
  "p-water": "r-water",
  "p-sodium-oxidation": "r-direction",
  "p-iron-ion": "r-direction",
  "p-multiple": "r-two-checks",
  "p-minimum": "r-count",
  "p-charge-only": "r-two-checks",
  "p-displacement": "r-spectator",
  "p-magnesium": "r-spectator",
  "p-iron-acid": "r-spectator",
  "p-carriers": "r-direction",
  "p-definition": "r-direction",
};
for (const q of halfEquationsJourney.practice)
  q.followUp = "he-v1-" + follow[q.id.replace("he-v1-", "")];

// Exact repeated equation demands share exposure across stages and sessions.
const equationGroups: Record<string, LearningTask[]> = {};
for (const q of [
  ...halfEquationsJourney.warmup,
  ...halfEquationsJourney.refresher,
  ...halfEquationsJourney.guided,
  ...halfEquationsJourney.practice,
  ...halfEquationsJourney.checkForms.flat(),
  ...halfEquationsJourney.reviewForms.flat(),
]) {
  if (q.electronEquation)
    (equationGroups[q.electronEquation.reaction] ??= []).push(q);
}
for (const group of Object.values(equationGroups))
  for (const q of group)
    q.exposureAliases = group
      .filter((other) => other.id !== q.id)
      .map((other) => other.id);
const chargeRepeat = ["he-v1-r-count", "he-v1-g-electrons"];
for (const q of [
  ...halfEquationsJourney.refresher,
  ...halfEquationsJourney.guided,
])
  if (chargeRepeat.includes(q.id))
    q.exposureAliases = chargeRepeat.filter((id) => id !== q.id);
