import type { LearningTask, LessonJourney, TaskModel } from "../types";
import { choice, number } from "./helpers";
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...number(
    `mc-v1-${id}`,
    prompt,
    answer,
    unit,
    explanation,
    hint,
    title,
    {},
    model,
  ),
  title,
});
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...choice(`mc-v1-${id}`, prompt, answer, errors, explanation, hint, title),
  title,
});
const p = (
  id: string,
  title: string,
  prompt: string,
  parts: { id: string; label: string; answer: number }[],
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  id: `mc-v1-${id}`,
  title,
  prompt,
  parts,
  partLegend: title,
  answer: JSON.stringify(
    Object.fromEntries(parts.map((v) => [v.id, String(v.answer)])),
  ),
  explanation,
  hint,
  purpose: title,
  model,
});
const w = (
  id: string,
  title: string,
  prompt: string,
  explanation: string,
  rubric: string[],
): LearningTask => ({
  id: `mc-v1-${id}`,
  title,
  prompt,
  answer: explanation,
  explanation,
  rubric,
  hint: "Name the quantity retained, show the relationship and explain the change.",
  purpose: title,
});
const model = (
  mode: "concentration" | "amount" | "mass" | "units" | "sampling",
  instruction: string,
): TaskModel => ({ kind: "molar-concentration", mode, instruction });
export const molarConcentrationJourney: LessonJourney = {
  version: 1,
  introduction:
    "Use concentration to connect a dissolved amount, its mass and the final solution volume.",
  scopeNote:
    "Higher separate Chemistry: the concentration/amount/mass part of AQA 4.3.4. Use c=n/V with V in dm³; n=cV and m=nM. M is molar mass in g/mol; Mr is relative formula mass with no unit. All quantities refer to the named dissolved solute and final solution volume, not initial solvent volume or total solution mass. Supplied GCSE molar masses govern each question. A homogeneous sample retains concentration; dilution retains dissolved solute amount if none reacts, escapes or precipitates. NaCl concentration counts the amount of dissolved NaCl formula units, not intact NaCl molecules; the illustrative 3D inventory depicts separate Na+ and Cl− ions, omits water and hydration, and is not one mole or a particle trajectory. Complete-reacting-volume calculations, balanced-equation ratios and the titration practical need their later individual lesson; completing this lesson does not cover all 4.3.4. Written explanations are self-reviewed, never automatically correct.",
  outcomes: [
    "Convert cm³ to dm³ before using mol/dm³.",
    "Find c, n or required volume from the other two quantities.",
    "Connect solute mass and amount using its supplied molar mass.",
    "Convert g/dm³ and mol/dm³ without confusing their numerators.",
    "Explain sampling and dilution using the quantity retained.",
  ],
  warmup: [
    n(
      "w-volume",
      "Recall cubic units",
      "Convert 400 cm³ to dm³.",
      0.4,
      "dm³",
      "400/1000=0.400 dm³.",
      "One dm³ contains 1000 cm³.",
    ),
    n(
      "w-moles",
      "Recall mass to amount",
      "NaCl has molar mass 58.5 g/mol. Find the amount in 11.7 g.",
      0.2,
      "mol",
      "11.7/58.5=0.2 mol.",
      "Divide solute mass by its molar mass.",
    ),
  ],
  refresher: [
    c(
      "r-volume",
      "Choose the denominator",
      "A solute is dissolved in water and the final solution is 250 cm³. Which volume belongs in c=n/V?",
      "0.250 dm³ of final solution",
      {
        "250 dm³": "Convert cubic centimetres by dividing by 1000.",
        "The starting water volume":
          "Dissolving changes the final solution volume; use the supplied final value.",
      },
      "Concentration refers to final solution, not starting solvent.",
      "Name the solution and convert its unit.",
    ),
    n(
      "r-c",
      "Find amount per dm³",
      "0.12 mol is dissolved in 600 cm³ final solution. Find mol/dm³.",
      0.2,
      "mol/dm³",
      "V=0.600 dm³;c=0.12/0.600=0.20.",
      "Divide amount by converted final volume.",
    ),
    n(
      "r-n",
      "Find a sample amount",
      "100 cm³ solution has concentration 0.30 mol/dm³. Find solute moles.",
      0.03,
      "mol",
      "n=0.30×0.100=0.030 mol.",
      "Concentration is an amount per volume, not the sample amount.",
    ),
    n(
      "r-mass",
      "Use the named molar mass",
      "0.10 mol dissolved NaOH has molar mass 40 g/mol. Find solute grams.",
      4,
      "g",
      "m=0.10×40=4.0 g.",
      "Multiply amount by molar mass.",
    ),
    c(
      "r-ions",
      "Describe dissolved salt",
      "How should a dilute aqueous NaCl inventory be represented?",
      "Separate Na+ and Cl− ions",
      {
        "NaCl molecules bonded in pairs":
          "NaCl is ionic; its dissolved ions are not discrete NaCl molecules.",
        "Only neutral sodium atoms":
          "Both kinds of charged ion remain in solution.",
      },
      "The solute formula specifies equal Na+ and Cl− amounts; water and hydration may be omitted in a labelled schematic.",
      "Recall ionic substance identity.",
    ),
  ],
  guided: [
    p(
      "g-c",
      "Amount per solution volume",
      "Initial record: 0.05 mol in 250 cm³ final solution. Convert volume and calculate concentration.",
      [
        { id: "volume", label: "Solution volume / dm³", answer: 0.25 },
        { id: "c", label: "Concentration / mol/dm³", answer: 0.2 },
      ],
      "250 cm³=0.250 dm³;c=0.05/0.250=0.20 mol/dm³.",
      "Convert first, then divide n by V.",
      model(
        "concentration",
        "Predict concentration before comparing the changed amount or volume.",
      ),
    ),
    p(
      "g-n",
      "Find the dissolved amount",
      "Initial record: 75 cm³ of 0.40 mol/dm³ solution. Find volume in dm³ and dissolved moles.",
      [
        { id: "volume", label: "Solution volume / dm³", answer: 0.075 },
        { id: "n", label: "Dissolved amount / mol", answer: 0.03 },
      ],
      "75 cm³=0.075 dm³;n=0.40×0.075=0.030 mol.",
      "Multiply concentration by converted volume.",
      model(
        "amount",
        "Compare a larger sample with a stronger solution; predict the amount.",
      ),
    ),
    p(
      "g-mass",
      "Connect amount to solute mass",
      "Initial record: 250 cm³ of 0.20 mol/dm³ NaCl, molar mass 58.5 g/mol. Find NaCl amount and mass.",
      [
        { id: "n", label: "NaCl amount / mol", answer: 0.05 },
        { id: "mass", label: "NaCl mass / g", answer: 2.925 },
      ],
      "n=0.20×0.250=0.050 mol;m=0.050×58.5=2.925 g. These are solute quantities, not whole-solution mass.",
      "Find moles before multiplying by molar mass.",
      model(
        "mass",
        "Keep amount and mass separate when you change solute or sample volume.",
      ),
    ),
    n(
      "g-units",
      "Convert the numerator",
      "Initial record: 11.7 g/dm³ NaCl; molar mass 58.5 g/mol. Find mol/dm³.",
      0.2,
      "mol/dm³",
      "Each dm³ contains 11.7 g, or 11.7/58.5=0.20 mol. The denominator volume stays one dm³.",
      "Convert grams to moles using the named solute.",
      model(
        "units",
        "Predict how equal g/dm³ can correspond to different mol/dm³ for different solutes.",
      ),
    ),
    p(
      "g-sampling",
      "Sample, then dilute",
      "Initial record: take 125 cm³ from 500 cm³ of 0.40 mol/dm³ NaCl. Dilute only that sample to 250 cm³. Find its retained moles and final concentration.",
      [
        { id: "n", label: "Sample amount / mol", answer: 0.05 },
        { id: "c", label: "Final concentration / mol/dm³", answer: 0.2 },
      ],
      "Sampling:n=0.40×0.125=0.050 mol and sample c remains 0.40. Dilution retains 0.050 mol;final c=0.050/0.250=0.20.",
      "Sampling and adding solvent retain different quantities.",
      model(
        "sampling",
        "Predict sample concentration and diluted concentration separately; inspect conserved dissolved ions.",
      ),
    ),
  ],
  practice: [
    n(
      "p-c1",
      "Concentration with cubic conversion",
      "0.15 mol solute occupies 300 cm³ final solution. Find concentration.",
      0.5,
      "mol/dm³",
      "0.15/0.300=0.50.",
      "Divide by final dm³.",
    ),
    n(
      "p-c2",
      "A larger final volume",
      "0.08 mol solute occupies 800 cm³ solution. Find concentration.",
      0.1,
      "mol/dm³",
      "0.08/0.800=0.10.",
      "Concentration can be less than the numerical amount.",
    ),
    c(
      "p-conversion",
      "Diagnose a missing conversion",
      "A student divides 0.15 mol by 300 cm³ and reports 0.0005 mol/dm³. What must be corrected?",
      "Use 0.300 dm³ before dividing",
      {
        "Multiply amount by 300": "c=n/V, not nV.",
        "The answer needs no correction":
          "0.0005 is in mol/cm³; multiplying by 1000 gives 0.50 mol/dm³.",
      },
      "The denominator unit controls the reported concentration.",
      "Track units through the division.",
    ),
    n(
      "p-n1",
      "A small homogeneous sample",
      "Find solute moles in 20 cm³ at 0.75 mol/dm³.",
      0.015,
      "mol",
      "0.75×0.020=0.015.",
      "Convert the small sample volume.",
    ),
    n(
      "p-n2",
      "Amount in dm³",
      "Find solute moles in 1.2 dm³ at 0.25 mol/dm³.",
      0.3,
      "mol",
      "0.25×1.2=0.30.",
      "The volume is already in the required unit.",
    ),
    n(
      "p-volume",
      "Find required solution volume",
      "A 0.60 mol/dm³ solution must supply 0.09 mol. Find required volume in cm³.",
      150,
      "cm³",
      "V=0.09/0.60=0.15 dm³=150 cm³.",
      "Divide amount by concentration, then convert back.",
    ),
    n(
      "p-volume2",
      "Required volume in dm³",
      "What volume of 0.24 mol/dm³ solution contains 0.036 mol?",
      0.15,
      "dm³",
      "0.036/0.24=0.15 dm³.",
      "Rearrange to V=n/c.",
    ),
    n(
      "p-mass1",
      "Mass from molar concentration",
      "100 cm³ of 0.30 mol/dm³ NaOH, M = 40 g/mol. Find dissolved mass.",
      1.2,
      "g",
      "n=0.30×0.100=0.030;m=0.030×40=1.2 g.",
      "Two links: cV, then nM.",
    ),
    n(
      "p-mass2",
      "Another solute",
      "200 cm³ of 0.15 mol/dm³ KCl, M=74.5 g/mol. Find dissolved mass.",
      2.235,
      "g",
      "0.15×0.200×74.5=2.235.",
      "Use KCl's supplied molar mass.",
    ),
    n(
      "p-mass-to-c",
      "Start with solute grams",
      "5.85 g NaCl, M = 58.5 g/mol, is present in 500 cm³ final solution. Find concentration.",
      0.2,
      "mol/dm³",
      "n=5.85/58.5=0.10 mol;c=0.10/0.500=0.20.",
      "Do not divide grams by volume and label the result mol/dm³.",
    ),
    n(
      "p-mass-to-c2",
      "Mass, moles, final volume",
      "4 g NaOH, M = 40 g/mol, is present in 250 cm³ final solution. Find concentration.",
      0.4,
      "mol/dm³",
      "4/40=0.10 mol;0.10/0.250=0.40.",
      "Use dissolved solute mass and final solution volume.",
    ),
    n(
      "p-g-to-mol",
      "Convert mass concentration",
      "NaOH is 8 g/dm³, M = 40 g/mol. Find mol/dm³.",
      0.2,
      "mol/dm³",
      "8/40=0.20.",
      "Convert the amount of solute in one dm³.",
    ),
    n(
      "p-mol-to-g",
      "Convert molar concentration",
      "KCl is 0.40 mol/dm³, M=74.5 g/mol. Find g/dm³.",
      29.8,
      "g/dm³",
      "0.40×74.5=29.8.",
      "Multiply molar concentration by molar mass.",
    ),
    c(
      "p-same-moles",
      "Compare equal concentrations",
      "Equal volumes of 0.20 mol/dm³ NaCl and NaOH are compared. M values 58.5 and 40 g/mol. What follows?",
      "Equal solute moles; NaCl has greater solute mass",
      {
        "Equal solute mass": "Mass also depends on molar mass.",
        "NaOH has more solute moles": "Equal c and V give equal n.",
      },
      "n=cV is equal, but m=nM is greater for NaCl.",
      "Compare amount before mass.",
    ),
    n(
      "p-portion",
      "Homogeneous sampling",
      "Take 50 cm³ from 400 cm³ of 0.60 mol/dm³ solution. Find moles in the sample.",
      0.03,
      "mol",
      "0.60×0.050=0.030 mol.",
      "Use sample volume, not original total volume.",
    ),
    c(
      "p-portion-c",
      "Sampling preserves concentration",
      "Taking one quarter of a homogeneous solution leaves what concentration in the sample?",
      "The original concentration",
      {
        "One quarter of the original":
          "Both moles and volume fall by the same factor.",
        "Four times the original":
          "Removing a homogeneous portion does not concentrate it.",
      },
      "n and V decrease proportionally, so n/V stays constant.",
      "Consider both numerator and denominator.",
    ),
    n(
      "p-dilution",
      "Dilution retains amount",
      "50 cm³ of 0.60 mol/dm³ solution is diluted to 200 cm³. Find final concentration.",
      0.15,
      "mol/dm³",
      "n=0.60×0.050=0.030 mol;final c=0.030/0.200=0.15.",
      "Final volume is 200, not 250 cm³.",
    ),
    n(
      "p-added",
      "Final versus added volume",
      "100 cm³ of 0.50 mol/dm³ solution receives water until its final volume is 250 cm³. Find final concentration.",
      0.2,
      "mol/dm³",
      "Retained n=0.050 mol;final V=0.250 dm³;c=0.20.",
      "Use the stated final volume, not the water added.",
    ),
    {
      ...n(
        "p-round",
        "Final concentration",
        "6.23 g NaCl, M = 58.5 g/mol, in 375 cm³ final solution. Give mol/dm³ to 3 significant figures.",
        0.284,
        "mol/dm³",
        "6.23 ÷ 58.5 ÷ 0.375 = 0.2839886039…; to 3 significant figures, the concentration is 0.284 mol/dm³.",
        "Keep intermediate moles unrounded.",
      ),
      rounding: { kind: "significant-figures", digits: 3 },
    },
    w(
      "p-proof",
      "Explain the two operations",
      "Explain why a homogeneous sample keeps the original concentration but adding solvent to it lowers concentration when no solute is lost.",
      "Sampling reduces dissolved moles and final solution volume in the same proportion, preserving their ratio. Adding solvent increases final solution volume while dissolved solute moles remain fixed, so c=n/V decreases.",
      [
        "Sampling changes both n and V proportionally.",
        "Dilution retains n while V increases.",
        "Link the concentration change to n/V.",
      ],
    ),
    w(
      "p-ions",
      "Explain the representation",
      "A dilution asset shows four Na+ and four Cl− ions before and after. Explain why it does not depict four NaCl molecules or 0.40 mol as four particles.",
      "NaCl is ionic and dissolves as separate Na+ and Cl− ions. The asset is a small illustrative inventory of equal ion amounts; actual molar quantities contain Avogadro-scale numbers. Water, hydration and actual trajectories are omitted. NaCl solute concentration is not the sum of both ion concentrations.",
      [
        "Identify separate ions rather than molecules.",
        "Explain illustrative count versus molar amount.",
        "Identify an omitted feature or distinguish solute from total-ion concentration.",
      ],
    ),
  ],
  checkForms: [
    [
      p(
        "ca-c",
        "Independent concentration",
        "0.063 mol solute is present in 180 cm³ final solution. Find volume in dm³ and concentration.",
        [
          { id: "v", label: "Final volume / dm³", answer: 0.18 },
          { id: "c", label: "Concentration / mol/dm³", answer: 0.35 },
        ],
        "V=0.180 dm³;c=0.063/0.180=0.350.",
        "Convert final volume before dividing.",
      ),
      n(
        "ca-mass",
        "Independent mass",
        "80 cm³ of 0.25 mol/dm³ KBr; M=119 g/mol. Find solute grams.",
        2.38,
        "g",
        "0.25×0.080×119=2.38.",
        "Find n, then m.",
      ),
      n(
        "ca-units",
        "Independent numerator conversion",
        "MgCl2 concentration 19 g/dm³; M=95 g/mol. Find mol/dm³.",
        0.2,
        "mol/dm³",
        "19/95=0.20.",
        "Convert grams in each dm³ to solute moles.",
      ),
      n(
        "ca-volume",
        "Independent required volume",
        "What volume in cm³ of 0.80 mol/dm³ solution contains 0.028 mol?",
        35,
        "cm³",
        "0.028/0.80=0.035 dm³=35 cm³.",
        "Find dm³, then cm³.",
      ),
      w(
        "ca-proof",
        "Independent dilution explanation",
        "A homogeneous 120 cm³ sample at 0.50 mol/dm³ is diluted to 300 cm³. Explain the retained amount, final concentration and why this is not just removing a sample.",
        "Initial sample n=0.50×0.120=0.060 mol. Dilution retains 0.060 mol while final V=0.300 dm³, giving c=0.20 mol/dm³. Taking a homogeneous portion would reduce n and V together and preserve 0.50 mol/dm³.",
        [
          "Show 0.060 mol retained.",
          "Use final 0.300 dm³ to obtain 0.20 mol/dm³.",
          "Explain how homogeneous sampling differs.",
        ],
      ),
    ],
    [
      p(
        "cb-c",
        "Independent changed concentration",
        "0.081 mol solute is present in 270 cm³ final solution. Find volume in dm³ and concentration.",
        [
          { id: "v", label: "Final volume / dm³", answer: 0.27 },
          { id: "c", label: "Concentration / mol/dm³", answer: 0.3 },
        ],
        "V=0.270;c=0.081/0.270=0.300.",
        "Use converted final volume.",
      ),
      n(
        "cb-mass",
        "Independent changed solute",
        "60 cm³ of 0.40 mol/dm³ MgCl2; M=95 g/mol. Find solute mass.",
        2.28,
        "g",
        "0.40×0.060×95=2.28.",
        "Use MgCl2's molar mass.",
      ),
      n(
        "cb-units",
        "Independent changed units",
        "KBr solution is 0.15 mol/dm³; M=119 g/mol. Find g/dm³.",
        17.85,
        "g/dm³",
        "0.15×119=17.85.",
        "This conversion goes from moles to grams.",
      ),
      n(
        "cb-volume",
        "Independent changed volume",
        "What volume in cm³ of 0.45 mol/dm³ solution contains 0.018 mol?",
        40,
        "cm³",
        "0.018/0.45=0.040 dm³=40 cm³.",
        "Rearrange before substituting.",
      ),
      w(
        "cb-proof",
        "Independent mass comparison",
        "Equal 50 cm³ volumes of 0.30 mol/dm³ NaOH and NaCl have molar masses 40 and 58.5 g/mol. Explain their amounts and why their dissolved masses differ.",
        "Each contains 0.30×0.050=0.015 mol of its named solute. NaOH mass=0.015×40=0.600 g;NaCl mass=0.015×58.5=0.8775 g. Equal c and V ensure equal amount, not equal mass; mass depends on molar mass.",
        [
          "Show both solute amounts are 0.015 mol.",
          "Find 0.600 g and 0.8775 g using the correct M.",
          "Explain that equal amount is not equal mass.",
        ],
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "ra-c",
        "Retrieve concentration",
        "0.042 mol solute is in 140 cm³ solution. Find mol/dm³.",
        0.3,
        "mol/dm³",
        "0.042/0.140=0.30.",
        "Convert then divide.",
      ),
      n(
        "ra-mass",
        "Retrieve mass link",
        "90 cm³ of 0.20 mol/dm³ NaOH, M = 40 g/mol. Find solute mass.",
        0.72,
        "g",
        "0.20×0.090×40=0.72.",
        "Use n=cV, then m=nM.",
      ),
      n(
        "ra-units",
        "Retrieve numerator conversion",
        "NaCl solution is 17.55 g/dm³, M = 58.5 g/mol. Find mol/dm³.",
        0.3,
        "mol/dm³",
        "17.55/58.5=0.30.",
        "Convert grams to moles.",
      ),
    ],
    [
      n(
        "rb-c",
        "Retrieve changed concentration",
        "0.096 mol solute is in 160 cm³ solution. Find mol/dm³.",
        0.6,
        "mol/dm³",
        "0.096/0.160=0.60.",
        "Use final volume in dm³.",
      ),
      n(
        "rb-mass",
        "Retrieve changed solute",
        "120 cm³ of 0.25 mol/dm³ KCl, M=74.5 g/mol. Find solute mass.",
        2.235,
        "g",
        "0.25×0.120×74.5=2.235.",
        "Find amount before mass.",
      ),
      n(
        "rb-units",
        "Retrieve mass concentration",
        "NaOH solution is 0.35 mol/dm³, M = 40 g/mol. Find g/dm³.",
        14,
        "g/dm³",
        "0.35×40=14.",
        "Convert moles in one dm³ to grams.",
      ),
    ],
  ],
};
molarConcentrationJourney.guided[0].openingHint = true;
molarConcentrationJourney.practice.find(
  (q) => q.id === "mc-v1-p-conversion",
)!.followUp = "mc-v1-r-volume";
molarConcentrationJourney.practice.find(
  (q) => q.id === "mc-v1-p-mass-to-c",
)!.followUp = "mc-v1-r-mass";
molarConcentrationJourney.practice.find(
  (q) => q.id === "mc-v1-p-portion-c",
)!.followUp = "mc-v1-r-n";

molarConcentrationJourney.practice.find(
  (q) => q.id === "mc-v1-p-conversion",
)!.optionAliases = {
  "Use0.300 dm³ before dividing": "Use 0.300 dm³ before dividing",
};
