import type { LearningTask, LessonJourney, TaskModel } from "../types";
import { choice, number } from "./helpers";
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...choice(
    `mo-v1-${id}`,
    prompt,
    answer,
    errors,
    explanation,
    hint,
    title,
    model,
  ),
  title,
});
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...number(`mo-v1-${id}`, prompt, answer, unit, explanation, hint, title),
  ...(Math.abs(answer) > 1e10 ? { tolerance: Math.abs(answer) * 1e-12 } : {}),
  title,
});
const guided = [
  c(
    "g-mass",
    "Find amount in mol",
    "9000 mg water: find amount in mol. Use Aᵣ H=1, O=16.",
    "0.5 mol",
    {
      "500 mol": "9000 is milligrams, not grams.",
      "162 mol": "Amount divides mass by molar mass; it does not multiply.",
    },
    "9000 mg=9 g. M(H₂O)=18 g/mol;9÷18=.5 mol.",
    "Convert to grams and construct molar mass.",
    {
      kind: "mole-amounts",
      mode: "mass",
      instruction: "Predict grams, molar mass and amount.",
    },
  ),
  c(
    "g-reverse",
    "Find mass from amount",
    "Find the mass of 0.25 mol CO₂. Use Aᵣ C=12, O=16.",
    "11 g",
    {
      "176 g": "Mass multiplies amount by molar mass.",
      "44 g": "44 g is the mass of one mole, not one quarter mole.",
    },
    "M(CO₂)=12+2×16=44 g/mol; .25×44=11 g.",
    "Multiply mol by grams per mol.",
    {
      kind: "mole-amounts",
      mode: "reverse",
      instruction: "Predict molar mass and sample mass.",
    },
  ),
  c(
    "g-entities",
    "Name the counted entities",
    "0.5 mol O₂: choose its molecule count and total O-atom amount. Use Nₐ=6.02×10²³ mol⁻¹.",
    "3.01×10²³ molecules; 1 mol O atoms",
    {
      "6.02×10²³ molecules; 1 mol O atoms":
        "That molecule count belongs to one mole of O₂.",
      "3.01×10²³ molecules; 0.5 mol O atoms":
        "Each O₂ molecule has two O atoms.",
    },
    ".5×Nₐ=3.01×10²³ molecules; two atoms per molecule gives 1 mol O atoms.",
    "Count complete entities before their constituents.",
    {
      kind: "mole-amounts",
      mode: "entities",
      instruction:
        "Name complete entities and construct their count in standard form; then predict total constituent mol.",
    },
  ),
  c(
    "g-inverse",
    "Reverse a particle count",
    "3.01×10²³ H₂O molecules: find amount and mass. Use Nₐ=6.02×10²³ mol⁻¹ and M=18 g/mol.",
    "0.5 mol; 9 g",
    {
      "3.01 mol; 54.18 g": "The coefficient alone is not the amount in mol.",
      "1.5 mol; 27 g": "The count is molecules, not total atoms.",
    },
    "N/Nₐ=.5 mol; .5×18=9 g. There are three atoms per molecule, but the supplied count already specifies molecules.",
    "Divide the entire count by Nₐ before multiplying by M.",
    {
      kind: "mole-amounts",
      mode: "inverse",
      instruction: "Use the stated entity count to predict mol and grams.",
    },
  ),
];
guided[0].openingHint = true;
export const molesJourney: LessonJourney = {
  version: 1,
  introduction:
    "Link measured mass, amount in mol and explicitly named entities without confusing molecules, atoms or ionic formula units.",
  scopeNote:
    "Higher mass/amount/particle-number scope: AQA4.3.2.1 and Trilogy equivalent, with Pearson1.50–1.51 context. All stated masses use supplied rounded Aᵣ values and calculations use Nₐ=6.02×10²³ mol⁻¹. This is the GCSE-rounded value; the exact SI constant is 6.02214076×10²³ mol⁻¹. The original broad route's six IDs remain retained; reaction ratios, reacting masses, balancing from masses and gas-volume rules receive separate individual lessons. Diagrams show representative formula composition, not a mole-sized population.",
  outcomes: [
    "Construct molar mass in g/mol and convert mass units before n=m/M.",
    "Calculate mass using m=nM.",
    "Use N=nNₐ and its inverse for the named entities.",
    "Apply formula subscripts to constituent atom/ion amounts and write normalized standard form.",
  ],
  warmup: [
    n(
      "w-mr",
      "Recall formula mass",
      "Find Mᵣ of H₂O using Aᵣ H=1 and O=16.",
      18,
      "",
      "2×1+16=18; relative formula mass has no unit.",
      "Count both H atoms.",
    ),
    n(
      "w-grams",
      "Recall mass conversion",
      "Convert 9000 mg to grams.",
      9,
      "g",
      "9000÷1000=9 g.",
      "1000 mg=1 g.",
    ),
  ],
  refresher: [
    c(
      "r-equation",
      "Choose amount from mass",
      "With mass in g and molar mass in g/mol, which expression gives amount in mol?",
      "Mass ÷ molar mass",
      {
        "Mass × molar mass": "That does not cancel grams correctly.",
        "Molar mass ÷ mass": "That is the reciprocal amount.",
      },
      "g÷(g/mol)=mol.",
      "Use unit cancellation.",
    ),
    c(
      "r-unit",
      "Separate relative and molar mass",
      "Water has Mᵣ18. Which gives its molar mass under the supplied GCSE values?",
      "18 g/mol",
      {
        "18 g": "That is a specified sample mass, not grams per mole.",
        "18 mol": "Mol describes amount, not molar mass.",
      },
      "Relative formula mass is dimensionless; molar mass has units g/mol.",
      "Name the quantity as well as its value.",
    ),
    c(
      "r-entity",
      "Identify ionic accounting",
      "Which named entities does one mole of NaCl formula units count?",
      "NaCl formula units; not NaCl molecules",
      {
        "Discrete NaCl molecules": "Ionic NaCl is a lattice of ions.",
        "Only chlorine molecules": "Cl⁻ ions differ from Cl₂ molecules.",
      },
      "The formula-unit ratio contains one Na⁺ and one Cl⁻; it does not identify a discrete NaCl molecule.",
      "Recall the ionic lattice.",
    ),
    c(
      "r-equal",
      "Compare equal amounts",
      "One mole C atoms and one mole CO₂ molecules have what in common?",
      "The number of specified entities",
      {
        "The same mass in grams": "Their molar masses are12 and 44 g/mol.",
        "The same total atom count": "Each CO₂ molecule contains three atoms.",
      },
      "Each has Nₐ specified entities, but masses and constituent atom totals differ.",
      "Say what each mole counts.",
    ),
    c(
      "r-standard",
      "Recognise normalized form",
      "Which is normalized standard form for 1.204×10²⁴?",
      "1.204×10²⁴",
      {
        "12.04×10²³":
          "Same numerical value, but the coefficient is at least10.",
        "1.204×10²³": "That is ten times smaller.",
      },
      "Use a coefficient at least1 and below10; changing its size requires the matching exponent change.",
      "Preserve value while normalizing.",
    ),
  ],
  guided,
  practice: [
    n(
      "p-magnesium",
      "Use a different molar mass",
      "Find amount in 6 g Mg. M=24 g/mol.",
      0.25,
      "mol",
      "6÷24=.25 mol.",
      "Divide grams by g/mol.",
    ),
    n(
      "p-water",
      "Use one-mole mass",
      "Find amount in 18 g water. M=18 g/mol.",
      1,
      "mol",
      "18÷18=1 mol.",
      "Use n=m/M.",
    ),
    n(
      "p-oxygen",
      "Use the molecular formula",
      "Find amount in 16 g O₂. Use Aᵣ O=16.",
      0.5,
      "mol",
      "M(O₂)=32 g/mol;16÷32=.5 mol O₂.",
      "Use O₂, not O, for this sample.",
    ),
    n(
      "p-salt",
      "Count ionic formula amounts",
      "Find amount in 58.5 g NaCl. M=58.5 g/mol.",
      1,
      "mol",
      "58.5÷58.5=1 mol NaCl formula units.",
      "Mol can count formula units.",
    ),
    n(
      "p-kg",
      "Convert kilograms before dividing",
      "Find amount in 0.044 kg CO₂. M=44 g/mol.",
      1,
      "mol",
      ".044 kg=44 g;44÷44=1 mol.",
      "Match the mass unit to g/mol.",
    ),
    n(
      "p-mg",
      "Transfer a small mass",
      "Find amount in 450 mg water. M=18 g/mol.",
      0.025,
      "mol",
      "450 mg=.45 g;.45÷18=.025 mol.",
      "Convert mg to g.",
    ),
    n(
      "p-mass",
      "Scale a pure compound mass",
      "Find mass of 0.15 mol CaCO₃. M=100 g/mol.",
      15,
      "g",
      ".15×100=15 g.",
      "Multiply amount by molar mass.",
    ),
    n(
      "p-salt-mass",
      "Use a fractional ionic amount",
      "Find mass of 0.04 mol NaCl formula units. M=58.5 g/mol.",
      2.34,
      "g",
      ".04×58.5=2.34 g.",
      "Use the mass per mol of formula units.",
    ),
    {
      ...c(
        "p-working",
        "Construct bracketed molar mass",
        "7.4 g Ca(OH)₂: enter molar mass in g/mol and amount in mol. Use Aᵣ Ca=40,O=16,H=1.",
        JSON.stringify({ molarMass: "74", amount: "0.1" }),
        {},
        "M=40+2×(16+1)=74 g/mol;7.4÷74=.1 mol.",
        "Multiply both O and H inside the brackets.",
      ),
      options: undefined,
      partLegend: "Construct molar mass and amount",
      parts: [
        { id: "molarMass", label: "Molar mass / g/mol", answer: 74 },
        { id: "amount", label: "Amount / mol", answer: 0.1 },
      ],
    },
    {
      ...c(
        "p-molecules",
        "Construct an entity count",
        "0.25 mol CO₂ molecules: enter the coefficient and exponent of their normalized standard-form count, then the amount of O atoms in mol. Use Nₐ=6.02×10²³ mol⁻¹.",
        JSON.stringify({ coefficient: "1.505", power: "23", oxygen: "0.5" }),
        {},
        "Molecules=.25×6.02×10²³=1.505×10²³. Each contains two O atoms, so O-atom amount=.5 mol.",
        "The requested constituent is oxygen only.",
      ),
      options: undefined,
      partLegend: "Name molecule count and oxygen-atom amount",
      parts: [
        { id: "coefficient", label: "Count coefficient", answer: 1.505 },
        { id: "power", label: "Power of 10", answer: 23 },
        { id: "oxygen", label: "O atoms / mol", answer: 0.5 },
      ],
    },
    n(
      "p-total-atoms",
      "Count all atoms in molecules",
      "Find total number of atoms in 0.5 mol H₂O molecules. Use Nₐ=6.02×10²³ mol⁻¹. Enter standard form using e notation, such as 6.02e23.",
      9.03e23,
      "atoms",
      ".5 mol molecules contains 1.5 mol total atoms:1.5×6.02×10²³=9.03×10²³.",
      "There are three atoms per H₂O molecule.",
    ),
    n(
      "p-chloride",
      "Count one constituent ion type",
      "Find number of Cl⁻ ions in 1 mol NaCl formula units. Use Nₐ=6.02×10²³ mol⁻¹ and enter e notation.",
      6.02e23,
      "Cl⁻ ions",
      "One Cl⁻ per formula-unit ratio gives 1 mol Cl⁻, or6.02×10²³ ions.",
      "Do not count Na⁺ as Cl⁻.",
    ),
    {
      ...c(
        "p-total-ions",
        "Normalize a combined ion count",
        "1 mol NaCl formula units contains 2 mol total constituent ions. Use Nₐ=6.02×10²³ mol⁻¹. Enter coefficient and power for the total-ion count in normalized standard form.",
        JSON.stringify({ coefficient: "1.204", power: "24" }),
        {},
        "2×6.02×10²³=12.04×10²³=1.204×10²⁴ ions.",
        "A coefficient above10 needs normalization.",
      ),
      options: undefined,
      partLegend: "Write total-ion count in standard form",
      parts: [
        { id: "coefficient", label: "Count coefficient", answer: 1.204 },
        { id: "power", label: "Power of 10", answer: 24 },
      ],
    },
    n(
      "p-carbon-count",
      "Reverse a stated atom count",
      "Find amount represented by 9.03×10²² C atoms. Use Nₐ=6.02×10²³ mol⁻¹.",
      0.15,
      "mol",
      "9.03×10²²/(6.02×10²³)=.15 mol C atoms.",
      "Divide the complete number, including its exponent.",
    ),
    n(
      "p-count-mass",
      "Go from count to mass",
      "Find mass of 1.204×10²⁴ water molecules. Use Nₐ=6.02×10²³ mol⁻¹ and M=18 g/mol.",
      36,
      "g",
      "N/Nₐ=2 mol;2×18=36 g.",
      "Find mol before grams.",
    ),
    n(
      "p-cage-amount",
      "Distinguish atoms from C₇₀ molecules",
      "If2 mol C atoms form only C₇₀ molecules, what amount of C₇₀ molecules forms? Enter a fraction or decimal.",
      1 / 35,
      "mol",
      "Each molecule requires70 C atoms:2/70=1/35 mol C₇₀ molecules.",
      "Divide the atom amount by atoms per molecule.",
    ),
    {
      ...c(
        "p-cage-count",
        "Construct a large-molecule count",
        "If2 mol C atoms form only C₇₀ molecules, find their molecule count in normalized standard form. Use Nₐ=6.02×10²³ mol⁻¹. Enter coefficient and power.",
        JSON.stringify({ coefficient: "1.72", power: "22" }),
        {},
        "(2/70)×6.02×10²³=1.72×10²² C₇₀ molecules.",
        "Divide by 70 before counting molecules.",
      ),
      options: undefined,
      partLegend: "Count molecules rather than constituent atoms",
      parts: [
        { id: "coefficient", label: "Count coefficient", answer: 1.72 },
        { id: "power", label: "Power of 10", answer: 22 },
      ],
    },
    c(
      "p-compare",
      "Compare equal gram samples",
      "16 g O₂ and 16 g CO₂: which contains more molecules? Use M(O₂)=32 and M(CO₂)=44 g/mol.",
      "The O₂ sample",
      {
        "They contain equal molecule counts":
          "Equal mass does not mean equal amount for different molar masses.",
        "The CO₂ sample": "16/44 is less than16/32.",
      },
      "O₂ amount=.5 mol;CO₂ amount=16/44 mol. Molecule count follows mol, so O₂ has more.",
      "Compare mass divided by molar mass.",
    ),
    n(
      "p-electrons",
      "Count a specified electron amount",
      "0.15 mol Mg atoms each lose two electrons. What amount of electrons is transferred?",
      0.3,
      "mol electrons",
      "2×.15=.3 mol electrons.",
      "Mol can describe electrons; use electrons per atom.",
    ),
    c(
      "p-count-name",
      "Keep equal-mole comparisons precise",
      "1 mol CO₂ molecules and 1 mol C atoms each count Nₐ named entities. Do they therefore have equal total atom counts?",
      "No; CO₂ has three times as many total atoms",
      {
        "Yes; every mole always has the same total atoms":
          "The stated entities are molecules in one sample and atoms in the other.",
        "No; C has three times as many atoms":
          "Each CO₂ molecule contains three atoms.",
      },
      "CO₂ contains 3 mol total atoms; C contains 1 mol atoms.",
      "Inspect the constituent count within each named entity.",
    ),
    {
      ...c(
        "p-explain",
        "Explain quantity and units",
        "Explain why9 g H₂O is 0.5 mol and why18 g/mol is molar mass, while18 is the dimensionless relative formula mass. Use Aᵣ H=1,O=16.",
        "Mᵣ=2×1+16=18 without units. Under these GCSE values, M=18 g/mol. n=m/M=9 g/(18 g/mol)=.5 mol. Multiplying mass by M or inverting the quotient has the wrong units for amount.",
        {},
        "Compare the units, not just the shared numerical value.",
        "Construct formula mass, assign molar-mass units and cancel units.",
      ),
      options: undefined,
      rubric: [
        "Counts both H atoms and obtains dimensionless Mᵣ18.",
        "Identifies molar mass18 g/mol and divides9 g by it.",
        "Obtains.5 mol with correct quantity/unit reasoning.",
      ],
    },
    {
      ...c(
        "p-justify",
        "Explain the specified entity",
        "Explain why1 mol O₂ contains Nₐ molecules but2Nₐ O atoms, and why saying 'one mole contains Nₐ particles' needs the particle type stated.",
        "One mole O₂ molecules counts Nₐ complete molecules. Two O atoms per molecule gives 2 mol O atoms, or2Nₐ atoms. A mole of molecules and a mole of atoms describe different entities, so the particle type must be named.",
        {},
        "Name the counted entity before applying its formula.",
        "Use two atoms per molecule without relabelling molecules as atoms.",
      ),
      options: undefined,
      rubric: [
        "Counts Nₐ complete O₂ molecules.",
        "Uses two O atoms per molecule to obtain2Nₐ atoms.",
        "Explains why the stated entity matters.",
      ],
    },
  ],
  checkForms: [
    [
      n(
        "ca-amount",
        "Calculate a fresh mass amount",
        "Find amount in 8.8 g CO₂. M=44 g/mol.",
        0.2,
        "mol",
        "8.8÷44=.2.",
        "Divide mass by molar mass.",
      ),
      n(
        "ca-mass",
        "Calculate a new sample mass",
        "Find mass of 0.3 mol O₂. M=32 g/mol.",
        9.6,
        "g",
        ".3×32=9.6.",
        "Multiply amount by molar mass.",
      ),
      {
        ...c(
          "ca-count",
          "Construct a fresh entity number",
          "Find number of molecules in 0.4 mol H₂O, in normalized standard form. Nₐ=6.02×10²³ mol⁻¹. Enter coefficient and exponent.",
          JSON.stringify({ coefficient: "2.408", power: "23" }),
          {},
          ".4×6.02×10²³=2.408×10²³ molecules.",
          "The count is molecules, not atoms.",
        ),
        options: undefined,
        partLegend: "Construct the stated molecule count",
        parts: [
          { id: "coefficient", label: "Count coefficient", answer: 2.408 },
          { id: "power", label: "Power of 10", answer: 23 },
        ],
      },
      n(
        "ca-ions",
        "Count a fresh constituent amount",
        "0.35 mol NaCl formula units: what total amount of Na⁺ and Cl⁻ ions does it contain?",
        0.7,
        "mol ions",
        "Two ions per formula-unit ratio gives .7 mol ions.",
        "Include both constituent ion types.",
      ),
      c(
        "ca-unit",
        "Identify a quantity unit",
        "What is the unit of molar mass when masses are in grams?",
        "g/mol",
        {
          mol: "That is amount.",
          "No unit": "Relative formula mass, not molar mass, is dimensionless.",
        },
        "Molar mass measures grams per mole.",
        "Name mass per amount.",
      ),
    ],
    [
      n(
        "cb-amount",
        "Convert a new small sample",
        "Find amount in 216 mg H₂O. M=18 g/mol.",
        0.012,
        "mol",
        "216 mg=.216 g;.216÷18=.012.",
        "Convert to grams.",
      ),
      n(
        "cb-mass",
        "Use a new ionic amount",
        "Find mass of 0.12 mol NaCl. M=58.5 g/mol.",
        7.02,
        "g",
        ".12×58.5=7.02.",
        "Multiply mol by g/mol.",
      ),
      n(
        "cb-inverse",
        "Reverse a fresh molecular count",
        "Find amount represented by 1.806×10²³ CO₂ molecules. Nₐ=6.02×10²³ mol⁻¹.",
        0.3,
        "mol",
        "1.806/6.02=.3 with equal powers.",
        "Divide by Nₐ.",
      ),
      {
        ...c(
          "cb-atoms",
          "Construct formula constituent amounts",
          "0.6 mol H₂O molecules: enter amounts of H atoms and O atoms, both in mol.",
          JSON.stringify({ hydrogen: "1.2", oxygen: "0.6" }),
          {},
          "Two H and one O per molecule gives 1.2 mol H atoms and .6 mol O atoms.",
          "Apply each formula subscript separately.",
        ),
        options: undefined,
        partLegend: "Count each constituent atom type",
        parts: [
          { id: "hydrogen", label: "H atoms / mol", answer: 1.2 },
          { id: "oxygen", label: "O atoms / mol", answer: 0.6 },
        ],
      },
      c(
        "cb-equal",
        "Compare equal specified amounts",
        "One mole NaCl formula units and one mole CO₂ molecules have what equal?",
        "The number of stated formula units or molecules",
        {
          "Their masses": "58.5 and 44 g differ.",
          "Their total constituent counts":
            "Two ions versus three atoms per entity differ.",
        },
        "Each has Nₐ named entities.",
        "Keep the specified entity type.",
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "ra-amount",
        "Retrieve mass conversion",
        "Find amount in 3.6 g water. M=18 g/mol.",
        0.2,
        "mol",
        "3.6/18=.2.",
        "Use n=m/M.",
      ),
      n(
        "ra-mass",
        "Retrieve reverse conversion",
        "Find mass of 0.075 mol CO₂. M=44 g/mol.",
        3.3,
        "g",
        ".075×44=3.3.",
        "Use m=nM.",
      ),
      n(
        "ra-count",
        "Retrieve a named entity count",
        "Find number of NaCl formula units in 0.1 mol. Nₐ=6.02×10²³ mol⁻¹; enter e notation.",
        6.02e22,
        "formula units",
        ".1×Nₐ=6.02×10²² formula units, not NaCl molecules.",
        "Scale the count by amount.",
      ),
    ],
    [
      n(
        "rb-amount",
        "Retrieve a changed mass unit",
        "Find amount in 0.016 kg O₂. M=32 g/mol.",
        0.5,
        "mol",
        ".016 kg=16 g;16/32=.5.",
        "Convert kg to g.",
      ),
      n(
        "rb-inverse",
        "Retrieve count-to-mass working",
        "Find mass of 1.505×10²³ CO₂ molecules. Nₐ=6.02×10²³ mol⁻¹;M=44 g/mol.",
        11,
        "g",
        "N/Nₐ=.25 mol;.25×44=11 g.",
        "Find amount first.",
      ),
      n(
        "rb-constituents",
        "Retrieve an atom amount",
        "Find total atom amount in 0.8 mol CO₂ molecules.",
        2.4,
        "mol atoms",
        "Three atoms per molecule gives 2.4 mol atoms.",
        "Count C and both O atoms.",
      ),
    ],
  ],
};
molesJourney.practice.find((q) => q.id === "mo-v1-p-working")!.followUp =
  "mo-v1-r-unit";
molesJourney.practice.find((q) => q.id === "mo-v1-p-total-ions")!.followUp =
  "mo-v1-r-standard";

molesJourney.practice.find((q) => q.id === "mo-v1-p-cage-amount")!.tolerance =
  0.00003;
