import { c, n, w, draw } from "./pathways-tasks";
import type { PathwayTask as Task } from "./pathways-types";
export const practice: Task[] = [
  draw(
    "p-ethene-h",
    "Draw ethene hydrogenation",
    "Ethene reacts with H2. Construct the fully displayed product.",
    "initial",
    "Ethane: two singly bonded C atoms, three individually bonded H on each C.",
    [
      "Retain both original C and all four original H.",
      "C=C becomes C–C; add one H to each original reacting C.",
      "Show all six H separately; no OH, halogens, brackets or n.",
    ],
  ),
  draw(
    "p-ethene-water",
    "Draw ethene hydration",
    "Ethene reacts with steam. Construct the fully displayed ethanol molecule.",
    "etheneWater",
    "Ethanol: C–C–O–H, with three C–H at one C and two at the other. Equivalent reversed drawings are valid.",
    [
      "Retain both original C and all original H; use a single C–C.",
      "Add H and OH across the original pair; show the O–H bond.",
      "All six H and the one O belong to one complete molecule; no brackets or n.",
    ],
  ),
  draw(
    "p-ethene-cl",
    "Draw chlorine addition",
    "Ethene reacts with Cl2. Construct the fully displayed product.",
    "etheneCl",
    "One single C–C, two H and one Cl individually bonded to each C: C2H4Cl2.",
    [
      "Keep both original C and all four original H.",
      "Add one Cl to each original double-bond C; C=C becomes C–C.",
      "Show both separate Cl atoms and all C–H bonds; no lost H or polymer notation.",
    ],
  ),
  draw(
    "p-ethene-br",
    "Draw bromine addition",
    "Ethene reacts with Br2. Construct the fully displayed product.",
    "etheneBr",
    "One single C–C, two H and one Br individually bonded to each C: C2H4Br2.",
    [
      "Keep both C and all four original H.",
      "One Br adds to each reacting carbon; replace C=C with C–C.",
      "Show all bonds separately; do not put both Br on one C or replace H.",
    ],
  ),
  draw(
    "p-ethene-i",
    "Draw a supplied iodine addition",
    "For the supplied ethene + I2 addition, construct the fully displayed product. No rate or colour comparison is supplied.",
    "etheneI",
    "A single C–C; each C has two H and one I: C2H4I2.",
    [
      "Retain all original C and H.",
      "One I attaches to each original double-bond C; the C–C is single.",
      "Show both I atoms individually; no invented colour or rate claim.",
    ],
  ),
  draw(
    "p-propene-h",
    "Retain the propene methyl end",
    "Propene reacts with H2. Construct the fully displayed product, retaining the entire chain.",
    "propeneH",
    "Propane: three singly connected C with C–H counts 3, 2, 3.",
    [
      "Keep all three C, including the original methyl end.",
      "Add one H at each original double-bond C and change that bond to single.",
      "Show eight separate H; no oxygen, halogens or repeat notation.",
    ],
  ),
  draw(
    "p-propene-water",
    "Use a specified propanol connectivity",
    "Propene reacts with steam. For this drawing place OH on carbon 2, counting from the original terminal C=C end.",
    "propeneWater",
    "The supplied carbon-2 OH propanol structure has a three-carbon single-bond chain with C–H counts 3, 1, 3, plus one O–H.",
    [
      "Retain all three C and change only the original C=C to C–C.",
      "Put OH on C2 and the added H on C1; retain the original methyl end.",
      "Show the O–H hydrogen and all seven C–H separately; no product-proportion claim.",
    ],
  ),
  draw(
    "p-propene-cl",
    "Add Cl without substituting H",
    "Propene reacts with Cl2. Construct its fully displayed product.",
    "propeneCl",
    "Single three-carbon chain; original reacting C1 and C2 each gain Cl. C–H counts are 2, 1, 3: C3H6Cl2.",
    [
      "Retain the three-carbon chain and all original six H.",
      "Add one Cl to C1 and one to C2; change the original double bond to single.",
      "The terminal methyl carbon stays unmodified; show all H and Cl separately.",
    ],
  ),
  draw(
    "p-propene-br",
    "Keep the original attachments",
    "Propene reacts with Br2. Construct its fully displayed product.",
    "propeneBr",
    "Single three-carbon chain with Br on C1 and C2; C–H counts 2, 1, 3: C3H6Br2.",
    [
      "Keep all three C and six original H.",
      "Add Br across the original C=C rather than replacing a methyl H.",
      "Each original reacting carbon gains one Br; show every bond.",
    ],
  ),
  draw(
    "p-propene-i",
    "Place the iodine pair",
    "For the supplied propene + I2 addition, construct the fully displayed product.",
    "propeneI",
    "Single three-carbon chain with one I on each original double-bond carbon: C3H6I2.",
    [
      "Retain all original C and H.",
      "C1 and C2 each gain one I; their bond becomes single.",
      "C3 retains its original three H; no rate or colour is inferred.",
    ],
  ),
  draw(
    "p-butene-h",
    "Keep the four-carbon chain",
    "The supplied terminal-C=C butene reacts with H2. Construct the fully displayed product.",
    "buteneH",
    "Butane: a four-carbon single-bond chain with C–H counts 3, 2, 2, 3.",
    [
      "Keep every original chain C and H.",
      "Add H at C1 and C2; only the original double becomes single.",
      "Show ten separate H and no polymer continuation.",
    ],
  ),
  draw(
    "p-butene-water",
    "Show the supplied butanol",
    "The supplied terminal-C=C butene reacts with steam. Place OH on C2, counting from the original double-bond end.",
    "buteneWater",
    "Four-carbon single-bond chain; C–H counts 3, 1, 2, 3 and O–H on C2: C4H10O.",
    [
      "Keep all four original C and all original H.",
      "Add H at C1 and OH at C2; show O–H separately.",
      "Do not add OH at both sites or claim product proportions.",
    ],
  ),
  draw(
    "p-butene-cl",
    "Retain the unreacted chain bonds",
    "The supplied terminal-C=C butene reacts with Cl2. Construct its fully displayed product.",
    "buteneCl",
    "Four singly connected C; Cl at C1 and C2; C–H counts 2, 1, 2, 3: C4H8Cl2.",
    [
      "Keep the entire four-carbon chain.",
      "Change the original C1=C2 only; add one Cl to each of that pair.",
      "Keep all eight original H and all other C–C bonds.",
    ],
  ),
  draw(
    "p-butene-br",
    "Construct a longer bromine product",
    "The supplied terminal-C=C butene reacts with Br2. Construct its fully displayed product.",
    "buteneBr",
    "Four-carbon single-bond chain; one Br on C1 and one on C2; C4H8Br2.",
    [
      "Keep all four C and eight H.",
      "Use one Br on each original double-bond C, with C1–C2 single.",
      "Show every H and both Br bonds; no chain crop or repeat notation.",
    ],
  ),
  draw(
    "p-butene-i",
    "Do not spread iodine along the chain",
    "For the supplied terminal-C=C butene + I2 addition, construct the fully displayed product.",
    "buteneI",
    "Four-carbon single-bond chain with two I only at C1 and C2: C4H8I2.",
    [
      "Retain all original C and H.",
      "One I goes to each original reacting C; other chain carbons receive no I.",
      "The original double becomes single; no rate or colour conclusion is supplied.",
    ],
  ),
  draw(
    "p-pentene-h",
    "Complete the first-four alkene series",
    "The supplied terminal-C=C pentene reacts with H2. Construct the fully displayed product.",
    "penteneH",
    "Pentane: five singly connected C; C–H counts 3, 2, 2, 2, 3.",
    [
      "Retain all five C and all ten original H.",
      "Add one H at each original double-bond carbon; make C1–C2 single.",
      "Show twelve H individually; no extra C or polymer notation.",
    ],
  ),
  draw(
    "p-pentene-water",
    "Use a provided longer alcohol structure",
    "The supplied terminal-C=C pentene reacts with steam. Construct the provided pentanol connectivity with OH on C2; its name is supplied.",
    "penteneWater",
    "Five-carbon single-bond chain; C–H counts 3, 1, 2, 2, 3 and one O–H on C2: C5H12O.",
    [
      "Keep all five C and original ten H.",
      "Add H at C1 and OH at C2; show the O–H bond.",
      "Show all twelve H in total; no new alcohol-name recall or selectivity claim is required.",
    ],
  ),
  draw(
    "p-pentene-cl",
    "Preserve a longer skeleton",
    "The supplied terminal-C=C pentene reacts with Cl2. Construct its fully displayed product.",
    "penteneCl",
    "Five-carbon single-bond chain with Cl on C1 and C2: C5H10Cl2.",
    [
      "Retain all five C, ten H and unreacted C–C bonds.",
      "One Cl adds to each original double-bond carbon; C1=C2 becomes single.",
      "Show every H and both Cl separately; no atom substitution.",
    ],
  ),
  draw(
    "p-pentene-br",
    "Draw a complete molecule",
    "The supplied terminal-C=C pentene reacts with Br2. Construct its complete fully displayed product.",
    "penteneBr",
    "Five-carbon single-bond chain with Br at C1 and C2: C5H10Br2.",
    [
      "Keep all five C and ten original H.",
      "Add one Br to each original double-bond C and make their bond single.",
      "This is one complete molecule: no bracket, n or continuation bond.",
    ],
  ),
  draw(
    "p-pentene-i",
    "Account for exactly one iodine molecule",
    "For the supplied terminal-C=C pentene + I2 addition, construct the fully displayed product.",
    "penteneI",
    "Five-carbon single-bond chain with two I across the original C1=C2: C5H10I2.",
    [
      "Keep every original C and H.",
      "One I attaches to each original double-bond C, not to every chain carbon.",
      "C1–C2 becomes single; iodine rate and colour are outside the supplied evidence.",
    ],
  ),
  draw(
    "p-internal-h",
    "Recognise an internal reaction site",
    "The supplied butene has C=C between C2 and C3. It reacts with H2. Construct the fully displayed product.",
    "internalH",
    "Butane with a four-carbon single-bond chain and C–H counts 3, 2, 2, 3.",
    [
      "Keep both original terminal CH3 groups.",
      "Add H to C2 and C3, changing their original double to single.",
      "Show ten H separately and do not modify another chain bond.",
    ],
  ),
  draw(
    "p-internal-br",
    "Add at an internal double bond",
    "The supplied butene has C=C between C2 and C3. It reacts with Br2. Construct the fully displayed product.",
    "internalBr",
    "Four-carbon single-bond chain; one Br on C2 and one on C3; C–H counts 3, 1, 1, 3.",
    [
      "Keep all four C and eight H, including both terminal methyl groups.",
      "Add one Br at C2 and one at C3; change only their double to single.",
      "Show all original H and both Br; equivalent reversed structures are valid.",
    ],
  ),
];
practice.push(
  c(
    "p-h2-condition",
    "Identify hydrogenation",
    "An alkene is converted to its alkane by adding H2. Which catalyst should be stated?",
    "Nickel",
    {
      Yeast: "Yeast belongs to fermentation of glucose.",
      "Phosphoric acid for industrial steam addition":
        "That belongs to hydration rather than this H2 route.",
    },
    "H2 with nickel and suitable heating gives the saturated hydrocarbon.",
    "Identify the added molecule before the catalyst.",
  ),
  c(
    "p-steam-condition",
    "Give industrial hydration conditions",
    "Which statement completes an industrial ethene + steam reaction arrow?",
    "Heat and pressure with a phosphoric-acid catalyst",
    {
      "Ordinary cold water and yeast":
        "That is not this industrial addition route.",
      "Hydrogen and nickel": "That changes the reagent and product.",
    },
    "Steam is the reagent and phosphoric acid is the catalyst; the stated process uses heat and pressure.",
    "Separate reagent from catalyst.",
  ),
  c(
    "p-bromine-test",
    "Compare the test observation",
    "Two samples are tested with bromine water without UV. Sample A decolourises it; B leaves it orange. In the stated alkene/alkane comparison, which contains C=C?",
    "A",
    {
      B: "The supplied negative saturated comparison leaves bromine orange.",
      "Neither, because UV was absent":
        "Ordinary alkene addition does not require UV.",
    },
    "A consumes the bromine in this test; B is the negative comparison.",
    "Use the supplied observation.",
  ),
  c(
    "p-cl-pair",
    "Infer a chlorine reagent",
    "A four-carbon alkene forms a saturated molecule with unchanged C and H counts and two new Cl atoms. Which reagent supplies the gain?",
    "Cl2",
    {
      HCl: "One HCl supplies only one Cl and also adds H.",
      H2O: "Water supplies neither Cl atom.",
    },
    "One chlorine molecule supplies two Cl, one at each original reacting carbon.",
    "Count the gained elements.",
  ),
  c(
    "p-h2-infer",
    "Infer hydrogen from an internal site",
    "A supplied internal four-carbon alkene becomes an alkane with two extra H and unchanged C count. What supplies the atom difference?",
    "H2",
    {
      H2O: "That would also supply O.",
      Br2: "That would add Br rather than H.",
    },
    "One H2 supplies the two added H across the original internal C=C.",
    "Subtract original atoms from product atoms.",
  ),
  n(
    "p-ethanol-Mr",
    "Include all ethanol hydrogens",
    "Find Mr of C2H6O using Ar(C)=12, Ar(H)=1 and Ar(O)=16.",
    "46",
    "relative molecular mass",
    "24 + 6 + 16 = 46; the O–H hydrogen is included in H6.",
    "Sum all atomic contributions.",
  ),
  n(
    "p-br-Mr",
    "Count both heavy atoms",
    "Find Mr of C2H4Br2 using Ar(C)=12, Ar(H)=1 and Ar(Br)=80.",
    "188",
    "relative molecular mass",
    "24 + 4 + 160 = 188.",
    "Use two bromine atoms.",
  ),
  n(
    "p-cl-Mr",
    "Use a fractional atomic mass",
    "Find Mr of C2H4Cl2 using Ar(C)=12, Ar(H)=1 and Ar(Cl)=35.5.",
    "99",
    "relative molecular mass",
    "24 + 4 + 71 = 99.",
    "Multiply the chlorine atomic mass by two.",
  ),
  n(
    "p-i-Mr",
    "Account for iodine",
    "Find Mr of C2H4I2 using Ar(C)=12, Ar(H)=1 and Ar(I)=127.",
    "282",
    "relative molecular mass",
    "24 + 4 + 254 = 282.",
    "The subscript applies to the iodine contribution.",
  ),
  n(
    "p-propane-Mr",
    "Count one hydrocarbon product",
    "Find Mr of C3H8 using Ar(C)=12 and Ar(H)=1.",
    "44",
    "relative molecular mass",
    "36 + 8 = 44.",
    "Use the complete molecular formula.",
  ),
  n(
    "p-pentanol-Mr",
    "Count a supplied longer alcohol",
    "The supplied alcohol product has formula C5H12O. Find Mr using Ar(C)=12, Ar(H)=1 and Ar(O)=16.",
    "88",
    "relative molecular mass",
    "60 + 12 + 16 = 88. Its name is supplied rather than required for this calculation.",
    "Include oxygen and all twelve H.",
  ),
  c(
    "p-family-halogen",
    "Classify a saturated addition product",
    "C2H4Br2 contains only single bonds. Which description is correct?",
    "A saturated halogen-containing compound",
    {
      "An alkane hydrocarbon":
        "Bromine is present; it contains more than C and H.",
      "An alkene because it was made from ethene":
        "Its supplied product has no C=C.",
    },
    "Classify the product from its own atoms and bonds rather than from the reactant name.",
    "Check both composition and bond type.",
  ),
  n(
    "p-process-E",
    "Account for unreacted gas",
    "A model supplies twelve ethene and eight water molecules and reports six additions. How many ethene molecules remain?",
    "6",
    "molecules",
    "12 − 6 = 6; unused ethene can return to the reactor.",
    "Subtract the reported additions.",
  ),
  n(
    "p-process-W",
    "Account for unused steam",
    "In the same model, eight water molecules enter and six additions occur. How many water molecules remain before cooling?",
    "2",
    "molecules",
    "8 − 6 = 2; they are unreacted feed molecules.",
    "Each addition consumes one water.",
  ),
  n(
    "p-process-P",
    "Use observed conversion",
    "Nine ethene and three water molecules enter a model reactor; two additions are reported. How many ethanol molecules form?",
    "2",
    "molecules",
    "Two reported additions make two ethanol; the supply maximum of three is not the observed amount.",
    "Use the reported reaction count.",
  ),
  n(
    "p-process-bound",
    "Find a supplied-feed bound",
    "Nine ethene and three water molecules enter. Each addition uses one of each. What maximum number of additions is allowed by the feed?",
    "3",
    "additions",
    "Only three water molecules are available; actual observed conversion may be lower.",
    "Find which reactant runs out first.",
  ),
  n(
    "p-process-zero",
    "Retain a genuine zero",
    "A supplied reactor record reports zero additions from four ethene and six water molecules. How many ethanol molecules form?",
    "0",
    "molecules",
    "Zero reactions form zero ethanol; neither a blank response nor an unsupported full-conversion assumption represents this result.",
    "Use the observed zero.",
  ),
  w(
    "p-cooler-explain",
    "Explain collected water",
    "Explain why the cooled outlet can contain both ethanol and water even though hydration consumes water.",
    "Some feed steam remains unreacted. Cooling condenses that water and the ethanol into a liquid mixture; the collected water is not a newly released hydration by-product.",
    [
      "State that some supplied steam remains unused.",
      "Cooling causes a physical state change.",
      "Distinguish unused feed water from a chemical by-product.",
    ],
    "Track the feed through reactor and cooler separately.",
  ),
  w(
    "p-recycle-explain",
    "Explain the return pipe",
    "A reactor/cooler process returns its unreacted ethene stream to the reactor. Explain the purpose of that return pipe.",
    "It recycles unreacted ethene so it can have another opportunity to react, reducing loss of unused feed. It does not mean that the returned gas has already become ethanol.",
    [
      "Identify the returned material as unreacted ethene.",
      "Explain reuse in another reactor pass.",
      "Do not count recycled feed as newly produced ethanol.",
    ],
    "Follow the chemical identity in the gas stream.",
  ),
  w(
    "p-ester-explain",
    "Track ester carbon atoms",
    "Explain why making ethyl ethanoate from ethanoic acid requires ethanol as a second carbon-containing reactant.",
    "Ethanoic acid supplies two carbons and ethanol supplies the other two. Their groups join in the four-carbon ester, with water as a separate small product.",
    [
      "Account for two acid-derived C.",
      "Account for two ethanol-derived C.",
      "Identify the ester and separate water product.",
    ],
    "Atoms must come from one of the starting reactants.",
  ),
  w(
    "p-routes-explain",
    "Compare two ethanol routes",
    "Compare the starting materials and conditions for industrial ethene hydration and yeast fermentation.",
    "Hydration adds heated steam to ethene under pressure with phosphoric acid. Fermentation uses aqueous glucose and yeast under suitable warm anaerobic conditions and forms ethanol with carbon dioxide.",
    [
      "Correct ethene/steam industrial route and catalyst.",
      "Correct glucose/yeast biological route and suitable warm anaerobic conditions.",
      "Distinguish fermentation CO2 from hydration, which releases no small by-product.",
    ],
    "Write the feeds before choosing conditions.",
  ),
  w(
    "p-oxidation-limit",
    "Use the stated alcohol",
    "The provided primary ethanol is oxidised to ethanoic acid. Explain why this example alone does not justify drawing a carboxylic acid from every alcohol produced by alkene hydration.",
    "The evidence is for the specified primary ethanol. Different alcohol connectivities can behave differently on oxidation; the task gives no rule that every alcohol yields a carboxylic acid.",
    [
      "Identify the specified primary ethanol.",
      "Do not extend its acid product to every possible alcohol connectivity.",
      "No additional oxidation product or mechanism recall is required.",
    ],
    "Use the particular starting structure supplied.",
  ),
  w(
    "p-addition-polymer",
    "Compare product extent",
    "Explain how ethene plus hydrogen differs from ethene addition polymerisation, even though each changes C=C to C–C.",
    "Hydrogenation adds one H2 across one ethene to make a discrete ethane molecule. Polymerisation connects many ethene monomers into a very large chain; other monomers supply the repeated carbon contributions. Neither stated addition releases a small by-product.",
    [
      "Correct H2 feed and discrete ethane product.",
      "Correct many-monomer feed and large-chain product.",
      "Do not invent water loss in ordinary addition polymerisation.",
    ],
    "Track the second feed and whether the product is a molecule or a repeated chain.",
  ),
  w(
    "p-higher-condensation",
    "Higher: distinguish polyester links",
    "Higher Chemistry: compare ordinary ethene addition polymerisation with the supplied diol/dicarboxylic-acid polyester route.",
    "Ethene monomers join without a small by-product. In the supplied polyester route, both monomers have two functional groups, allowing continued ester-link formation, with water eliminated at each actual ester link.",
    [
      "Addition uses C=C monomers and releases no small by-product.",
      "The supplied diol and diacid each have two reactive groups.",
      "Polyester ester-link formation releases water; do not infer a finite-chain count without its connectivity.",
    ],
    "Count reactive groups and actual links rather than guessing from a crop.",
  ),
);
