import { c, n } from "./pathways-tasks";
import type { PathwayTask as Task } from "./pathways-types";
export const guided: Task[] = [
  c(
    "g-hydrogen",
    "Add hydrogen",
    "Ethene reacts with H₂. Build its product and choose the formula.",
    "C2H6",
    {
      C2H4: "That omits the two added H.",
      C2H2: "This loses H instead of adding the supplied H2.",
    },
    "The original C2H4 retains all atoms; H2 adds one H to each reacting carbon and C=C becomes C–C.",
    "Select the original C=C pair before choosing its new attachments.",
    "addition",
    "initial",
  ),
  c(
    "g-water",
    "Show the O–H bond",
    "Build the product of ethene + steam. Which attachment pair represents the supplied water?",
    "H and OH",
    {
      "OH and OH": "That supplies two O atoms, while water contains only one.",
      "O and nothing": "Both water H atoms would be missing.",
    },
    "One H bonds to one carbon; the other H stays bonded to O in the OH on the other carbon.",
    "Use every atom from H2O.",
    "addition",
    "etheneWater",
  ),
  c(
    "g-bromine",
    "Distinguish addition from substitution",
    "Construct ethene + Br2. What happens to the four H already on the ethene molecule?",
    "All four remain",
    {
      "Two are replaced by Br":
        "That changes this addition into a substitution proposal.",
      "All four leave as hydrogen gas":
        "No such elimination is part of the stated reaction.",
    },
    "Both Br atoms add without replacing H. The product has C2H4Br2 and a single C–C bond.",
    "Trace the original hydrogens separately from the added halogens.",
    "addition",
    "etheneBr",
  ),
  c(
    "g-internal",
    "React at the actual C=C",
    "The supplied four-carbon alkene has its C=C between carbons 2 and 3. Where must H2 add?",
    "Across carbons 2 and 3",
    {
      "Across carbons 1 and 2":
        "That changes a different original single bond.",
      "Only at carbon 4": "The supplied double bond is internal.",
    },
    "The original terminal methyl groups remain. Each original double-bond carbon gains one H.",
    "Find the double bond in the fixed starting structure.",
    "addition",
    "internalH",
  ),
  c(
    "g-oh-site",
    "Use a supplied connectivity",
    "For this propene hydration drawing, OH is specified on carbon 2. Which statement is supported?",
    "Draw the stated carbon-2 OH product without inferring product proportions",
    {
      "Both possible alcohols must form in equal amounts":
        "The task supplies a connectivity, not a measured product distribution.",
      "Carbon 3 must disappear": "The original three-carbon chain is retained.",
    },
    "The exercise fixes which alcohol to represent. Selectivity, mechanisms and relative yields are not being assessed.",
    "Use the supplied OH placement.",
    "addition",
    "propeneWater",
  ),
  c(
    "g-conditions",
    "Choose the route conditions",
    "Use the industrial ethene hydration conditions board. Which combination belongs on the reaction arrow?",
    "Heated steam, pressure and phosphoric acid",
    {
      "Hydrogen and nickel": "That makes the alkane product.",
      "Glucose and yeast": "That is the alternative biological ethanol route.",
    },
    "The reagent is water as steam; phosphoric acid is the catalyst in the stated industrial reaction.",
    "Keep reagent, catalyst and conditions distinct.",
    "conditions",
    "steam",
  ),
  c(
    "g-evidence",
    "Interpret the bromine test",
    "Choose the ordinary alkene bromine-water test conditions and observation. Which conclusion follows from orange becoming colourless in this stated comparison?",
    "The supplied alkene reacts with bromine",
    {
      "The molecule must have become an alkane containing only C and H":
        "The product retains Br, so it is not a hydrocarbon.",
      "UV was necessarily present": "The ordinary test does not require UV.",
    },
    "Bromine adds at C=C and is consumed; the colour change is the test evidence.",
    "Use the actual observation rather than renaming every saturated product an alkane.",
    "conditions",
    "bromine",
  ),
  c(
    "g-inverse",
    "Infer the missing reagent",
    "Compare the supplied propene and alcohol structures. Their difference is two H and one O. What one reagent supplies that gain?",
    "Water",
    {
      "Oxygen only": "O2 supplies no H and contains two O.",
      "Hydrogen only": "H2 supplies no O.",
    },
    "The product gains H plus OH, which together are H2O. Inference from atom difference is not a spontaneous reverse reaction.",
    "Subtract original atoms from product atoms.",
    "infer",
    "water",
  ),
  n(
    "g-mass",
    "Count the entire ethanol molecule",
    "Use the supplied ethanol inventory and Ar(C)=12, Ar(H)=1, Ar(O)=16. Find its relative molecular mass.",
    "46",
    "relative molecular mass",
    "2 × 12 + 6 × 1 + 16 = 46, including the hydrogen bonded to O.",
    "Count O–H as part of the same molecule.",
    "ledger",
    "initial",
  ),
  c(
    "g-process",
    "Keep the actual reaction count",
    "The process diagram supplies ten ethene, eighteen water and six reported additions. How many ethene molecules remain?",
    "Four",
    {
      Zero: "Ten possible feed molecules does not prove ten reactions occurred.",
      Six: "Six is the reacted count, not the remainder.",
    },
    "10 − 6 = 4 unreacted ethene. Six ethanol form and twelve water remain.",
    "Use the supplied reported reaction count.",
    "process",
    "initial",
  ),
  c(
    "g-cooling",
    "Separate state change from reaction",
    "Use the same reactor/cooler diagram. Why can water appear in the collected liquid?",
    "Unused steam cools and condenses",
    {
      "Hydration releases water as its small by-product":
        "Water is consumed by hydration; excess supplied steam can remain.",
      "Ethene loses its carbon atoms in the cooler":
        "Cooling does not change those elements into water.",
    },
    "Physical condensation in the cooler is different from a chemical condensation reaction that eliminates water.",
    "Track original feed molecules through both stages.",
    "process",
    "initial",
  ),
  c(
    "g-ester",
    "Supply the missing carbon source",
    "Build the acid-to-ester route. What second organic feed contributes the ethyl group?",
    "Ethanol",
    {
      "Water alone": "Water contains no carbon to supply the ethyl group.",
      "Hydrogen alone": "H2 cannot supply two carbon atoms.",
    },
    "Ethanoic acid plus ethanol produces ethyl ethanoate and water. Two carbons originate in each organic reactant.",
    "Track the two carbon-containing reactants.",
    "map",
    "ester",
  ),
  c(
    "g-ferment",
    "Choose the alternative ethanol route",
    "Use the glucose pathway. Which small product accompanies ethanol in yeast fermentation?",
    "Carbon dioxide",
    {
      "Water as the only separate product":
        "That misses the carbon dioxide supplied by fermentation.",
      Bromine: "No bromine reactant is present.",
    },
    "Suitable warm anaerobic yeast fermentation produces ethanol in solution and CO2. It does not use the hydration catalyst.",
    "Distinguish the biological and steam routes.",
    "map",
    "ferment",
  ),
  c(
    "g-polymer",
    "Choose the chain-forming feed",
    "Use the ethene polymer route. Which feed provides the repeated carbon-chain contributions?",
    "More ethene monomers",
    {
      "One H2 molecule": "Hydrogen adds no carbon chain.",
      "One water molecule": "Water adds no carbon chain.",
    },
    "Many ethene monomers connect; no small by-product is released in ordinary addition polymerisation.",
    "Track where the repeated carbon atoms come from.",
    "map",
    "polymer",
  ),
];
