import type { LearningTask, LessonJourney } from "../types";
import { waterRecords as R, type WaterGiven } from "../../lib/water";
const id = (s: string) => "water-v1-" + s;
function choice(
  s: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
  record?: string,
  given?: WaterGiven,
): LearningTask {
  const opts = [answer, ...Object.keys(errors)],
    n = [...s].reduce((a, c) => a + c.charCodeAt(0), 0) % opts.length;
  return {
    id: id(s),
    title,
    purpose: title,
    prompt,
    answer,
    options: [...opts.slice(n), ...opts.slice(0, n)],
    misconceptions: errors,
    explanation,
    hint,
    ...(record
      ? {
          model: {
            kind: "water-investigation" as const,
            mode: R[record].mode,
            record,
          },
        }
      : {}),
    ...(given ? { waterGiven: given } : {}),
  };
}
function numeric(
  s: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
  record?: string,
  given?: WaterGiven,
): LearningTask {
  return {
    id: id(s),
    title,
    purpose: title,
    prompt,
    answer: String(answer),
    unit,
    inputMode: "decimal",
    tolerance: 1e-6,
    explanation,
    hint,
    ...(record
      ? {
          model: {
            kind: "water-investigation" as const,
            mode: R[record].mode,
            record,
          },
        }
      : {}),
    ...(given ? { waterGiven: given } : {}),
  };
}
function construct(
  s: string,
  title: string,
  prompt: string,
  refs: readonly (readonly [string, string, number])[],
  given: WaterGiven,
  explanation: string,
  hint: string,
): LearningTask {
  return {
    id: id(s),
    title,
    purpose: title,
    prompt,
    answer: JSON.stringify(
      Object.fromEntries(refs.map(([f, , v]) => [f, String(v)])),
    ),
    parts: refs.map(([f, label, answer]) => ({
      id: f,
      label,
      answer,
      inputMode: "decimal",
    })),
    partLegend: "Construct your water-analysis values",
    waterGiven: given,
    explanation,
    hint,
  };
}
function written(
  s: string,
  title: string,
  prompt: string,
  answer: string,
  rubric: string[],
  hint: string,
  given?: WaterGiven,
): LearningTask {
  return {
    id: id(s),
    title,
    purpose: title,
    prompt,
    answer,
    referenceResponse: answer,
    explanation: answer,
    rubric,
    hint,
    ...(given ? { waterGiven: given } : {}),
  };
}
const warmup = [
  choice(
    "w-mixture",
    "Recall dissolved substances",
    "Clear salt solution is…",
    "A mixture",
    {
      "Chemically pure H₂O": "Dissolved salt is another substance.",
      "An element": "Water and salt contain elements in compounds.",
    },
    "Dissolved salt can be invisible while the solution remains a mixture.",
    "Use composition, not appearance.",
  ),
  numeric(
    "w-volume",
    "Convert a sample volume",
    "Convert 25 cm³ to dm³.",
    0.025,
    "dm³",
    "1000 cm³=1 dm³, so 25÷1000=0.025 dm³.",
    "Divide by 1000.",
  ),
  numeric(
    "w-subtract",
    "Remove the dish contribution",
    "A dry empty dish is 31.25 g; dish plus cooled dry residue is 31.33 g. What is residue mass?",
    0.08,
    "g",
    "31.33−31.25=0.08 g.",
    "Subtract the empty dish.",
  ),
  choice(
    "w-phase",
    "Recall condensation",
    "Condensation changes water vapour into…",
    "Liquid water",
    {
      "Hydrogen and oxygen": "Phase change does not decompose H₂O.",
      Salt: "Water does not become salt.",
    },
    "Cooling changes water's state, not its chemical identity.",
    "Track H₂O.",
  ),
];
const refresher = [
  choice(
    "r-mineral",
    "Classify mineral water",
    "Use the stated quality evidence. Which description fits?",
    "Potable but not chemically pure",
    {
      "Pure because it is clear": "Dissolved minerals remain.",
      "Never potable if any mineral is present":
        "Acceptably low salts can remain.",
    },
    R.mineral.feedback,
    "Distinguish composition and supplied quality.",
    "mineral",
  ),
  choice(
    "r-clear",
    "Limit a quality inference",
    "Only clarity and pH 7 are supplied. What is established?",
    "Neither potability nor chemical purity",
    {
      "Both proved": "Invisible contaminants can remain.",
      "Potable because pH is neutral":
        "pH does not measure all salts or microbes.",
    },
    R.clear.feedback,
    "Notice the missing tests.",
    "clear",
  ),
  choice(
    "r-saline",
    "Use failed quality evidence",
    "Which observation prevents potability in this case?",
    "Salt exceeds the stated drinking-water limit",
    {
      "pH 7": "Neutral pH is not itself a salt failure.",
      "The sample is clear": "Clarity does not establish safe composition.",
    },
    R.saline.feedback,
    "Use the actual failed requirement.",
    "saline",
  ),
  choice(
    "r-pure",
    "Use stipulated composition",
    "Only H₂O and satisfactory quality are stipulated. Which applies?",
    "Both chemically pure and potable",
    {
      "No pure water can be potable": "The descriptions can overlap.",
      "Potable means always impure": "Potability does not require impurities.",
    },
    R.pure.feedback,
    "Use this stipulated case, not a general rule.",
    "pure",
  ),
  choice(
    "r-fresh",
    "Link treatments to contaminants",
    "Why use the supplied chlorine stage after filtering?",
    "Destroy harmful microorganisms",
    {
      "Remove every dissolved salt": "Chlorine is not desalination.",
      "Turn sediment into H₂O": "Filtration separates sediment.",
    },
    R.fresh.feedback,
    "Assign each stage one purpose.",
    "fresh",
  ),
  choice(
    "r-uv",
    "Distinguish UV from a substance",
    "The UV stage is…",
    "Disinfection using light",
    {
      "A chemical dissolved into water":
        "UV is radiation, not a dissolved chemical.",
      "A salt-removing filter": "UV does not desalinate.",
    },
    R.freshUV.feedback,
    "Separate light treatment from chemical agents.",
    "freshUV",
  ),
  choice(
    "r-ozone",
    "Explain an ozone plant",
    "After filtration, ozone mainly targets…",
    "Harmful microorganisms",
    {
      "All dissolved minerals": "Ozone does not remove every ion.",
      "Water molecules to create salt": "It does not turn water into salt.",
    },
    R.freshOzone.feedback,
    "Connect treatment and target.",
    "freshOzone",
  ),
  choice(
    "r-seawater",
    "Separate salty water",
    "Where is nonvolatile salt after the supplied distillation?",
    "In the heated flask",
    {
      "In the collected water vapour":
        "Nonvolatile salt does not evaporate with water in this case.",
      "Destroyed into nothing": "Atoms are conserved.",
    },
    R.seawater.feedback,
    "Trace which component evaporates.",
    "seawater",
  ),
  choice(
    "r-roRoute",
    "Follow a specified membrane plant",
    "Where is most rejected salt?",
    "In the brine stream",
    {
      "Destroyed by pressure": "Pressure does not destroy salt.",
      "In ordinary filter-paper pores": "This is a selective-membrane process.",
    },
    R.saltyRO.feedback,
    "Account for a separate waste stream.",
    "saltyRO",
  ),
  numeric(
    "r-dish10",
    "Construct residue concentration",
    "Use the model's original dish and 10 cm³ sample. Find g per dm³.",
    5,
    "g/dm³",
    R.dish10.feedback,
    "Subtract then convert volume.",
    "dish10",
  ),
  numeric(
    "r-dish25",
    "Scale a 25 cm³ sample",
    "Use the supplied dish readings. Find g per dm³.",
    4,
    "g/dm³",
    R.dish25.feedback,
    "0.025 dm³ is one fortieth of a litre.",
    "dish25",
  ),
  numeric(
    "r-dish50",
    "Scale a seawater sample",
    "Use the fixed 50 cm³ data. Find g per dm³.",
    32,
    "g/dm³",
    R.dish50.feedback,
    "Remove the empty dish first.",
    "dish50",
  ),
  numeric(
    "r-dish100",
    "Analyse dilute water",
    "Use the fixed 100 cm³ sample. Find g per dm³.",
    0.3,
    "g/dm³",
    R.dish100.feedback,
    "The difference is small but not zero.",
    "dish100",
  ),
  choice(
    "r-cold",
    "Connect the phase path",
    "What forms collected liquid at the cool end?",
    "Condensation of water vapour",
    {
      "Chemical decomposition": "H₂O identity remains.",
      "Evaporation of salt": "The supplied salt is nonvolatile.",
    },
    R.cold.feedback,
    "Heating and cooling have different roles.",
    "cold",
  ),
  choice(
    "r-uncooled",
    "Explain a cooling comparison",
    "With the same feed and heating time, effective cooling collects more because…",
    "More water vapour condenses before escaping",
    {
      "Cooling creates extra water atoms": "Atoms are not created.",
      "All dissolved salt becomes liquid water":
        "Salt stays at the heated end.",
    },
    R.uncooled.feedback,
    "Relate cooling to vapour collection.",
    "uncooled",
  ),
  choice(
    "r-identity",
    "Retain H₂O identity",
    "The delivery tube contains water vapour rather than…",
    "New hydrogen and oxygen gases",
    {
      "H₂O molecules": "Water vapour is H₂O.",
      "Water in a gaseous state": "That is exactly water vapour.",
    },
    R.identity.feedback,
    "A change of state is physical.",
    "identity",
  ),
  numeric(
    "r-mem100",
    "Conserve membrane volume",
    "Use the fixed 100 litre feed and supplied 40 litre product. Find brine volume.",
    60,
    "litres",
    R.mem100.feedback,
    "Feed equals product plus brine in this ideal exercise.",
    "mem100",
  ),
  numeric(
    "r-mem80",
    "Use a different recovery",
    "Use the fixed 80 litre feed and 24 litre product. Find brine volume.",
    56,
    "litres",
    R.mem80.feedback,
    "Subtract product from feed.",
    "mem80",
  ),
  numeric(
    "r-mem120",
    "Account for remaining water",
    "Use the fixed 120 litre feed and 54 litre product. Find brine volume.",
    66,
    "litres",
    R.mem120.feedback,
    "Do not discard the uncollected water.",
    "mem120",
  ),
  numeric(
    "r-coast",
    "Normalise route energy",
    "In the fixed comparison, how much more energy does B use per m³?",
    11,
    "kWh/m³",
    R.coast.feedback,
    "Divide each total by 2 m³.",
    "coast",
  ),
  numeric(
    "r-lake",
    "Compare a local freshwater source",
    "Use the fixed equal-volume totals. Find B−A per m³.",
    5.5,
    "kWh/m³",
    R.lake.feedback,
    "Compare equal quantities and the same boundary.",
    "lake",
  ),
  numeric(
    "r-heatReuse",
    "Read a signed comparison",
    "Use the fixed totals. Find B−A per m³.",
    -2,
    "kWh/m³",
    R.heatReuse.feedback,
    "A negative difference means B uses less here.",
    "heatReuse",
  ),
  numeric(
    "r-equal",
    "Recognise equal totals",
    "What is B−A per m³ for these fixed equal totals?",
    0,
    "kWh/m³",
    R.equal.feedback,
    "Same total and volume give the same per-volume energy.",
    "equal",
  ),
  numeric(
    "r-repeat50",
    "Average repeat residues",
    "Use all four supplied 50 cm³ repeats. Find the mean concentration.",
    34.2,
    "g/dm³",
    R.repeat50.feedback,
    "Mean mass first; scale second.",
    "repeat50",
  ),
  numeric(
    "r-repeat25",
    "Scale a repeat mean",
    "Use the three original 25 cm³ samples. Find the mean concentration.",
    4.8,
    "g/dm³",
    R.repeat25.feedback,
    "Equal-volume samples support direct mass averaging.",
    "repeat25",
  ),
  numeric(
    "r-repeat10",
    "Use dry residue evidence",
    "Use the four original 10 cm³ samples. Find the mean concentration.",
    3,
    "g/dm³",
    R.repeat10.feedback,
    "Do not confuse repeat consistency with proof of dryness.",
    "repeat10",
  ),
];
const guided = [
  choice(
    "g-quality",
    "Read water evidence",
    "Classify this mineral-water sample.",
    "Potable but not chemically pure",
    {
      "Clear therefore pure": "Dissolved minerals remain.",
      "Not potable because any mineral is forbidden":
        "Acceptably low salts can remain.",
    },
    R.mineral.feedback,
    "Use the supplied quality checks.",
    "mineral",
  ),
  choice(
    "g-treatment",
    "Build a freshwater route",
    "Choose the stages and track contaminants.",
    "Filter grit; disinfect microbes; dissolved minerals remain",
    {
      "Filter all dissolved salt": "Ordinary beds do not desalinate.",
      "Chlorine removes grit": "Filtration separates suspended solids.",
    },
    R.fresh.feedback,
    "Match each operation to its target.",
    "fresh",
  ),
  numeric(
    "g-residue",
    "Analyse dissolved solids",
    "Find the concentration from the original 10 cm³ sample.",
    5,
    "g/dm³",
    R.dish10.feedback,
    "Mass difference divided by sample volume in dm³.",
    "dish10",
  ),
  choice(
    "g-distil",
    "Collect distilled water",
    "Follow water through the apparatus.",
    "Evaporate water, cool vapour, collect liquid",
    {
      "Decompose H₂O into gases": "This is a physical phase separation.",
      "Collect salt vapour": "Nonvolatile salt stays in the flask.",
    },
    R.cold.feedback,
    "Trace the heated and cooled ends.",
    "cold",
  ),
  numeric(
    "g-membrane",
    "Conserve membrane streams",
    "Find the brine volume from the fixed membrane feed.",
    60,
    "litres",
    R.mem100.feedback,
    "Feed minus product.",
    "mem100",
  ),
  numeric(
    "g-energy",
    "Compare treatment energy",
    "Find B−A energy per m³ for the supplied coastal case.",
    11,
    "kWh/m³",
    R.coast.feedback,
    "Normalise both totals first.",
    "coast",
  ),
  numeric(
    "g-repeat",
    "Check practical evidence",
    "Find the mean concentration of the four equal-volume samples.",
    34.2,
    "g/dm³",
    R.repeat50.feedback,
    "Average all four masses, then scale.",
    "repeat50",
  ),
];
const residueGiven = (
  empty: number,
  cooled: number,
  volume: number,
): WaterGiven => ({
  title: "Original measured sample",
  note: "Stable nonvolatile residue; dry dish and cooled measurements.",
  rows: [],
  balance: { empty, cooled, volume },
});
const repeatGiven = (
  masses: readonly number[],
  volume: number,
): WaterGiven => ({
  title: "Original repeat measurements",
  note: "Independent equal-volume samples; dry cooled residue masses after empty-dish subtraction.",
  rows: [],
  repeat: { masses, volume },
});
const memGiven = (feed: number, product: number, salt: number): WaterGiven => ({
  title: "Original membrane inventory",
  note: "Ideal supplied model: no volume loss and complete salt rejection.",
  rows: [],
  membrane: { feed, product, salt },
});
const energyGiven = (a: number, b: number, volume: number): WaterGiven => ({
  title: "Original equal-service data",
  note: "Invented matched-volume energy totals with the same accounting boundary. Both products meet the supplied quality requirement.",
  rows: [],
  energy: { a, b, volume },
});
const practice = [
  choice(
    "p-clear",
    "Limit an inference",
    "Clear water has pH 7 at room temperature; no other tests are provided. Is potability established?",
    "No; relevant chemical and microbiological quality is unknown",
    {
      "Yes; neutral means safe": "pH does not test all salts or microbes.",
      "Yes; microbes are visible if present":
        "Clarity does not exclude microbes.",
    },
    "pH and clarity alone cannot certify drinking-water quality.",
    "Identify unmeasured properties.",
  ),
  choice(
    "p-minerals",
    "Separate potable and pure",
    "Water meets the stated drinking-water quality requirements and contains dissolved calcium salts. It is…",
    "Potable, but a mixture",
    {
      "Pure H₂O": "Calcium salts are other substances.",
      "Never potable": "Suitable low levels of dissolved minerals can remain.",
    },
    "Potability describes safe drinking quality; chemical purity describes composition.",
    "Use both definitions.",
  ),
  choice(
    "p-uv",
    "Name a disinfection method",
    "Which is a disinfection method using light?",
    "Ultraviolet treatment",
    {
      "Ozone addition": "Ozone is a chemical agent.",
      "Ordinary filter beds": "These remove suspended solids.",
    },
    "Chlorine, ozone and UV are specified disinfection options; UV is radiation.",
    "Separate light from a substance.",
  ),
  choice(
    "p-filtration",
    "Track dissolved salt",
    "Freshwater passes through ordinary filter beds. Its dissolved salt is…",
    "Still dissolved in the filtrate",
    {
      "All trapped as ordinary-filter residue":
        "Dissolved salt passes through ordinary beds.",
      "Changed into oxygen": "Physical filtration does not create oxygen.",
    },
    "Ordinary filtration separates undissolved particles, not all dissolved ions.",
    "Distinguish particles from dissolved solute.",
  ),
  written(
    "p-freshMethod",
    "Explain a treatment route",
    "Explain how a suitable freshwater source containing grit and harmful microbes becomes potable. Link each stage to its purpose.",
    "In the UK, rain with little dissolved matter replenishes freshwater sources. Choose a suitable source with acceptably low dissolved salts, such as a river, lake or groundwater supply. Filter beds remove undissolved solid particles. Then chlorine, ozone or ultraviolet treatment destroys harmful microorganisms. Check the supplied drinking-water quality requirements; dissolved minerals can remain at acceptable levels.",
    [
      "Suitable fresh source and sufficiently low salts",
      "Filtration linked to undissolved particles",
      "Disinfection method linked to microorganisms",
      "Potable does not require chemically pure H₂O",
    ],
    "Give step→reason links.",
  ),
  construct(
    "p-residue",
    "Construct a sample concentration",
    "Use the original readings; enter residue mass, sample dm³ and concentration.",
    [
      ["mass", "Residue mass / g", 0.15],
      ["volume", "Sample volume / dm³", 0.025],
      ["conc", "Concentration / g per dm³", 6],
    ],
    residueGiven(27.35, 27.5, 25),
    "27.50−27.35=0.15 g;25 cm³=0.025 dm³;0.15÷0.025=6 g/dm³.",
    "Exclude the dish, then convert volume.",
  ),
  construct(
    "p-dilute",
    "Analyse a low-residue sample",
    "Construct all three values from the supplied data.",
    [
      ["mass", "Residue mass / g", 0.02],
      ["volume", "Sample volume / dm³", 0.1],
      ["conc", "Concentration / g per dm³", 0.2],
    ],
    residueGiven(33.24, 33.26, 100),
    "0.02 g in 0.100 dm³ gives 0.20 g/dm³. A small residue is not automatically zero.",
    "Subtract carefully.",
  ),
  choice(
    "p-wet",
    "Evaluate wet residue",
    "If water remains with the residue, the calculated dissolved-solid mass is…",
    "Too high",
    {
      "Too low": "Retained water adds measured mass.",
      Unchanged: "The balance includes remaining water.",
    },
    "Wet residue includes water mass and overestimates dissolved solids.",
    "What extra mass is on the balance?",
  ),
  choice(
    "p-spill",
    "Evaluate sample loss",
    "Some salt residue spills before the final weighing. The result is…",
    "Too low",
    {
      "Too high": "Spillage removes measured residue.",
      Unaffected: "The missing salt changes the mass.",
    },
    "Lost residue underestimates dissolved solids; heating to dryness cannot restore spilled salt.",
    "Track the missing material.",
  ),
  written(
    "p-practical",
    "Plan water analysis",
    "Describe a supervised practical method to measure pH and dissolved solids in a known sample, including valid dry-residue evidence.",
    "Measure pH with a suitable pH probe/meter or universal indicator paper/solution. Weigh a clean dry empty evaporating dish using a balance. Measure a known water volume using suitable volume apparatus and add it to the dish. Under qualified supervision evaporate water by suitable controlled heating. Cool the dish before weighing; reheat, cool and reweigh until the mass is constant. Subtract empty-dish mass, convert sample volume to dm³ and divide residue mass by that volume. This measures the supplied stable nonvolatile dissolved solids, not every possible contaminant.",
    [
      "Suitable pH method",
      "Balance and known volume",
      "Controlled evaporation with school supervision",
      "Cool, weigh, reheat and obtain constant mass",
      "Subtract dish and use correct volume units",
      "Recognise limited quality evidence",
    ],
    "Explain the quantity measured at each step.",
  ),
  choice(
    "p-constant",
    "Evaluate dryness evidence",
    "Which evidence supports that a stable residue is dry?",
    "Reheat, cool and obtain the same mass on reweighing",
    {
      "A single hot-dish reading": "Hot-dish weighing is unsuitable evidence.",
      "Filter the dry salt again": "That does not demonstrate dryness.",
    },
    "Constant mass after reheating and cooling supports complete water removal in the stated stable-residue case.",
    "Look for an unchanged mass after further heating.",
  ),
  construct(
    "p-repeat",
    "Calculate repeat concentration",
    "Use all four equal-volume samples. Enter total residue, mean and mean concentration.",
    [
      ["total", "Total of repeat masses / g", 6.8],
      ["mean", "Mean residue / g", 1.7],
      ["conc", "Mean concentration / g per dm³", 34],
    ],
    repeatGiven([1.66, 1.7, 1.72, 1.72], 50),
    "Total 6.80 g; mean 6.80÷4=1.70 g;1.70÷0.050=34 g/dm³.",
    "Divide the sum by the number of equal-volume samples.",
  ),
  choice(
    "p-evap",
    "Choose the collected component",
    "To collect water from a nonvolatile salt solution, evaporation to dryness alone is insufficient because…",
    "Vapour must also be cooled and collected",
    {
      "Salt must first turn into water": "Salt is not converted to water.",
      "Water cannot become vapour": "Heating can evaporate water.",
    },
    "Evaporation leaves residue; distillation also condenses and collects the vapour.",
    "Which substance do you want to retain?",
  ),
  written(
    "p-steam",
    "Explain distillation and its checks",
    "Explain how a supervised practical collects water from a nonvolatile salt solution, then checks the collected sample.",
    "Heat the salt solution under qualified supervision to form water vapour; H₂O changes state rather than decomposing. A connected delivery tube leads to an open receiver in a cold-water or ice bath, where vapour cools and condenses into collected liquid. The delivery outlet stays above collected liquid to avoid drawing it back on cooling. Nonvolatile salt remains in the heated flask. In the supplied clean nonvolatile-salt case, compare original and collected samples using suitable pH and residue measurements; a boiling temperature near 100 °C at standard atmospheric pressure supports the expected water identity/purity in this limited practical. Pure water at the stated room temperature has pH 7. These observations alone do not certify every quality requirement for an unknown sample.",
    [
      "Supervised heating and H₂O phase identity",
      "Connected vapour route, cooling and open liquid collection",
      "Nonvolatile salt retained and outlet above collected liquid",
      "Compare samples using pH, residue and boiling conditions",
      "Limit the quality conclusion",
    ],
    "Link each part of the apparatus to its purpose and keep test conclusions limited.",
  ),
  written(
    "p-cooling",
    "Explain a fair collection comparison",
    "Two apparatus setups use equal starting salt solution and equal heating time. One receiver is effectively cooled; the other is not. Explain why the cooled setup collects more water.",
    "Heating forms water vapour in both setups. Effective cooling removes energy from the vapour so more condenses into liquid water before escaping. The uncooled setup loses more vapour without collecting it. Equal feed and heating time make the cooling comparison meaningful; cooling does not create water or carry nonvolatile salt into the receiver.",
    [
      "Evaporation in the heated flask",
      "Cooling linked to condensation",
      "Escaping vapour explains lower collection",
      "Equal comparison conditions and nonvolatile salt retained",
    ],
    "Link a change of state to collected volume.",
  ),
  choice(
    "p-idealDistillate",
    "Use a stipulated distillate case",
    "A nonvolatile salt solution is distilled in clean apparatus; heating destroys the specified microbes and collection is clean. Does this stated case need another sterilisation stage?",
    "No; the supplied distillate already meets the stated quality requirements",
    {
      "Always yes even if requirements are met": "Use this stipulated case.",
      "No because pH 7 alone proves all water safe":
        "pH alone cannot prove that.",
    },
    "This ideal case matches the specified separation and microbiological evidence. Do not extend it to unknown volatile contaminants or dirty collection.",
    "Use all stipulated conditions.",
  ),
  construct(
    "p-membrane",
    "Conserve both desalination streams",
    "Construct product, brine and retained salt values.",
    [
      ["product", "Product volume / litres", 36],
      ["brine", "Brine volume / litres", 54],
      ["salt", "Salt in brine / g", 2700],
    ],
    memGiven(90, 36, 2700),
    "90−36=54 litres brine; all 2700 g salt is retained under the stated ideal rejection.",
    "Feed equals the two streams combined.",
  ),
  construct(
    "p-brineConcentration",
    "Quantify brine concentration",
    "Find the brine volume and salt concentration in g per litre.",
    [
      ["brine", "Brine volume / litres", 50],
      ["conc", "Brine concentration / g per litre", 60],
    ],
    memGiven(100, 50, 3000),
    "50 litres remain;3000 g÷50 litres=60 g/litre, compared with 30 g/litre in the feed.",
    "Salt is retained in less water.",
  ),
  choice(
    "p-pressure",
    "Identify the RO mechanism",
    "Reverse osmosis separates water from dissolved salts using…",
    "High pressure and a selective membrane",
    {
      "An ordinary sediment filter alone":
        "That is not salt-selective reverse osmosis.",
      "A magnet attracting all water": "This is not the mechanism.",
    },
    "Pumping drives water through the membrane while most salts are retained; it requires energy and produces brine.",
    "Name both the driving force and barrier.",
  ),
  written(
    "p-desalination",
    "Compare desalination routes",
    "A coastal community has little rainfall and available energy. Explain two possible routes from salty water to potable water and one important resource consequence.",
    "Distillation heats water to form vapour and cools it to collect liquid, leaving nonvolatile salts behind. Reverse osmosis uses high pressure to drive water through a selective membrane while most salts remain in concentrated brine. Both need energy, for heating/cooling or pressure pumping. Choose using local source availability, supplied energy data and quality requirements; neither ordinary filtration nor pH 7 alone removes excessive dissolved salt.",
    [
      "Distillation evaporation and condensation with salt retained",
      "RO pressure and selective membrane",
      "Energy requirement linked to each route",
      "Local choice and quality requirements",
    ],
    "Describe separation, then resource cost.",
  ),
  construct(
    "p-energy",
    "Normalise treatment energy",
    "Compute both route energies per m³ and signed B−A.",
    [
      ["a", "A energy / kWh per m³", 3],
      ["b", "B energy / kWh per m³", 9],
      ["difference", "B minus A / kWh per m³", 6],
    ],
    energyGiven(15, 45, 5),
    "15÷5=3 and 45÷5=9 kWh/m³; B−A=6. The data favour A's supplied energy, not a universal environmental verdict.",
    "Use the same treated volume.",
  ),
  construct(
    "p-energyReverse",
    "Read a negative energy difference",
    "Compute both per-volume energies and signed B−A.",
    [
      ["a", "A energy / kWh per m³", 8],
      ["b", "B energy / kWh per m³", 5],
      ["difference", "B minus A / kWh per m³", -3],
    ],
    energyGiven(24, 15, 3),
    "8 and 5 kWh/m³; B−A=−3. B is lower inside this supplied boundary.",
    "Keep the requested subtraction order.",
  ),
  choice(
    "p-local",
    "Choose an available source",
    "A locality has suitable freshwater with low dissolved salt. Why can filtration/disinfection be preferable to seawater desalination?",
    "It can meet the standard with less separation energy in the supplied setting",
    {
      "Freshwater never has microbes": "It can still require disinfection.",
      "Seawater is chemically pure": "It contains dissolved salts.",
    },
    "Source suitability, treatment targets and local energy evidence matter; fresh water is not automatically potable before treatment.",
    "Avoid an absolute claim.",
  ),
  choice(
    "p-boil",
    "Exclude suspended solids",
    "Water contains dissolved salt and sand. Why filter before measuring its dissolved-solid residue?",
    "Prevent insoluble sand from being included in the residue mass",
    {
      "Remove all dissolved salt before measurement":
        "Ordinary filtration does not remove dissolved salt.",
      "Destroy all microorganisms":
        "Ordinary filtration alone does not establish disinfection.",
    },
    "Filter suspended sand first; dissolved salt remains in the known-volume filtrate. Otherwise sand would add to the residue and overestimate dissolved solids.",
    "Separate undissolved particles from dissolved solute.",
  ),
  choice(
    "p-pH",
    "Use a stated pH condition",
    "Pure water at the stated room-temperature condition has pH…",
    "7",
    {
      "0": "That is strongly acidic on this scale.",
      "14": "That is strongly alkaline.",
    },
    "Room-temperature pure water is neutral, pH 7. Neutral pH alone does not prove purity or safety.",
    "Neutral on the room-temperature GCSE scale.",
  ),
  written(
    "p-testLimits",
    "Evaluate a limited water test",
    "A clear sample is pH 7 and leaves no measurable nonvolatile residue in a small sample. Explain what can and cannot be concluded.",
    "The observations show neutral pH and no residue above the method's detection limit for that sampled volume. They do not establish that only H₂O is present: volatile or very low-level dissolved contaminants could be unmeasured. Microbiological quality has not been assessed. Potability requires the relevant drinking-water quality evidence, not appearance or one practical test alone.",
    [
      "Neutral pH at the stated condition",
      "No measured residue is a detection-limited result",
      "Possible unmeasured chemical impurities",
      "Microbiological quality not established",
    ],
    "Separate measurement from a stronger claim.",
  ),
  numeric(
    "p-scaleOnly",
    "Scale a measured residue",
    "A 50 cm³ sample yields 1.55 g of dry nonvolatile residue. Find the mass in 1000 cm³ of homogeneous water.",
    31,
    "g",
    "1000÷50=20;1.55×20=31 g.",
    "Use the ratio of volumes.",
  ),
];
const checkForms = [
  [
    choice(
      "cA-quality",
      "Interpret quality",
      "A clear, pH 7 sample exceeds the stated salt limit. It is…",
      "Not potable in this stated case",
      {
        "Potable because pH 7": "The salt requirement fails.",
        "Pure because clear": "Dissolved salt remains.",
      },
      "Stated failed salt quality overrides appearance/pH.",
      "Use every supplied fact.",
    ),
    choice(
      "cA-treatment",
      "Select stages",
      "Suitable freshwater has grit and harmful microorganisms but acceptable salts. Which route addresses both?",
      "Filter then disinfect",
      {
        "Disinfect only": "Grit remains.",
        "Filter only": "Microbiological quality is not established.",
      },
      "Filtration targets undissolved solids; disinfection targets microbes.",
      "Match two contaminants.",
    ),
    construct(
      "cA-residue",
      "Analyse reserved measurements",
      "Construct mass, dm³ and g/dm³.",
      [
        ["mass", "Residue mass / g", 0.18],
        ["volume", "Sample volume / dm³", 0.03],
        ["conc", "Concentration / g per dm³", 6],
      ],
      residueGiven(29.14, 29.32, 30),
      "0.18÷0.030=6 g/dm³.",
      "Subtract and convert.",
    ),
    choice(
      "cA-distil",
      "Explain collection",
      "Nonvolatile salt solution is distilled. The collected water forms by…",
      "Condensation of water vapour",
      {
        "Condensation of salt": "Nonvolatile salt remains.",
        "Decomposition of H₂O": "Water identity remains.",
      },
      "Cooling condenses water vapour; this is physical separation.",
      "Track H₂O.",
    ),
    construct(
      "cA-membrane",
      "Account for streams",
      "Find brine volume and retained salt.",
      [
        ["brine", "Brine volume / litres", 72],
        ["salt", "Brine salt / g", 4000],
      ],
      memGiven(125, 53, 4000),
      "125−53=72 litres;4000 g is retained in the ideal model.",
      "Conserve both quantities.",
    ),
    construct(
      "cA-energy",
      "Compare reserved energy",
      "Find A and B per-m³ energy and B−A.",
      [
        ["a", "A energy / kWh per m³", 2],
        ["b", "B energy / kWh per m³", 7],
        ["difference", "B minus A / kWh per m³", 5],
      ],
      energyGiven(14, 49, 7),
      "14÷7=2;49÷7=7; difference 5 kWh/m³.",
      "Normalise totals.",
    ),
    written(
      "cA-method",
      "Explain the required practical",
      "Explain pH/residue analysis and distillation of a supplied nonvolatile salt solution in a supervised laboratory.",
      "Measure pH using a suitable probe or universal indicator. Weigh an empty dry dish, measure a known sample volume, evaporate water under supervision, cool and weigh residue to constant mass after reheating. Subtract empty-dish mass and divide by sample dm³. In distillation heat water to form vapour and cool it through the collection route to obtain liquid water in a clean receiver; nonvolatile salts remain in the flask. This is practical reasoning, not proof of every drinking-water quality requirement.",
      [
        "Suitable pH measurement",
        "Known volume and empty-dish subtraction",
        "Cool and repeat weighing to constant mass",
        "Evaporation, cooling and liquid collection",
        "Nonvolatile salt retained; quality inference limited",
      ],
      "Link apparatus operations to quantities and phase changes.",
    ),
    choice(
      "cA-dry",
      "Judge evidence",
      "Stable residue gives the same cooled mass after reheating. This supports…",
      "Dryness to constant mass in the stated method",
      {
        "Absence of every microbe in all water":
          "Residue mass is not a microbiological test.",
        "Creation of new salt": "Mass consistency is not atom creation.",
      },
      "Constant mass supports dryness, not universal safety.",
      "Keep the inference within the measurement.",
    ),
  ],
  [
    choice(
      "cB-pure",
      "Apply definitions",
      "A quality-approved drinking-water sample contains dissolved minerals. Which is true?",
      "Potable does not imply chemically pure",
      {
        "All ions make it unsafe": "Acceptably low salts can remain.",
        "Clear means only H₂O": "Dissolved solute can be invisible.",
      },
      "Composition and drinking quality are distinct.",
      "Use both terms precisely.",
    ),
    choice(
      "cB-UV",
      "Classify a method",
      "UV water treatment is…",
      "Disinfection by light",
      {
        "Chemical removal of all salts": "UV does not desalinate.",
        "A magnetic separation": "That is not the mechanism.",
      },
      "UV targets microorganisms; chlorine and ozone are alternative chemical agents.",
      "Identify the target.",
    ),
    construct(
      "cB-residue",
      "Use another sample volume",
      "Construct residue mass, dm³ and concentration.",
      [
        ["mass", "Residue mass / g", 0.07],
        ["volume", "Sample volume / dm³", 0.02],
        ["conc", "Concentration / g per dm³", 3.5],
      ],
      residueGiven(38.4, 38.47, 20),
      "0.07 g in 0.020 dm³ gives 3.5 g/dm³.",
      "Dish is excluded.",
    ),
    construct(
      "cB-repeat",
      "Average reserved repeats",
      "Construct total, mean and concentration.",
      [
        ["total", "Total residue masses / g", 3.72],
        ["mean", "Mean residue / g", 1.24],
        ["conc", "Mean concentration / g per dm³", 31],
      ],
      repeatGiven([1.2, 1.24, 1.28], 40),
      "Total 3.72; mean 1.24;1.24÷0.040=31 g/dm³.",
      "Equal-volume means first.",
    ),
    choice(
      "cB-pressure",
      "Explain reverse osmosis",
      "Which combination describes reverse osmosis?",
      "High pressure and a selective membrane",
      {
        "Ordinary sand filter and gravity": "Ordinary beds do not desalinate.",
        "Heating to make hydrogen": "H₂O decomposition is not RO.",
      },
      "Water crosses the membrane; most salts are retained in brine.",
      "Identify barrier and force.",
    ),
    construct(
      "cB-energy",
      "Use a reversed ranking",
      "Construct both per-m³ energies and B−A.",
      [
        ["a", "A energy / kWh per m³", 6],
        ["b", "B energy / kWh per m³", 4],
        ["difference", "B minus A / kWh per m³", -2],
      ],
      energyGiven(30, 20, 5),
      "6 versus 4; B−A=−2 kWh/m³ inside this boundary.",
      "Keep a signed difference.",
    ),
    written(
      "cB-source",
      "Justify treatment choice",
      "Explain why a coastal area with little freshwater may desalinate seawater. Compare the two specified desalination mechanisms and limits on a quality claim.",
      "Seawater is available but contains too much dissolved salt for the stated drinking-water requirement. Distillation evaporates water and condenses it into a clean receiver while nonvolatile salt remains behind. Reverse osmosis uses high pressure and a selective membrane to pass water while retaining most salts in brine. Both use energy, and local supply and matched energy data guide choice. Quality must meet the stated requirements; clarity or neutral pH alone does not establish potability.",
      [
        "Local availability and excessive salt",
        "Evaporation and condensation",
        "Pressure and selective membrane with brine",
        "Energy and limited quality inference",
      ],
      "Give reason-linked mechanisms.",
    ),
    choice(
      "cB-cooling",
      "Predict collection",
      "Equal feed and heating time: effective cooling increases collected liquid because…",
      "More vapour condenses before escaping",
      {
        "New water is created": "Water is conserved.",
        "Salt starts evaporating": "The supplied salt is nonvolatile.",
      },
      "Cooling improves water-vapour collection; it is not a chemical reaction.",
      "Link temperature to phase.",
    ),
  ],
];
const reviewForms = [
  [
    choice(
      "vA-quality",
      "Retrieve definitions",
      "Water meets quality requirements with low dissolved salts. It may be…",
      "Potable but not chemically pure",
      {
        "Always pure": "Dissolved salts are other substances.",
        "Always unsafe": "Suitable low salt levels can remain.",
      },
      "Potability is quality; purity is composition.",
      "Use the distinction.",
    ),
    numeric(
      "vA-residue",
      "Retrieve sample scaling",
      "A 20 cm³ sample yields 0.09 g dry nonvolatile residue. Find g per dm³.",
      4.5,
      "g/dm³",
      "0.09÷0.020=4.5 g/dm³.",
      "Convert volume.",
    ),
    choice(
      "vA-path",
      "Retrieve a physical separation",
      "In distillation, salt is nonvolatile. Water is collected by…",
      "Evaporation followed by condensation",
      {
        "H₂O decomposition": "Phase change does not split the molecule.",
        "Evaporating salt only": "Salt remains behind.",
      },
      "Water vapour cools back to liquid.",
      "Track both phases.",
    ),
    written(
      "vA-filter",
      "Retrieve a linked treatment account",
      "Explain why ordinary filtration and disinfection address different contaminants.",
      "Ordinary filter beds remove undissolved particles. Chlorine, ozone or UV treatment destroys harmful microorganisms. Neither ordinary filtration nor disinfection removes all dissolved salts, so a source with excessive salt requires desalination. Acceptable minerals can remain in potable water.",
      [
        "Undissolved particles and filtration",
        "Microorganisms and a named disinfection method",
        "Dissolved salt limitation",
      ],
      "Name operation, target and limitation.",
    ),
  ],
  [
    choice(
      "vB-evidence",
      "Retrieve test limits",
      "Clear, pH 7 water with no microbiological results is…",
      "Not yet established as potable",
      {
        "Automatically safe":
          "Microbiological and chemical quality are incomplete.",
        "Automatically pure": "pH/clarity do not establish composition.",
      },
      "A limited measurement cannot justify a stronger safety claim.",
      "What evidence is missing?",
    ),
    construct(
      "vB-membrane",
      "Retrieve conservation",
      "Find brine volume and salt for the original inventory.",
      [
        ["brine", "Brine volume / litres", 46],
        ["salt", "Brine salt / g", 2100],
      ],
      memGiven(70, 24, 2100),
      "70−24=46 litres with 2100 g retained salt in the stated ideal model.",
      "Conserve feed and solute.",
    ),
    numeric(
      "vB-energy",
      "Retrieve energy normalisation",
      "A process uses 28 kWh to treat 4 m³. Find kWh per m³.",
      7,
      "kWh/m³",
      "28÷4=7 kWh/m³.",
      "Energy divided by volume.",
    ),
    written(
      "vB-dry",
      "Retrieve measurement quality",
      "Explain why residue is cooled and reweighed after reheating, and how wet residue or spilled residue biases the result.",
      "Cool the dish before weighing to obtain a suitable mass reading. Reheat, cool and reweigh until constant mass to support complete water removal for the supplied stable nonvolatile residue. Remaining water increases apparent dissolved-solid mass; spillage loses residue and decreases it. Subtract the original empty-dish mass.",
      [
        "Cool before weighing",
        "Reheat and constant mass",
        "Wet residue overestimates",
        "Spillage underestimates and dish subtraction",
      ],
      "Track added or lost measured mass.",
    ),
  ],
];
guided[0].openingHint = true;
const recover = [
  "r-clear",
  "r-mineral",
  "r-uv",
  "r-fresh",
  "r-fresh",
  "r-dish25",
  "r-dish100",
  "r-repeat50",
  "r-repeat50",
  "r-dish10",
  "r-repeat50",
  "r-repeat50",
  "r-cold",
  "r-identity",
  "r-uncooled",
  "r-seawater",
  "r-mem100",
  "r-mem100",
  "r-roRoute",
  "r-seawater",
  "r-coast",
  "r-heatReuse",
  "r-lake",
  "r-fresh",
  "r-clear",
  "r-clear",
  "r-dish50",
];
export const waterRecoveryRoutes: Record<string, string> = {};
practice.forEach((q, i) => {
  q.followUp = id(recover[i]);
  waterRecoveryRoutes[q.id] = q.followUp;
});
export const allWaterTasks = [
  ...warmup,
  ...refresher,
  ...guided,
  ...practice,
  ...checkForms.flat(),
  ...reviewForms.flat(),
];
export const waterExposureFamilies = {
  quality: [
    "w-mixture",
    "r-mineral",
    "g-quality",
    "p-minerals",
    "cB-pure",
    "vA-quality",
  ],
  limited: ["r-clear", "p-clear", "vB-evidence"],
  saltyQuality: ["r-saline", "cA-quality"],
  fresh: [
    "r-fresh",
    "r-uv",
    "r-ozone",
    "g-treatment",
    "p-filtration",
    "p-freshMethod",
    "p-boil",
    "cA-treatment",
    "vA-filter",
  ],
  uv: ["r-uv", "p-uv", "cB-UV"],
  distil: [
    "w-phase",
    "r-cold",
    "g-distil",
    "p-evap",
    "p-steam",
    "cA-distil",
    "vA-path",
  ],
  identity: ["r-identity", "p-steam"],
  cooling: ["r-uncooled", "p-cooling", "cB-cooling"],
  dry: ["p-constant", "cA-dry", "vB-dry"],
  residue: ["r-dish10", "g-residue", "r-dish25", "r-dish50", "r-dish100"],
  membrane: [
    "r-mem100",
    "g-membrane",
    "r-mem80",
    "r-mem120",
    "r-roRoute",
    "p-pressure",
    "cB-pressure",
  ],
  energy: ["r-coast", "g-energy", "r-lake", "r-heatReuse", "r-equal"],
  repeat: ["r-repeat50", "g-repeat", "r-repeat25", "r-repeat10"],
};
const groups = Object.values(waterExposureFamilies).map((fs) => new Set(fs));
let merged = true;
while (merged) {
  merged = false;
  outer: for (let a = 0; a < groups.length; a++)
    for (let b = a + 1; b < groups.length; b++)
      if ([...groups[a]].some((s) => groups[b].has(s))) {
        groups[a] = new Set([...groups[a], ...groups[b]]);
        groups.splice(b, 1);
        merged = true;
        break outer;
      }
}
for (const group of groups)
  for (const s of group) {
    const q = allWaterTasks.find((q) => q.id === id(s));
    if (!q) throw Error("Unknown water exposure task " + s);
    q.exposureAliases = [...group].filter((o) => o !== s).map(id);
  }
export const waterJourney: LessonJourney = {
  version: 1,
  introduction:
    "Read water evidence, choose treatments and analyse practical results.",
  scopeNote:
    "AQA Chemistry 8462 4.10.1.2 and required practical 8; Trilogy 8464 5.10.1.2 and required practical 13. Both tiers. Original simulations/data and honest written self-review; school-supervised practical competence and whole-course exam readiness are not established by this lesson.",
  outcomes: [
    "Distinguish potable, chemically pure and clear water using supplied quality evidence.",
    "Choose suitable fresh/salty sources and link filtration, chlorine, ozone and UV to their targets.",
    "Measure pH, subtract empty-dish mass, convert known volumes and calculate dissolved-solid concentration.",
    "Use reheating, cooling, constant mass and equal-volume repeats; evaluate wet/spilled residue.",
    "Explain evaporation, condensation, nonvolatile salt retention and effective receiver cooling using a rotatable 3D apparatus.",
    "Explain high-pressure reverse osmosis, energy and concentrated brine; conserve supplied ideal inventories.",
    "Compare energy per equal treated volume and justify local choice without universal ranking claims.",
  ],
  warmup,
  refresher,
  guided,
  practice,
  checkForms,
  reviewForms,
  practiceGroups: [
    {
      label: "Quality evidence and freshwater treatment",
      taskIds: practice.slice(0, 5).map((q) => q.id),
    },
    {
      label: "Measure and evaluate dissolved solids",
      taskIds: practice.slice(5, 12).map((q) => q.id),
    },
    {
      label: "Distillation and membrane separation",
      taskIds: practice.slice(12, 20).map((q) => q.id),
    },
    {
      label: "Resource choices and reliable water tests",
      taskIds: practice.slice(20).map((q) => q.id),
    },
  ],
};
