import type { LearningTask, LessonJourney, TaskModel } from "../types";
import { choice, number } from "./helpers";
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  ...choice(
    `rm-v1-${id}`,
    prompt,
    answer,
    errors,
    explanation,
    hint,
    title,
    model,
  ),
  title,
});
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...number(`rm-v1-${id}`, prompt, answer, unit, explanation, hint, title),
  title,
});
const guided = [
  c(
    "g-ratio",
    "Scale the mole ratio",
    "From 0.5 mol N₂ with excess H₂, find NH₃ mol.",
    "1 mol",
    {
      "0.25 mol": "The requested/given coefficient factor is 2/1, not 1/2.",
      "3 mol":
        "0.5 mol is the nitrogen amount, not the total of all coefficients.",
    },
    ".5×(2/1)=1 mol NH₃. Coefficients give mole ratios.",
    "Identify given and requested coefficients separately.",
    {
      kind: "reacting-masses",
      mode: "ratio",
      instruction: "Predict the coefficients and mol.",
    },
  ),
  c(
    "g-forward",
    "Link mass through moles",
    "N₂ + 3 H₂ → 2 NH₃. From 14 g N₂ with excess H₂, find theoretical NH₃ mass. M(N₂)=28, M(NH₃)=17 g/mol.",
    "17 g",
    {
      "28 g":
        "Multiplying 14 g by the coefficient ratio omits the different molar masses.",
      "8.5 g": "The ammonia amount is twice the nitrogen amount, not equal.",
    },
    "14/28=.5 mol N₂;×2=1 mol NH₃;×17=17 g. Equivalent mass ratio:34 g NH₃ per 28 g N₂.",
    "Grams→given mol→requested mol→grams.",
    {
      kind: "reacting-masses",
      mode: "forward",
      instruction: "Predict given mol, requested mol and mass.",
    },
  ),
  c(
    "g-required",
    "Find a required reactant",
    "2 Mg + SiO₂ → Si + 2 MgO. Find Mg required for 1.2 kg SiO₂. M(SiO₂)=60, M(Mg)=24 g/mol.",
    "960 g",
    {
      "2400 g":
        "2:1 is a mole ratio; weight it with each molar mass for a mass ratio.",
      "0.96 g": "Convert 1.2 kg to 1200 g before using g/mol.",
    },
    "1200/60=20 mol SiO₂;×2=40 mol Mg;×24=960 g. Equivalently 1200×48/60=960 g. Both named substances are reactants.",
    "Calculate the Mg needed, not a product mass.",
    {
      kind: "reacting-masses",
      mode: "required",
      instruction: "Convert the silica mass, then predict required magnesium.",
    },
  ),
  c(
    "g-conserved",
    "Compare mass and amount",
    "N₂ + 3 H₂ → 2 NH₃. For 1 mol N₂ and 3 mol H₂, compare total molecular amount and mass before/after theoretical complete conversion. M values:28,2,17 g/mol.",
    "Mass stays 34 g; total molecular amount changes 4→2 mol",
    {
      "Mass and molecular amount both stay the same":
        "Atom counts and mass are conserved; molecule count can change.",
      "Mass halves because molecule count halves":
        "The molecules have different molar masses.",
    },
    "Before 28+3×2=34 g;after 2×17=34 g.4 mol molecules become 2 mol molecules; nitrogen/hydrogen atom amounts are unchanged.",
    "Weight every molecular amount by its own molar mass.",
    {
      kind: "reacting-masses",
      mode: "conserved",
      instruction: "Predict molecular amounts and masses on both sides.",
    },
  ),
];
guided[0].openingHint = true;
export const reactingMassesJourney: LessonJourney = {
  version: 1,
  introduction:
    "Use balanced equation ratios to calculate theoretical amounts and masses of named substances, including required reactants.",
  scopeNote:
    "Higher reacting-mass scope: AQA4.3.2.2 and Trilogy equivalent; Pearson 1.48 context. Calculations assume theoretical complete conversion of the given reactant with other reactants sufficient/in excess unless stoichiometric amounts are specified. The ammonia equation here describes stoichiometric accounting, not complete real Haber-process conversion. Mole-based and equivalent coefficient-weighted mass-ratio methods are both valid. Balancing from measured masses, limiting reactants and actual yield remain separate lessons. The 3 D event shows a handful of representative molecules, not moles or reaction trajectories.",
  outcomes: [
    "Identify given/requested coefficients and scale mol in either direction.",
    "Convert mass units and use molar masses around the mole-ratio step.",
    "Calculate a required reactant as well as a product.",
    "Explain conserved mass/atom amounts without claiming conserved molecule counts.",
  ],
  warmup: [
    n(
      "w-amount",
      "Recall mass to amount",
      "Find amount in 14 g N₂. M=28 g/mol.",
      0.5,
      "mol",
      "14÷28=.5 mol.",
      "Use grams divided by grams per mol.",
    ),
    n(
      "w-mass",
      "Recall amount to mass",
      "Find mass of 2 mol NH₃. M=17 g/mol.",
      34,
      "g",
      "2×17=34 g.",
      "Multiply mol by molar mass.",
    ),
  ],
  refresher: [
    c(
      "r-coeff",
      "Name the ratio quantity",
      "In N₂ + 3 H₂ → 2 NH₃, what does 1:3:2 describe?",
      "Mole amounts of N₂:H₂:NH₃",
      {
        "Gram masses of N₂:H₂:NH₃":
          "Different substances have different grams per mole.",
        "Subscripts inside each molecule":
          "Subscripts define composition; coefficients count whole entities.",
      },
      "Coefficients scale whole molecules and mol amounts; mass ratios require molar masses.",
      "Separate coefficients from subscripts and grams.",
    ),
    c(
      "r-direction",
      "Choose the direction",
      "For 3 mol H₂ producing 2 mol NH₃, which factor converts given H₂ mol to NH₃ mol?",
      "2/3",
      {
        "3/2": "That converts ammonia mol to hydrogen mol.",
        "1/5": "The given amount is not the sum of both coefficient shares.",
      },
      "Requested coefficient divided by given coefficient gives 2/3.",
      "Write requested/given.",
    ),
    c(
      "r-unit",
      "Match mass units",
      "Which starting mass must be used for 1.2 kg SiO₂ when M=60 g/mol?",
      "1200 g",
      {
        "1.2 g": "The supplied mass is kilograms.",
        "0.0012 g": "Kilograms are larger than grams.",
      },
      "1.2×1000=1200 g.",
      "Match the g in g/mol.",
    ),
    c(
      "r-assumption",
      "Bound the calculation",
      "A theoretical product mass is calculated from one reactant. Which condition is needed?",
      "Enough of the other reactants and complete conversion of the given reactant",
      {
        "Every real reaction always reaches that mass":
          "Actual yield and equilibrium can reduce product obtained.",
        "The product has the same molar mass as the reactant":
          "The balanced ratio works with different molar masses.",
      },
      "This is a theoretical stoichiometric amount; sufficient other reactants and full conversion are assumptions.",
      "Distinguish theoretical calculation from actual yield.",
    ),
    c(
      "r-conservation",
      "Identify the conserved quantity",
      "In N₂ + 3 H₂ → 2 NH₃, which must be conserved?",
      "Total mass and each element's atom amount",
      {
        "Total number of molecules":
          "Four reactant molecules correspond to two product molecules.",
        "Mass of each individual substance":
          "Reactants become different products.",
      },
      "Atoms rearrange; different numbers of differently composed molecules can form.",
      "Count atoms before counting molecules.",
    ),
  ],
  guided,
  practice: [
    n(
      "p-nitrogen",
      "Transfer a mole ratio",
      "N₂ + 3 H₂ → 2 NH₃. Find NH₃ mol from 0.8 mol N₂ with excess H₂.",
      1.6,
      "mol",
      ".8×2=1.6 mol.",
      "Use requested/given=2/1.",
    ),
    n(
      "p-hydrogen",
      "Use the given hydrogen share",
      "N₂ + 3 H₂ → 2 NH₃. Find theoretical NH₃ mol from 0.9 mol H₂ with excess N₂.",
      0.6,
      "mol",
      ".9×2/3=.6 mol.",
      "The given coefficient is 3.",
    ),
    n(
      "p-reverse",
      "Reverse the direction",
      "N₂ + 3 H₂ → 2 NH₃. How much H₂ is required for 0.4 mol NH₃?",
      0.6,
      "mol",
      ".4×3/2=.6 mol H₂.",
      "Requested H₂ coefficient 3; given NH₃ coefficient 2.",
    ),
    n(
      "p-equal",
      "Recognise a 1:1 pair",
      "2 Mg + O₂ → 2 MgO. Find theoretical MgO mol from 0.35 mol Mg with excess O₂.",
      0.35,
      "mol",
      ".35×2/2=.35 mol.",
      "Both named coefficients are 2.",
    ),
    n(
      "p-ammonia",
      "Transfer a mass calculation",
      "N₂ + 3 H₂ → 2 NH₃. Find theoretical NH₃ mass from 7 g N₂ with excess H₂. M: N₂28,NH₃17 g/mol.",
      8.5,
      "g",
      "7/28=.25 mol N₂;×2=.5 mol NH₃;×17=8.5 g.",
      "Use all three stages.",
    ),
    n(
      "p-water",
      "Transfer a diatomic molar mass",
      "2 H₂ + O₂ → 2 H₂O. Find theoretical H₂O mass from 8 g O₂ with excess H₂. M: O₂32,H₂O18 g/mol.",
      9,
      "g",
      "8/32=.25 mol O₂;×2=.5 mol water;×18=9 g.",
      "O₂ has molar mass 32, not 16.",
    ),
    n(
      "p-oxide",
      "Use equal mole amounts and unequal masses",
      "2 Mg + O₂ → 2 MgO. Find MgO mass from 3 g Mg with excess O₂. M: Mg 24,MgO40 g/mol.",
      5,
      "g",
      "3/24=.125 mol;MgO also.125 mol;×40=5 g.",
      "Equal mol need not mean equal grams.",
    ),
    n(
      "p-required",
      "Scale required magnesium",
      "2 Mg + SiO₂ → Si + 2 MgO. Find Mg mass required for 150 g SiO₂. M: SiO₂60,Mg 24 g/mol.",
      120,
      "g",
      "150/60=2.5 mol SiO₂;Mg 5 mol;mass 120 g.",
      "Both named substances are reactants.",
    ),
    n(
      "p-required-kg",
      "Transfer kilograms",
      "2 Mg + SiO₂ → Si + 2 MgO. Find Mg required for 0.45 kg SiO₂. M: SiO₂60,Mg 24 g/mol. Answer in grams.",
      360,
      "g",
      "450/60=7.5 mol;Mg 15 mol;×24=360 g.",
      "Convert kg first.",
    ),
    n(
      "p-decompose",
      "Handle a 3:2 ratio",
      "2 Al₂O₃ → 4 Al + 3 O₂. Find theoretical O₂ mass from 20.4 g Al₂O₃. M: Al₂O₃102,O₂32 g/mol.",
      9.6,
      "g",
      "20.4/102=.2 mol;×3/2=.3 mol O₂;×32=9.6 g.",
      "Requested/given ratio is 3/2.",
    ),
    n(
      "p-reverse-mass",
      "Calculate precursor mass",
      "CaCO₃ → CaO + CO₂. Find CaCO₃ required to produce 22 g CO₂ theoretically. M: CaCO₃100,CO₂44 g/mol.",
      50,
      "g",
      "22/44=.5 mol CO₂;requires.5 mol CaCO₃;×100=50 g.",
      "Use the 1:1 mole ratio in reverse.",
    ),
    n(
      "p-same-unit",
      "Use an equivalent weighted ratio",
      "2 Al₂O₃ → 4 Al + 3 O₂.204 kg Al₂O₃ corresponds to 96 kg O₂. Find theoretical O₂ from 51 kg Al₂O₃, using this given mass ratio.",
      24,
      "kg",
      "51×96/204=24 kg. Both sides use kg consistently.",
      "A valid mass ratio already includes molar masses.",
    ),
    c(
      "p-repair",
      "Repair a coefficient-as-grams error",
      "A learner says 14 g N₂ makes 28 g NH₃ because N₂:NH₃ coefficients are 1:2. M values 28 and 17 g/mol. What repairs this?",
      "Convert 14 g N₂ to 0.5 mol, scale to 1 mol NH₃, then convert to 17 g",
      {
        "Keep 28 g because coefficients are always mass ratios":
          "Coefficient ratios count mol, not grams.",
        "Divide 14 g by the sum 1+2":
          "The given mass belongs to N₂, not the whole mixture.",
      },
      "The correct mass ratio is 28:34, so 14 g N₂ gives 17 g NH₃ theoretically.",
      "Use grams per mol before and after scaling.",
    ),
    {
      ...c(
        "p-working",
        "Construct complete reacting-mass working",
        "2 H₂ + O₂ → 2 H₂O. From 24 g O₂ with excess H₂, enter O₂ mol, H₂O mol and H₂O mass in g. M:32 and 18 g/mol.",
        JSON.stringify({ given: "0.75", requested: "1.5", mass: "27" }),
        {},
        "24/32=.75 mol O₂;×2=1.5 mol H₂O;×18=27 g.",
        "Track the named substance at each stage.",
      ),
      options: undefined,
      partLegend: "Construct mol and mass working",
      parts: [
        { id: "given", label: "O₂ amount / mol", answer: 0.75 },
        { id: "requested", label: "H₂O amount / mol", answer: 1.5 },
        { id: "mass", label: "H₂O mass / g", answer: 27 },
      ],
    },
    {
      ...c(
        "p-reverse-working",
        "Construct required-reactant working",
        "N₂ + 3 H₂ → 2 NH₃. Find H₂ required for 10.2 g NH₃ theoretically. Enter NH₃ mol, required H₂ mol and H₂ mass in g. M: NH₃17,H₂2 g/mol.",
        JSON.stringify({ given: "0.6", requested: "0.9", mass: "1.8" }),
        {},
        "10.2/17=.6 mol NH₃;×3/2=.9 mol H₂;×2=1.8 g.",
        "Reverse the ratio before multiplying by H₂ molar mass.",
      ),
      options: undefined,
      partLegend: "Construct reverse calculation",
      parts: [
        { id: "given", label: "NH₃ amount / mol", answer: 0.6 },
        { id: "requested", label: "H₂ amount / mol", answer: 0.9 },
        { id: "mass", label: "H₂ mass / g", answer: 1.8 },
      ],
    },
    n(
      "p-total-before",
      "Calculate all reactant mass",
      "N₂ + 3 H₂ → 2 NH₃. For 0.2 mol N₂ and 0.6 mol H₂, find total initial mass. M:28 and 2 g/mol.",
      6.8,
      "g",
      ".2×28+.6×2=5.6+1.2=6.8 g.",
      "Add masses, not unweighted mol amounts.",
    ),
    n(
      "p-total-after",
      "Check the complete product mass",
      "N₂ + 3 H₂ → 2 NH₃.0.2 mol N₂ and 0.6 mol H₂ theoretically form 0.4 mol NH₃. M(NH₃)=17 g/mol. Find total product mass.",
      6.8,
      "g",
      ".4×17=6.8 g, matching total reactant mass.",
      "Use the product molar mass.",
    ),
    c(
      "p-molecules",
      "Explain changed molecular amount",
      "For 1 mol N₂ +3 mol H₂ →2 mol NH₃, why does total molecular amount fall from 4 to 2 mol?",
      "Atoms are regrouped into differently composed molecules",
      {
        "Half the atoms disappear":
          "N atom amount 2 mol and H atom amount 6 mol are retained.",
        "Each mole always has an equal mass":
          "Molar masses differ between substances.",
      },
      "Molecule count need not be conserved when atom counts and total mass are conserved.",
      "Compare atoms within each molecule.",
    ),
    {
      ...c(
        "p-explain",
        "Explain the mass ratio",
        "Explain why N₂:NH₃ coefficients 1:2 give theoretical mass ratio 28:34 rather than 1:2, using M values 28 and 17 g/mol.",
        "Coefficients give mol ratio 1:2. One mol N₂ has mass 28 g; two mol NH₃ have mass 2×17=34 g. Thus requested/given mass factor 34/28 includes each molar mass; bare coefficient ratios do not give gram ratios.",
        {},
        "Compare your use of mol ratios and grams per mol.",
        "Weight each coefficient by its molar mass.",
      ),
      options: undefined,
      rubric: [
        "Identifies coefficients as mol ratios.",
        "Calculates masses 28 g and 34 g.",
        "Explains why a gram ratio needs both molar masses.",
      ],
    },
    {
      ...c(
        "p-justify",
        "Explain conservation and assumptions",
        "Explain how total mass is conserved in N₂ +3 H₂ →2 NH₃ even though molecule count changes. State why theoretical product mass is not automatically actual Haber-process yield. M values 28,2,17 g/mol.",
        "One N₂ plus three H₂ contains two N and six H atoms, as do two NH₃. Weighted mass 28+3×2=2×17=34 g. Molecule amount changes 4→2 mol without losing atoms. A theoretical calculation assumes sufficient reactants and complete conversion; the real Haber reaction is reversible and actual yield need not reach that amount.",
        {},
        "Review conserved quantities and the theoretical assumption separately.",
        "Count atoms and compare weighted masses before discussing real conversion.",
      ),
      options: undefined,
      rubric: [
        "Retains two N and six H per equation event.",
        "Shows 34 g on each side despite 4→2 mol molecules.",
        "States theoretical full-conversion/sufficient-reactant assumptions and real yield limitation.",
      ],
    },
  ],
  checkForms: [
    [
      n(
        "ca-mass",
        "Calculate a fresh product mass",
        "2 Mg + O₂ →2 MgO. Find MgO mass from 4.8 g Mg with excess O₂. M: Mg 24,MgO40 g/mol.",
        8,
        "g",
        "4.8/24=.2 mol;×2/2=.2 mol;×40=8 g.",
        "Use mol ratio between the named species.",
      ),
      n(
        "ca-ratio",
        "Scale a fresh non-unit ratio",
        "N₂ +3 H₂ →2 NH₃. Find theoretical NH₃ mol from 1.2 mol H₂ with excess N₂.",
        0.8,
        "mol",
        "1.2×2/3=.8 mol.",
        "Use requested/given.",
      ),
      n(
        "ca-required",
        "Calculate a fresh required-reactant mass",
        "N₂ +3 H₂ →2 NH₃. Find H₂ required for 6.8 g NH₃. M:17 and 2 g/mol.",
        1.2,
        "g",
        "6.8/17=.4 mol NH₃;×3/2=.6 mol H₂;×2=1.2 g.",
        "Calculate in reverse.",
      ),
      {
        ...c(
          "ca-working",
          "Construct unfamiliar decomposition working",
          "CaCO₃ →CaO +CO₂. From 15 g CaCO₃, enter CaCO₃ mol and theoretical CO₂ mass in g. M:100 and 44 g/mol.",
          JSON.stringify({ given: "0.15", mass: "6.6" }),
          {},
          "15/100=.15 mol;×1/1×44=6.6 g.",
          "Use mol before grams.",
        ),
        options: undefined,
        partLegend: "Construct decomposition working",
        parts: [
          { id: "given", label: "CaCO₃ amount / mol", answer: 0.15 },
          { id: "mass", label: "CO₂ mass / g", answer: 6.6 },
        ],
      },
      c(
        "ca-quantity",
        "Name the coefficient quantity",
        "Balanced equation coefficients directly give which ratios?",
        "Mole amounts of named substances",
        {
          "Gram masses regardless of substance":
            "Molar masses are also needed.",
          "Total initial mass shares":
            "A given mass belongs to the specified substance.",
        },
        "Coefficients count complete entities and mol amounts.",
        "Distinguish amount from mass.",
      ),
    ],
    [
      n(
        "cb-mass",
        "Transfer a fresh kilogram sample",
        "2 H₂ +O₂ →2 H₂O. Find theoretical H₂O mass from 0.004 kg O₂ with excess H₂. M:32 and 18 g/mol.",
        4.5,
        "g",
        "4/32=.125 mol;×2=.25 mol;×18=4.5 g.",
        "Convert kg to g first.",
      ),
      n(
        "cb-reverse",
        "Reverse a fresh mole ratio",
        "N₂ +3 H₂ →2 NH₃. Find N₂ required for 0.7 mol NH₃.",
        0.35,
        "mol",
        ".7×1/2=.35 mol.",
        "Requested coefficient divided by given coefficient.",
      ),
      n(
        "cb-required",
        "Calculate a fresh Mg requirement",
        "2 Mg +SiO₂ →Si +2 MgO. Find Mg needed for 0.09 kg SiO₂. M: SiO₂60,Mg 24 g/mol.",
        72,
        "g",
        "90/60=1.5 mol SiO₂;Mg 3 mol;×24=72 g.",
        "Both named substances are reactants.",
      ),
      {
        ...c(
          "cb-working",
          "Construct a fresh product calculation",
          "N₂ +3 H₂ →2 NH₃. From 4.2 g N₂ with excess H₂, enter NH₃ mol and theoretical NH₃ mass in g. M: N₂28,NH₃17 g/mol.",
          JSON.stringify({ requested: "0.3", mass: "5.1" }),
          {},
          "4.2/28=.15 mol N₂;×2=.3 mol NH₃;×17=5.1 g.",
          "Scale mol before converting to grams.",
        ),
        options: undefined,
        partLegend: "Construct product amount and mass",
        parts: [
          { id: "requested", label: "NH₃ amount / mol", answer: 0.3 },
          { id: "mass", label: "NH₃ mass / g", answer: 5.1 },
        ],
      },
      c(
        "cb-conserved",
        "Identify conservation in a molecular reaction",
        "When complete molecules regroup during a balanced reaction, what must stay unchanged?",
        "Total mass and each element's atom amount",
        {
          "The number of molecules":
            "Coefficients on each side may have different sums.",
          "The mass of every individual substance":
            "Reactants are consumed and products form.",
        },
        "Atoms rearrange into different molecules; total mass is conserved.",
        "Name the conserved quantities.",
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "ra-mass",
        "Retrieve reacting mass",
        "2 Mg +O₂ →2 MgO. Find theoretical MgO mass from 1.8 g Mg with excess oxygen. M:24 and 40 g/mol.",
        3,
        "g",
        "1.8/24×2/2×40=3 g.",
        "Use the mol ratio.",
      ),
      n(
        "ra-required",
        "Retrieve required-reactant direction",
        "N₂ +3 H₂ →2 NH₃. Find H₂ required for 3.4 g NH₃ theoretically. M:17 and 2 g/mol.",
        0.6,
        "g",
        "3.4/17×3/2×2=.6 g.",
        "Reverse the ratio.",
      ),
      n(
        "ra-ratio",
        "Retrieve non-unit scaling",
        "N₂ +3 H₂ →2 NH₃. Find NH₃ mol from 0.45 mol H₂ with excess N₂.",
        0.3,
        "mol",
        ".45×2/3=.3 mol.",
        "Use requested/given coefficients.",
      ),
    ],
    [
      n(
        "rb-mass",
        "Retrieve kilogram conversion",
        "2 H₂ +O₂ →2 H₂O. Find H₂O mass from 0.002 kg O₂ with excess H₂. M:32 and 18 g/mol.",
        2.25,
        "g",
        "2/32×2×18=2.25 g.",
        "Convert kilograms before using g/mol.",
      ),
      n(
        "rb-required",
        "Retrieve required magnesium",
        "2 Mg +SiO₂ →Si +2 MgO. Find Mg required for 75 g SiO₂. M:60 and 24 g/mol.",
        60,
        "g",
        "75/60×2×24=60 g.",
        "Both substances are reactants.",
      ),
      n(
        "rb-total",
        "Retrieve weighted total mass",
        "N₂ +3 H₂ →2 NH₃. For 0.3 mol N₂ and 0.9 mol H₂, calculate total initial mass. M:28 and 2 g/mol.",
        10.2,
        "g",
        ".3×28+.9×2=10.2 g.",
        "Sum masses after multiplying each amount by its own M.",
      ),
    ],
  ],
};
reactingMassesJourney.practice.find(
  (q) => q.id === "rm-v1-p-repair",
)!.followUp = "rm-v1-r-coeff";
