import type { LearningTask, LessonJourney, TaskModel } from "../types";
import type { TangentMode } from "../../lib/tangent-rates";
import type { TangentGraph } from "../../components/TangentPlot";
type Model = Extract<TaskModel, { kind: "tangent-rates" }>;
const model = (
  mode: TangentMode,
  instruction: string,
  record?: string,
): Model => ({ kind: "tangent-rates", mode, instruction, record });
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
  m?: Model,
): LearningTask => ({
  id: "tr-v1-" + id,
  title,
  purpose: title,
  prompt,
  answer: String(answer),
  unit,
  tolerance: 1e-10,
  explanation,
  hint,
  model: m,
});
function c(
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
  m?: Model,
): LearningTask {
  const choices = [answer, ...Object.keys(errors)],
    offset = [...id].reduce((s, x) => s + x.charCodeAt(0), 0) % choices.length;
  return {
    id: "tr-v1-" + id,
    title,
    purpose: title,
    prompt,
    answer,
    options: [...choices.slice(offset), ...choices.slice(0, offset)],
    misconceptions: errors,
    explanation,
    hint,
    model: m,
  };
}
const w = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  rubric: string[],
  graph?: TangentGraph,
): LearningTask => ({
  id: "tr-v1-" + id,
  title,
  purpose: title,
  prompt,
  answer,
  explanation: answer,
  hint: rubric[0],
  rubric,
  tangentDrawing: graph,
});
const practiceGraph: TangentGraph = {
  curve: {
    start: 0,
    end: 40,
    max: 60,
    unit: "cm³",
    quantity: "Gas collected",
    origin: 0,
    a: -0.025,
    b: 2.5,
    c: 0,
    at: 20,
    label: "Constructed product curve",
  },
  label: "Original constructed product curve; construct a tangent at 20 s.",
};
const reservedGraph: TangentGraph = {
  curve: {
    start: 0,
    end: 40,
    max: 50,
    unit: "cm³",
    quantity: "Gas collected",
    origin: 0,
    a: -0.02,
    b: 2,
    c: 0,
    at: 20,
    label: "Reserved constructed product curve",
  },
  label: "Reserved original product curve; construct your tangent at 20 s.",
};
export const tangentJourney: LessonJourney = {
  version: 1,
  introduction:
    "Construct a tangent at a moment, read a gradient triangle and convert a chemical amount or calibrated signal into amount per second.",
  scopeNote:
    "Higher/shared working AQA 8462 4.6.1.1 (printed 56) and Trilogy 8464 5.6.1.1 (printed 99), both actually read: numerical tangent gradients and mol/s. Actual 2022 Higher Paper 2 Q 08.2 (QP 30–31, MS 24) freshly read and graph/mark scheme visually inspected; OpenStax Chemical Reaction Rates read; actual Maths gradients-of-curves/average-rates-of-change sources and four live views inspected. The official optical question supplies 7.1×10⁻⁵mol sulfur per percentage-point decrease; it marks construction, coordinate differences, ratio, evaluation and calibration separately, allowing follow-through. No single exact official tangent answer is asserted. App calculation cases use original constructed exact coordinates and explicit calibrations, not examiner drawing equivalence. A tangent follows the local direction; a finite-interval chord gives an average. Signed remaining-reactant/signal slope can be negative while positive chemical consumption/production uses the stated magnitude and calibration. Moles may be directly given or converted using explicit Mr, mmol conversion or supplied room-condition molar volume. Written and drawn answers remain self-reviewed; no automatic exam mark, practical competence or grade prediction. No calculus/kinetic laws or unsupported other-board alignment.",
  warmup: [
    n(
      "warm-difference",
      "Subtract both coordinates",
      "Points(10, 20), (30, 50) lie on one straight line. What is its vertical difference, later ordinate minus earlier?",
      30,
      "",
      "50−20=30. Subtract both ordinates before division.",
      "Subtract 20 from 50.",
    ),
    n(
      "warm-seconds",
      "Convert the horizontal axis",
      "How many seconds are in 1.5 minutes?",
      90,
      "s",
      "1.5×60=90 s. Convert before giving a per-second rate.",
      "Multiply by 60.",
    ),
  ],
  refresher: [
    n(
      "r-seconds",
      "Convert a time interval",
      "A tangent triangle spans 1.5 minutes horizontally. Convert that span to seconds.",
      90,
      "s",
      "1.5 × 60 = 90 s. Convert the difference of times once before giving a per-second rate.",
      "Multiply the elapsed minutes by 60.",
    ),
    n(
      "r-mass-amount",
      "Convert mass to amount",
      "0.44 g CO₂ is formed. Mr(CO₂) = 44. How many moles is this?",
      0.01,
      "mol",
      "n = mass / Mr = 0.44 / 44 = 0.01 mol. Do not multiply mass by Mr.",
      "Divide mass by Mr.",
    ),
    n(
      "r-gas-amount",
      "Use an explicitly supplied molar volume",
      "At the stated room temperature and pressure, one mole occupies 24000 cm³. How many moles are in 240 cm³?",
      0.01,
      "mol",
      "n = 240 / 24000 = 0.01 mol. This conversion uses the explicitly supplied conditions and volume units.",
      "Divide volume by the stated volume per mole.",
    ),
    n(
      "r-time",
      "Horizontal difference",
      "A supplied tangent uses times 40 s and 100 s. What horizontal difference is used?",
      60,
      "s",
      "100−40=60 s; 100 s is not the interval.",
      "Subtract the two times.",
    ),
    n(
      "r-gradient",
      "A straight-line slope",
      "A tangent passes through(10 s, 20 cm³), (30 s, 50 cm³). Calculate its gradient.",
      1.5,
      "cm³/s",
      "(50−20)/(30−10)=30/20=1.5cm³/s.",
      "Use the changes in both coordinates.",
    ),
    n(
      "r-negative",
      "Retain the plotted sign",
      "Remaining reactant changes from 5 g to 1 g along a tangent over 20 s. Give the signed gradient.",
      -0.2,
      "g/s",
      "(1−5)/20=−0.2 g/s. The plotted remaining amount falls.",
      "Later remaining amount minus earlier.",
    ),
    n(
      "r-consumption",
      "Positive consumption",
      "A remaining-reactant tangent has gradient−0.2 g/s. What is its positive consumption rate?",
      0.2,
      "g/s",
      "Reactant is consumed at 0.2 g/s; the sign describes decreasing remaining amount.",
      "Give the magnitude for consumption.",
    ),
    n(
      "r-mmol",
      "Millimoles to moles",
      "Convert 9 mmol to mol.",
      0.009,
      "mol",
      "9/1000=0.009 mol. A millimole is one thousandth of a mole.",
      "Divide by 1000.",
    ),
    n(
      "r-amount-rate",
      "Moles over time",
      "0.006 mol product forms in 30 s. Calculate its mean formation rate.",
      0.0002,
      "mol/s",
      "0.006/30=0.0002 mol/s. A mean is a finite-interval rate.",
      "Divide amount formed by elapsed time.",
    ),
    n(
      "r-percent-point",
      "A percentage-point change",
      "A light signal falls from 55 % to 35 %. What is the magnitude of this change in percentage points?",
      20,
      "percentage-points",
      "55−35=20 percentage-points. This is not 20 mol and needs no additional divide-by 100 for a per-percentage-point calibration.",
      "Subtract the supplied percentage readings.",
    ),
    c(
      "r-moment",
      "Choose the local construction",
      "What represents reaction rate at 30 s on a curved product-time graph?",
      "The tangent at 30 s",
      {
        "The whole 0–60 s chord": "A chord gives a finite-interval mean.",
        "The graph height at 30 s":
          "Height is quantity, not quantity per time.",
      },
      "A tangent follows the local direction at the requested moment.",
      "Look for the local direction.",
    ),
    c(
      "r-points",
      "Choose points on the right line",
      "Which points are used for the gradient of a drawn tangent?",
      "Two readable points on the same tangent",
      {
        "Two unrelated observed points on the curve":
          "Their join is a chord, not necessarily that tangent.",
        "Only the contact point": "A gradient needs coordinate differences.",
      },
      "Use two separated readable points on the tangent; they need not be measured curve observations.",
      "Both points must lie on your tangent.",
    ),
    c(
      "r-calibration",
      "Signal is not chemical amount",
      "A signal falls by percentage points each second. What is needed before converting it to mol/s?",
      "A supplied signal-change to chemical-amount calibration",
      {
        "Nothing: percentage points are moles":
          "These quantities have different meanings.",
        "Only the final graph height":
          "Height alone supplies neither slope nor a conversion.",
      },
      "The optical signal is indirect; the stated calibration relates its change to chemical amount.",
      "What maps signal change to moles?",
    ),
    c(
      "r-initial",
      "The first moment",
      "What is the initial rate on an amount-time curve?",
      "The tangent gradient when the reaction begins",
      {
        "The final amount divided by all elapsed time":
          "This is a whole-interval mean when starting at zero.",
        "The highest graph height": "Height represents amount.",
      },
      "Initial rate is instantaneous rate at the beginning, not total final amount/time.",
      "Initial describes a moment.",
    ),
    c(
      "r-precision",
      "Avoid false precision",
      "Why is an experimental tangent rate described as an estimate?",
      "Drawing and coordinate reading have limited precision",
      {
        "Ten calculator digits guarantee ten accurate digits":
          "Calculator output cannot remove graph-reading uncertainty.",
        "A tangent is always a whole-interval average":
          "It represents local direction.",
      },
      "Report precision supported by the graph and question, not all digits displayed by a calculator.",
      "Consider how the line and coordinates are obtained.",
    ),
  ],
  guided: [
    n(
      "g-construct",
      "Construct a tangent",
      "Construct the tangent at 20 s and find the product-formation rate.",
      1.5,
      "cm³/s",
      "The tangent at 20 s has 1.5 cm³/s gradient. One suitable pair is(10 s, 25 cm³), (30 s, 55 cm³), giving 30/20. These are tangent points, not curve observations. Practice guidance is not an examiner mark.",
      "Place a line through the requested contact and local direction.",
      model(
        "construct",
        "Move two endpoints, then predict the signed gradient and quantity role.",
      ),
    ),
    n(
      "g-gradient",
      "Calculate both triangle spans",
      "Use the supplied tangent coordinates to calculate product-formation rate.",
      1.5,
      "cm³/s",
      "The supplied points giveΔquantity=30 cm³ andΔtime=20 s; 30/20=1.5 cm³/s.",
      "Subtract both pairs of coordinates.",
      model(
        "gradient",
        "Predict horizontal difference, signed vertical difference, signed gradient and positive chemical rate independently.",
      ),
    ),
    n(
      "g-moles",
      "A mean amount rate",
      "0.006 mol product forms in 30 s. Use the model to calculate mol/s.",
      0.0002,
      "mol/s",
      "0.006/30=0.0002 mol/s. This is the stated mean, not an instantaneous tangent.",
      "Amount over elapsed time.",
      model(
        "moles",
        "Convert only when necessary; keep amount, elapsed seconds and rate separate.",
      ),
    ),
    n(
      "g-calibration",
      "Falling signal, positive production",
      "Use the supplied constructed optical tangent and 7.1×10⁻⁵mol/percentage-point calibration. Calculate sulfur formation rate.",
      0.000071,
      "mol/s",
      "Signal slope=(35−55)/(40−20)=−1 percentage-point/s. Sulfur formation rate=1×0.000071=0.000071 mol/s; the calibration maps decrease to positive production.",
      "Take the magnitude in the stated direction, then multiply by calibration.",
      model(
        "calibration",
        "Keep signed signal slope separate from positive calibrated product rate.",
      ),
    ),
    c(
      "g-evidence",
      "What does a tangent establish?",
      "Which construction represents rate at 30 s?",
      "The tangent at the requested moment",
      {
        "The whole-interval chord":
          "Its slope gives the mean over that interval.",
        "Final quantity divided by 30":
          "It ignores nonzero starts and changing rates.",
      },
      "A tangent gives the local direction at a moment; a chord gives a finite-interval mean.",
      "Match the construction to a moment.",
      model("evidence", "Choose the supported claim and scientific reason."),
    ),
  ],
  practice: [
    n(
      "p-early",
      "An earlier tangent",
      "Construct the tangent at 10 s on the original product curve; calculate its formation rate.",
      2,
      "cm³/s",
      "At 10 s the tangent slope is 2 cm³/s; suitable endpoints(0 s, 2.5 cm³), (20 s, 42.5 cm³) give 40/20.",
      "Follow the local direction at 10 s.",
      model(
        "construct",
        "Retain your line and compare its local direction.",
        "early",
      ),
    ),
    n(
      "p-late",
      "A later tangent",
      "Construct the tangent at 30 s; calculate its formation rate.",
      1,
      "cm³/s",
      "Suitable endpoints(20 s, 42.5 cm³), (35 s, 57.5 cm³) give 15/15=1 cm³/s. A later tangent is shallower on this constructed slowing curve.",
      "Use 30 s, not the earlier requested moment.",
      model(
        "construct",
        "Place a line at 30 s and choose a visible wide triangle.",
        "late",
      ),
    ),
    n(
      "p-mass-line",
      "Read a different vertical scale",
      "Construct the product-mass tangent at 20 s and calculate g/s.",
      0.08,
      "g/s",
      "Suitable endpoints(10 s, 1.2 g), (30 s, 2.8 g) give 1.6/20=0.08 g/s.",
      "Read the mass scale, not the gas-volume scale.",
      model("construct", "Construct and predict using the g axis.", "mass"),
    ),
    n(
      "p-consuming-line",
      "A falling remaining-amount curve",
      "Construct the tangent at 20 s on the remaining-reactant graph. Give positive consumption rate.",
      0.1,
      "g/s",
      "The tangent through(10 s, 4 g), (30 s, 2 g) has signed gradient−0.1 g/s; positive consumption is 0.1 g/s.",
      "Retain the negative plotted gradient; interpret its magnitude.",
      model(
        "construct",
        "Signed gradient and positive consumption are different fields.",
        "consumption",
      ),
    ),
    n(
      "p-flat-line",
      "Horizontal at nonzero amount",
      "Construct a horizontal tangent at 30 s on the constant 40 cm³ curve. Give its rate.",
      0,
      "cm³/s",
      "Any visible sufficiently separated endpoints on the 40 cm³ horizontal line give zero ordinate change and zero rate. Nonzero amount is not a nonzero rate.",
      "What changes along a horizontal tangent?",
      model(
        "construct",
        "Keep the amount at 40 while predicting its slope.",
        "flat",
      ),
    ),
    n(
      "p-offset-triangle",
      "Do not divide final coordinates",
      "Use the supplied product-mass tangent points(40 s, 1.4 g), (100 s, 3.2 g) to calculate g/s.",
      0.03,
      "g/s",
      "(3.2−1.4)/(100−40)=1.8/60=0.03g/s.",
      "Subtract both nonzero starting values.",
      model("gradient", "Predict both differences before division.", "offset"),
    ),
    n(
      "p-negative-triangle",
      "Interpret the signed result",
      "Use the supplied remaining-reactant tangent. Give positive consumption rate.",
      0.2,
      "g/s",
      "Signed vertical difference−4 g over 20 s gives−0.2 g/s gradient and 0.2 g/s consumption.",
      "A falling remaining amount means reactant is being consumed.",
      model(
        "gradient",
        "Retain signed ordinate change and positive consumption.",
        "falling",
      ),
    ),
    n(
      "p-horizontal-triangle",
      "A plateau triangle",
      "Supplied tangent points(30 s, 40 cm³), (70 s, 40 cm³). Calculate the product-formation rate.",
      0,
      "cm³/s",
      "(40−40)/(70−30)=0/40=0.",
      "Same height means zero vertical difference.",
      model(
        "gradient",
        "Do not divide the nonzero graph height by final time.",
        "horizontal",
      ),
    ),
    n(
      "p-minute-triangle",
      "Convert an axis once",
      "Use tangent points(0.5 min, 12 cm³), (1.5 min, 42 cm³). Give cm³/s.",
      0.5,
      "cm³/s",
      "Δtime=1min=60s;Δvolume=30cm³;30/60=0.5cm³/s.",
      "Convert the difference of times into seconds.",
      model(
        "gradient",
        "Predict the horizontal difference in seconds.",
        "minutes",
      ),
    ),
    n(
      "p-reversed-order",
      "Keep subtraction order consistent",
      "Supplied tangent points are listed in reverse time order. Calculate the formation rate.",
      1.5,
      "cm³/s",
      "Reorder both coordinates together: 30 cm³/20 s=1.5 cm³/s. Reversing both subtraction orders also preserves the ratio.",
      "Do not reverse only one coordinate difference.",
      model(
        "gradient",
        "Use earlier-to-later differences consistently.",
        "reverse",
      ),
    ),
    n(
      "p-consumed-moles",
      "A positive molar consumption",
      "0.012 mol reactant is consumed over 40 s. Calculate mean mol/s.",
      0.0003,
      "mol/s",
      "0.012/40=0.0003 mol/s. Consumed amount is positive.",
      "Use the amount consumed, not the remaining amount.",
      model("moles", "Interpret the given consumed amount.", "consumed"),
    ),
    n(
      "p-mmol-minutes",
      "Two independent conversions",
      "9 mmol product forms in 1.5 min. Calculate mean mol/s.",
      0.0001,
      "mol/s",
      "9mmol=0.009mol;1.5min=90s;0.009/90=0.0001mol/s.",
      "Convert both mmol and minutes.",
      model(
        "moles",
        "Keep converted amount and seconds separately editable.",
        "mmol",
      ),
    ),
    n(
      "p-mass-moles",
      "Mass to amount first",
      "0.44 g CO₂ forms over 20 s; Mr=44. Calculate mol/s.",
      0.0005,
      "mol/s",
      "n=0.44/44=0.01mol;0.01/20=0.0005mol/s.",
      "Divide mass by Mr before dividing by time.",
      model("moles", "Predict mol, elapsed seconds and mean rate.", "mass"),
    ),
    n(
      "p-gas-moles",
      "Use stated gas conditions",
      "240 cm³ gas forms over 50 s; at the stated room conditions 1 mol occupies 24000 cm³. Calculate mol/s.",
      0.0002,
      "mol/s",
      "n=240/24000=0.01 mol; 0.01/50=0.0002 mol/s. This volume conversion depends on the explicitly supplied conditions.",
      "Use 24000 cm³/mol, not 24 cm³/mol.",
      model("moles", "Use the stated molar volume and conditions.", "gas"),
    ),
    n(
      "p-amount-offset",
      "Differences in amount and time",
      "Product rises 0.003→0.015 mol during 20–80 s. Calculate mean mol/s.",
      0.0002,
      "mol/s",
      "Change=0.012 mol; elapsed time=60 s; mean=0.0002 mol/s.",
      "Subtract both initial amount and initial time.",
      model("moles", "Retain the nonzero starting readings.", "offset"),
    ),
    n(
      "p-shallow-calibration",
      "A shallower optical tangent",
      "Use the supplied later tangent and calibration to calculate mol/s.",
      0.00001775,
      "mol/s",
      "Signal change−10 percentage-points over 40 s gives−0.25 percentage-point/s; 0.25×0.000071=0.00001775 mol/s.",
      "Magnitude of the tangent slope times stated calibration.",
      model(
        "calibration",
        "Keep the original percentage-point scale.",
        "shallow",
      ),
    ),
    n(
      "p-other-calibration",
      "Do not borrow a calibration",
      "A separate experiment states 2×10⁻⁵mol per percentage-point decrease. Use its supplied tangent.",
      0.00002,
      "mol/s",
      "This tangent has magnitude 1 percentage-point/s; 1×0.00002=0.00002 mol/s. Calibration belongs to the specified experiment.",
      "Use this experiment’s conversion.",
      model(
        "calibration",
        "Change the calibration only when the supplied case changes.",
        "other",
      ),
    ),
    n(
      "p-zero-calibration",
      "Calibrated plateau",
      "Use the supplied 24 % plateau tangent and valid stated calibration. Calculate measured formation rate.",
      0,
      "mol/s",
      "Zero signal change per second gives zero measured formation under the stated valid local calibration. Nonzero light level is not a rate.",
      "Use signal change, not 24 %.",
      model(
        "calibration",
        "Interpret the local calibrated signal without inventing total amount.",
        "zero",
      ),
    ),
    n(
      "p-rising-calibration",
      "Follow the specified signal direction",
      "A different sensor maps each percentage-point INCREASE to 4×10⁻⁵mol product. Calculate its rate.",
      0.00002,
      "mol/s",
      "Signal increases 20 points over 40 s: 0.5 point/s; 0.5×0.00004=0.00002 mol/s. Not every sensor must fall.",
      "Use this stated relation and direction.",
      model(
        "calibration",
        "Separate the supplied signal direction from chemical formation.",
        "increasing",
      ),
    ),
    n(
      "p-wide-calibration",
      "A wider triangle, same slope",
      "Use wider-spaced points on the same constructed light tangent and calculate mol/s.",
      0.000071,
      "mol/s",
      "Magnitude 40 points/40 s=1 point/s; rate=0.000071 mol/s. Triangle size changed; line slope did not.",
      "Both spans increase proportionally on the same line.",
      model(
        "calibration",
        "Choose readable separated points on one tangent.",
        "wider",
      ),
    ),
    c(
      "p-readable",
      "Why make a large triangle?",
      "Which triangle should be used when the same tangent is readable?",
      "Widely separated readable points on the same tangent",
      {
        "Two almost adjacent points only":
          "A fixed coordinate-reading error becomes a larger fraction of each short span.",
        "Points from different tangents":
          "They do not define this tangent’s slope.",
      },
      "A larger readable triangle reduces relative coordinate-reading error; it does not change the line slope.",
      "Choose separation without leaving the tangent.",
      model("evidence", "Justify a coordinate choice.", "triangle"),
    ),
    c(
      "p-chord",
      "Mean versus moment",
      "A chord joins measured curve points at 0 s and 60 s. What does its slope represent?",
      "Mean rate over 0–60 s",
      {
        "Automatically the exact rate at 30 s":
          "The curve may change slope throughout the interval.",
        "Final quantity alone": "Slope needs a difference and elapsed time.",
      },
      "Two curve endpoints define a finite-interval mean, not necessarily the tangent at the midpoint.",
      "Is the line a chord or a local tangent?",
      model("evidence", "Identify the actual construction.", "chord"),
    ),
    c(
      "p-uncalibrated",
      "Do not invent mol/s",
      "Light signal falls at 0.5 percentage-points/s with no amount calibration. What can be concluded?",
      "No chemical amount rate in mol/s is established",
      {
        "The chemical formation rate is 0.5 mol/s":
          "Percentage points cannot be replaced by moles.",
        "The reaction rate is necessarily zero":
          "A falling signal has change but no amount mapping.",
      },
      "The signal rate can be described; mol/s requires a supplied chemical-amount calibration.",
      "Do you have a relation from signal change to moles?",
      model(
        "evidence",
        "Keep signal information without claiming unsupported amount rate.",
        "uncalibrated",
      ),
    ),
    n(
      "p-molar-sign",
      "Negative slope, positive consumption",
      "Remaining-reactant tangent gradient is−0.0003 mol/s. Give positive consumption rate.",
      0.0003,
      "mol/s",
      "The remaining amount falls while reactant is consumed at 0.0003 mol/s.",
      "Take the magnitude for the stated consumption.",
      model(
        "evidence",
        "Choose the correct interpretation and reason.",
        "remaining",
      ),
    ),
    c(
      "p-precision",
      "Graph reading is an estimate",
      "Which precision claim is justified for a drawn experimental tangent?",
      "An estimate reported with precision supported by the graph and question",
      {
        "An exact rate guaranteed by ten calculator digits":
          "Drawing and coordinate-reading precision remain limited.",
        "An exact rate because any two points give it":
          "Only points on the specified tangent give that line’s gradient.",
      },
      "A calculator does not remove uncertainty in the graph and tangent. Follow the question’s requested precision.",
      "Consider the original coordinate readings.",
      model("evidence", "Judge what the evidence supports.", "limitation"),
    ),
    w(
      "p-explain-triangle",
      "Explain the coordinate choice",
      "Explain why you use two widely separated readable points on one tangent and subtract both coordinates.",
      "A tangent represents local direction at the requested moment. Use points on that line, not arbitrary curve points. Subtract both ordinates and both times. Widely separated readable points reduce relative coordinate-reading error; choosing a larger triangle on the same line does not change its gradient.",
      [
        "Local tangent, not arbitrary measured points.",
        "Both coordinate differences.",
        "Same-line slope invariance and relative reading error.",
      ],
    ),
    w(
      "p-explain-sign",
      "Explain the falling signal",
      "Explain why a negative remaining-reactant gradient can mean positive consumption and why an optical slope needs calibration before mol/s.",
      "A remaining amount decreases as reactant is consumed, so its plotted gradient is negative while consumption rate is the positive magnitude. An optical signal is not chemical amount; use an explicitly supplied signal-change/amount relation in its stated direction before giving mol/s.",
      [
        "Negative remaining-amount slope versus positive consumption.",
        "Optical signal requires amount calibration.",
        "State the direction and unit conversion.",
      ],
    ),
    w(
      "p-explain-precision",
      "Explain an estimate",
      "Explain why an experimental tangent answer cannot be declared exact merely because the calculator shows many decimal places.",
      "The fitted curve, tangent drawing and coordinate readings have limited precision. Arithmetic may show more digits than those readings justify. Keep working precision for calculation and report the precision required by the question or supported by the graph.",
      [
        "Drawing and reading uncertainty.",
        "Calculator digits do not create measurement precision.",
        "Round at the end as required.",
      ],
    ),
    w(
      "p-explain-calibration",
      "Explain percentage points",
      "An optical tangent falls 20 percentage-points over 20 s. Each point maps to 7.1×10⁻⁵mol sulfur. Explain the conversion and why there is no further divide-by 100.",
      "The signed signal slope is−1 percentage-point/s. Its magnitude is 1 point/s. Calibration is already per percentage point, so positive sulfur formation rate is 1×7.1×10⁻⁵mol/s. Dividing by 100 again would use a fraction conversion inconsistent with the supplied per-point calibration.",
      [
        "Use 20/20=1 point/s magnitude.",
        "Multiply by the per-percentage-point calibration.",
        "No extra divide-by 100.",
      ],
    ),
    w(
      "p-draw-product",
      "Draw your own tangent",
      "Construct a tangent at 20 s on the supplied product curve; choose two separated visible endpoints. This drawing is self-reviewed.",
      "A suitable line passes through(10 s, 25 cm³), (30 s, 55 cm³), contacts the curve at(20 s, 40 cm³) and follows its local direction. Its triangle gives 30 cm³/20 s=1.5 cm³/s. Other points on the same line are valid.",
      [
        "Touches the curve at 20 s.",
        "Follows the local direction.",
        "Two separated visible tangent points, not two arbitrary curve observations.",
      ],
      practiceGraph,
    ),
    w(
      "p-draw-remaining",
      "Draw a falling tangent",
      "Construct the tangent at 20 s on the supplied remaining-reactant curve. Save the drawing for self-review.",
      "Suitable endpoints(10 s, 4 g), (30 s, 2 g) define a tangent through(20 s, 3 g). The line has signed slope−0.1 g/s; positive consumption rate is 0.1 g/s. Other suitable points on that same line are valid.",
      [
        "Contact at 20 s.",
        "Local falling direction.",
        "Signed plotted gradient versus positive consumption.",
      ],
      {
        curve: {
          ...practiceGraph.curve,
          max: 8,
          unit: "g",
          quantity: "Reactant remaining",
          a: 0.0025,
          b: -0.2,
          c: 6,
        },
        label:
          "Original constructed remaining-reactant curve; draw your own tangent.",
      },
    ),
  ],
  checkForms: [
    [
      n(
        "A-gradient",
        "Reserved mass tangent",
        "A supplied product-mass tangent passes through(25 s, 0.8 g), (65 s, 2.4 g). Calculate its gradient.",
        0.04,
        "g/s",
        "(2.4−0.8)/(65−25)=1.6/40=0.04g/s.",
        "Subtract both coordinates.",
      ),
      n(
        "A-moles",
        "Reserved mean molar rate",
        "12 mmol product forms in 2 minutes. Calculate mean mol/s.",
        0.0001,
        "mol/s",
        "12mmol=0.012mol;2min=120s;rate=0.0001mol/s.",
        "Convert both units before division.",
      ),
      n(
        "A-calibration",
        "Reserved optical conversion",
        "A supplied tangent falls from 70 % at 15 s to 40 % at 45 s. Each percentage-point decrease maps to 3×10⁻⁵mol product. Calculate mol/s.",
        0.00003,
        "mol/s",
        "Magnitude30points/30s=1point/s;rate=0.00003mol/s.",
        "Use the stated calibration, not one from another case.",
      ),
      c(
        "A-tangent",
        "Reserved construction choice",
        "You need rate at 45 s on a curved product-time graph. Which is appropriate?",
        "A tangent following the curve at 45 s",
        {
          "The whole reaction chord": "This gives the mean over its interval.",
          "Product amount at 45 s divided by 45":
            "This need not be the instantaneous rate.",
        },
        "The tangent follows local direction at 45 s.",
        "The requested rate is at a moment.",
      ),
      w(
        "A-draw",
        "Reserved tangent construction",
        "Construct a tangent at 20 s on the supplied reserved product curve. This drawing is saved for self-review.",
        "One suitable line uses(10 s, 20 cm³), (30 s, 44 cm³), passing through(20 s, 32 cm³); its gradient is 24/20=1.2 cm³/s. Other suitable same-line endpoint pairs are valid.",
        [
          "Contact at 20 s.",
          "Follows local curve direction.",
          "Readable separated endpoints on the tangent.",
        ],
        reservedGraph,
      ),
    ],
    [
      n(
        "B-consumed",
        "Reserved signed gradient",
        "A remaining-reactant tangent passes through(10 s, 0.018 mol), (50 s, 0.006 mol). Give positive consumption rate.",
        0.0003,
        "mol/s",
        "Signed slope=(0.006−0.018)/40=−0.0003 mol/s; positive consumption is 0.0003 mol/s.",
        "Interpret the remaining-amount slope.",
      ),
      n(
        "B-minute",
        "Reserved minute axis",
        "A product-volume tangent passes through(0.25 min, 8 cm³), (1.25 min, 32 cm³). Give cm³/s.",
        0.4,
        "cm³/s",
        "24 cm³ over 1 min=60 s; 24/60=0.4 cm³/s.",
        "Use elapsed minutes, then convert to seconds.",
      ),
      n(
        "B-calibration",
        "Reserved rising sensor",
        "A supplied sensor tangent rises from 10 % at 20 s to 25 % at 50 s. Each percentage-point INCREASE maps to 6×10⁻⁵mol product. Calculate mol/s.",
        0.00003,
        "mol/s",
        "15points/30s=0.5point/s;0.5×0.00006=0.00003mol/s.",
        "Use the stated rising relation.",
      ),
      c(
        "B-uncalibrated",
        "Reserved evidence limit",
        "An uncalibrated light signal falls at 2 percentage-points/s. What is established?",
        "A falling signal rate, but no chemical amount rate in mol/s",
        {
          "Exactly 2 mol/s product formation":
            "No signal-to-moles calibration exists.",
          "Zero reaction rate":
            "Absence of calibration is not absence of a reaction.",
        },
        "Retain the signal information without inventing a chemical-amount rate.",
        "What relationship has actually been supplied?",
      ),
      w(
        "B-explain",
        "Reserved mean versus moment",
        "Explain why joining two measured curve points 0 s and 60 s does not automatically provide the reaction rate at 30 s.",
        "The join is a chord whose gradient is the mean rate over 0–60 s. The instantaneous rate at 30 s is the slope of a tangent following the local direction there. A changing curve need not have its midpoint tangent slope equal to the whole-interval mean.",
        [
          "Identify the chord as a finite-interval mean.",
          "Identify the local tangent at 30 s.",
          "Do not assume midpoint equality for a changing curve.",
        ],
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "R-gradient",
        "Delayed coordinate differences",
        "A product tangent passes through(15 s, 6 cm³), (55 s, 38 cm³). Calculate cm³/s.",
        0.8,
        "cm³/s",
        "(38−6)/(55−15)=32/40=0.8cm³/s.",
        "Subtract both nonzero starting coordinates.",
      ),
      n(
        "R-mass",
        "Delayed mass-to-moles rate",
        "0.32 g oxygen forms in 25 s; Mr(O₂)=32. Calculate mean mol/s.",
        0.0004,
        "mol/s",
        "n=0.32/32=0.01mol;rate=0.01/25=0.0004mol/s.",
        "Convert mass to moles before dividing by time.",
      ),
      w(
        "R-precision",
        "Delayed estimate reasoning",
        "Explain how a wider readable triangle on the same tangent affects the gradient and coordinate-reading uncertainty.",
        "The gradient of the same straight line remains unchanged because both differences scale together. A larger readable triangle reduces relative coordinate-reading error; it does not make an experimental tangent exact.",
        [
          "Same-line gradient invariant.",
          "Reduced relative coordinate-reading error.",
          "Experimental estimate remains limited in precision.",
        ],
      ),
    ],
    [
      n(
        "S-calibration",
        "Delayed calibration transfer",
        "A supplied light tangent decreases 12 percentage-points over 40 s. Each point maps to 5×10⁻⁵mol product. Calculate mol/s.",
        0.000015,
        "mol/s",
        "Magnitude12/40=0.3point/s;rate=0.3×0.00005=0.000015mol/s.",
        "Multiply slope magnitude by the stated per-point calibration.",
      ),
      n(
        "S-consumption",
        "Delayed positive consumption",
        "A remaining-reactant tangent has signed slope−0.025 g/s. Give the positive consumption rate.",
        0.025,
        "g/s",
        "Remaining amount falls at 0.025 g/s while consumption is positive 0.025 g/s.",
        "Distinguish the plotted sign from consumption.",
      ),
      w(
        "S-uncalibrated",
        "Delayed evidence limit",
        "Explain what is missing when an optical signal slope is reported as mol/s without any calibration.",
        "The signal is measured in percentage points or another optical unit, not in moles. A supplied relation between signal change and chemical amount is needed in the stated direction. Without it the optical slope cannot establish a chemical amount rate in mol/s.",
        [
          "Signal units are not moles.",
          "Need signal-change/amount relation.",
          "Do not invent mol/s.",
        ],
      ),
    ],
  ],
};
const recovery: Record<string, string> = {
  "p-early": "r-moment",
  "p-late": "r-moment",
  "p-mass-line": "r-gradient",
  "p-consuming-line": "r-consumption",
  "p-flat-line": "r-gradient",
  "p-offset-triangle": "r-time",
  "p-negative-triangle": "r-negative",
  "p-horizontal-triangle": "r-gradient",
  "p-minute-triangle": "r-seconds",
  "p-reversed-order": "r-gradient",
  "p-consumed-moles": "r-consumption",
  "p-mmol-minutes": "r-mmol",
  "p-mass-moles": "r-mass-amount",
  "p-gas-moles": "r-gas-amount",
  "p-amount-offset": "r-time",
  "p-shallow-calibration": "r-percent-point",
  "p-other-calibration": "r-calibration",
  "p-zero-calibration": "r-gradient",
  "p-rising-calibration": "r-calibration",
  "p-wide-calibration": "r-points",
  "p-readable": "r-points",
  "p-chord": "r-moment",
  "p-uncalibrated": "r-calibration",
  "p-molar-sign": "r-consumption",
  "p-precision": "r-precision",
  "p-explain-triangle": "r-points",
  "p-explain-sign": "r-consumption",
  "p-explain-precision": "r-precision",
  "p-explain-calibration": "r-percent-point",
  "p-draw-product": "r-moment",
  "p-draw-remaining": "r-negative",
};
for (const q of tangentJourney.practice)
  q.followUp = "tr-v1-" + recovery[q.id.slice(6)];
const all = [
  ...tangentJourney.warmup,
  ...tangentJourney.refresher,
  ...tangentJourney.guided,
  ...tangentJourney.practice,
  ...tangentJourney.checkForms.flat(),
  ...tangentJourney.reviewForms.flat(),
];
const reservedMassTangent: TangentGraph = {
  curve: {
    start: 20,
    end: 80,
    max: 4,
    unit: "g",
    quantity: "Product formed",
    origin: 25,
    a: -0.0005,
    b: 0.06,
    c: 0.6,
    at: 45,
    label: "Original reserved constructed product-mass curve",
  },
  line: [
    { t: 25, q: 0.8 },
    { t: 65, q: 2.4 },
  ],
  label:
    "Supplied original constructed tangent at45s. Calculate its gradient from the stated coordinates.",
};
all.find((q) => q.id === "tr-v1-A-gradient")!.tangentGraph =
  reservedMassTangent;
const families = {
  geometry: [
    "r-seconds",
    "warm-difference",
    "warm-seconds",
    "r-time",
    "r-gradient",
    "r-negative",
    "r-consumption",
    "r-moment",
    "r-points",
    "r-initial",
    "g-construct",
    "g-gradient",
    "p-early",
    "p-late",
    "p-mass-line",
    "p-consuming-line",
    "p-flat-line",
    "p-offset-triangle",
    "p-negative-triangle",
    "p-horizontal-triangle",
    "p-minute-triangle",
    "p-reversed-order",
    "p-readable",
    "p-chord",
    "p-molar-sign",
    "p-explain-triangle",
    "p-explain-sign",
    "p-draw-product",
    "p-draw-remaining",
    "A-gradient",
    "A-tangent",
    "A-draw",
    "B-consumed",
    "B-minute",
    "B-explain",
    "R-gradient",
    "S-consumption",
    "R-precision",
  ],
  moles: [
    "r-seconds",
    "r-mass-amount",
    "r-gas-amount",
    "warm-seconds",
    "r-mmol",
    "r-amount-rate",
    "r-consumption",
    "g-moles",
    "p-consumed-moles",
    "p-mmol-minutes",
    "p-mass-moles",
    "p-gas-moles",
    "p-amount-offset",
    "A-moles",
    "B-consumed",
    "R-mass",
    "S-consumption",
  ],
  calibration: [
    "r-percent-point",
    "r-calibration",
    "g-calibration",
    "p-shallow-calibration",
    "p-other-calibration",
    "p-zero-calibration",
    "p-rising-calibration",
    "p-wide-calibration",
    "p-uncalibrated",
    "p-explain-calibration",
    "p-explain-sign",
    "A-calibration",
    "B-calibration",
    "B-uncalibrated",
    "S-calibration",
    "S-uncalibrated",
  ],
  evidence: [
    "r-moment",
    "r-points",
    "r-calibration",
    "r-initial",
    "r-precision",
    "g-evidence",
    "p-readable",
    "p-chord",
    "p-uncalibrated",
    "p-molar-sign",
    "p-precision",
    "p-explain-triangle",
    "p-explain-sign",
    "p-explain-precision",
    "p-explain-calibration",
    "A-tangent",
    "B-uncalibrated",
    "B-explain",
    "R-precision",
    "S-uncalibrated",
    "S-consumption",
  ],
};
for (const family of Object.values(families)) {
  const ids = family.map((id) => "tr-v1-" + id);
  for (const q of all)
    if (ids.includes(q.id))
      q.exposureAliases = [
        ...new Set([
          ...(q.exposureAliases ?? []),
          ...ids.filter((id) => id !== q.id),
        ]),
      ];
}
for (const q of all)
  if (q.model?.kind === "tangent-rates") {
    const ids = (
      q.model.mode === "construct" || q.model.mode === "gradient"
        ? families.geometry
        : q.model.mode === "moles"
          ? families.moles
          : q.model.mode === "calibration"
            ? families.calibration
            : families.evidence
    ).map((id) => "tr-v1-" + id);
    q.exposureAliases = [
      ...new Set([
        ...(q.exposureAliases ?? []),
        ...ids.filter((id) => id !== q.id),
      ]),
    ];
  }
