import type { LearningTask, LessonJourney, TaskModel } from "../types";
import { choice, number } from "./helpers";
const n = (
  id: string,
  title: string,
  prompt: string,
  answer: number,
  unit: string,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...number(`tc-v1-${id}`, prompt, answer, unit, explanation, hint, title),
  title,
});
const c = (
  id: string,
  title: string,
  prompt: string,
  answer: string,
  errors: Record<string, string>,
  explanation: string,
  hint: string,
): LearningTask => ({
  ...choice(`tc-v1-${id}`, prompt, answer, errors, explanation, hint, title),
  title,
});
const p = (
  id: string,
  title: string,
  prompt: string,
  parts: { id: string; label: string; answer: number }[],
  explanation: string,
  hint: string,
  model?: TaskModel,
): LearningTask => ({
  id: `tc-v1-${id}`,
  title,
  prompt,
  parts,
  partLegend: title,
  answer: JSON.stringify(
    Object.fromEntries(parts.map((v) => [v.id, String(v.answer)])),
  ),
  explanation,
  hint,
  purpose: title,
  model,
});
const w = (
  id: string,
  title: string,
  prompt: string,
  explanation: string,
  rubric: string[],
): LearningTask => ({
  id: `tc-v1-${id}`,
  title,
  prompt,
  answer: explanation,
  explanation,
  rubric,
  hint: "Name the reacting substance, show its amount and explain the relevant ratio or volume.",
  purpose: title,
});
const m = (
  mode: "titre" | "concentration" | "ratio" | "mass" | "volume",
  instruction: string,
): TaskModel => ({ kind: "titration-calculations", mode, instruction });
export const titrationCalculationsJourney: LessonJourney = {
  version: 1,
  introduction:
    "Follow the measured solution volume through the reaction ratio to the unknown concentration.",
  scopeNote:
    "Higher separate Chemistry: AQA 4.3.4 and the calculation part of 4.4.2.5/RPA2; related Pearson 5.8C–5.10C include unknown reacting volume. All reactions use supplied balanced equations for strong acids and strong alkalis under the stated complete-neutralisation assumption. A titre is final minus initial reading on the same burette. With c in mol/dm³, n=cV requires V in dm³; then unknown n=known n×unknown coefficient/known coefficient. Divide by the original unknown solution sample volume, not the titre or total mixture volume. Mass concentration=c×the named solute molar mass M in g/mol. Reverse reacting volume requires the stoichiometric amount divided by titrant concentration. A direct cV ratio can use matching cm³ units because the common 1000 cancels; do not mix volume units. Supplied selected titres are treated as reliable endpoint estimates; endpoint and equivalence are close in a suitable method, not universally identical. Selection/precision/indicator technique and supervised practical competence require the separate Titration technique lesson. The 3D scale is schematic apparatus, not a molecular solution or instructions for unsupervised work. Written answers stay self-reviewed and cannot earn automatic correctness or an official examiner mark.",
  outcomes: [
    "Subtract initial from final burette reading.",
    "Convert reacting solution volumes consistently.",
    "Use the correctly oriented balanced mole ratio.",
    "Find unknown molar and mass concentrations.",
    "Calculate a required reacting volume and explain sources of calculation bias.",
  ],
  warmup: [
    n(
      "w-volume",
      "Match concentration units",
      "Convert 25.0 cm³ to dm³.",
      0.025,
      "dm³",
      "25.0/1000=0.025 dm³.",
      "Divide by 1000.",
    ),
    n(
      "w-ratio",
      "Read the acid coefficient",
      "H2SO4 + 2NaOH → Na2SO4 + 2H2O. How many moles NaOH react with 1 mol H2SO4?",
      2,
      "mol",
      "The NaOH:H2SO4 coefficient ratio is 2:1.",
      "Use coefficients, not formula subscripts.",
    ),
  ],
  refresher: [
    n(
      "r-amount",
      "Known dissolved amount",
      "20.0 cm³ NaOH at 0.100 mol/dm³. Find its amount.",
      0.002,
      "mol",
      "0.100×0.0200=0.00200 mol.",
      "n=cV; V in dm³.",
    ),
    n(
      "r-titre",
      "Read delivered volume",
      "A burette starts at 3.20 cm³ and ends at 22.70 cm³. Find the delivered volume.",
      19.5,
      "cm³",
      "22.70−3.20=19.50 cm³.",
      "Subtract initial from final.",
    ),
    c(
      "r-ratio",
      "Orient the reaction factor",
      "2HCl + Ba(OH)2 → BaCl2 + 2H2O. Starting from Ba(OH)2 moles, which operation gives reacting HCl moles?",
      "Multiply by 2",
      {
        "Divide by 2": "This reverses the HCl:Ba(OH)2 ratio.",
        "Keep the same amount": "The coefficients are 2:1, not 1:1.",
      },
      "Unknown HCl coefficient 2 divided by known Ba(OH)2 coefficient 1 gives factor 2.",
      "Unknown coefficient over known coefficient.",
    ),
    c(
      "r-volume",
      "Choose the denominator",
      "25.0 cm³ HCl is titrated with 18.0 cm³ NaOH. Which volume belongs in c(HCl)=n(HCl)/V?",
      "The original 25.0 cm³ HCl sample",
      {
        "The 18.0 cm³ NaOH titre": "That is a different solution.",
        "The combined43.0 cm³ mixture":
          "We want the original acid concentration, not a reacted mixture.",
      },
      "Use the original sample volume of the named unknown solution.",
      "Match n and V to the same solution.",
    ),
    n(
      "r-mass",
      "Convert the concentration numerator",
      "NaOH has concentration0.150 mol/dm³ and M=40 g/mol. Find its mass concentration.",
      6,
      "g/dm³",
      "0.150×40=6.00 g/dm³.",
      "Multiply by the named solute molar mass.",
    ),
  ],
  guided: [
    p(
      "g-titre",
      "Find the titre",
      "NaOH 0.100 mol/dm³. Burette: initial 1.40 cm³, final 21.40 cm³. Find titre and NaOH amount.",
      [
        { id: "titre", label: "Delivered/cm³", answer: 20 },
        { id: "amount", label: "NaOH/mol", answer: 0.002 },
      ],
      "21.40−1.40=20.00 cm³=0.02000 dm³; NaOH n=0.100×0.02000=0.00200 mol.",
      "Subtract before converting.",
      m(
        "titre",
        "Shift both readings together or change the delivered volume.",
      ),
    ),
    p(
      "g-concentration",
      "Follow a one-to-one reaction",
      "Initial record: 25.0 cm³ HCl reacts completely with 20.0 cm³ NaOH at 0.100 mol/dm³. HCl + NaOH → NaCl + H2O. Find NaOH amount and original HCl concentration.",
      [
        { id: "amount", label: "NaOH/mol", answer: 0.002 },
        { id: "c", label: "HCl/mol dm⁻³", answer: 0.08 },
      ],
      "NaOH n=0.100×0.0200=0.00200 mol; HCl n=0.00200 mol; c=0.00200/0.0250=0.0800 mol/dm³.",
      "Calculate known n, apply ratio, divide by acid sample volume.",
      m(
        "concentration",
        "Change titre or original acid sample volume; retain the named denominator.",
      ),
    ),
    p(
      "g-ratio",
      "Apply the equation ratio",
      "Initial record: 25.0 cm³ H2SO4 reacts completely with 24.0 cm³ NaOH at 0.100 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find acid amount and acid concentration.",
      [
        { id: "amount", label: "H2SO4/mol", answer: 0.0012 },
        { id: "c", label: "H2SO4/mol dm⁻³", answer: 0.048 },
      ],
      "NaOH n=0.00240 mol; acid n=0.00240×1/2=0.00120 mol; c=0.00120/0.0250=0.0480 mol/dm³.",
      "The acid amount is half the NaOH amount.",
      m(
        "ratio",
        "Compare 1:2 acid:alkali with 2:1 and an equal-volume record.",
      ),
    ),
    p(
      "g-mass",
      "Report a mass concentration",
      "Initial record: 25.0 cm³ NaOH reacts completely with 20.0 cm³ HCl at 0.200 mol/dm³. HCl + NaOH → NaCl + H2O. NaOH M=40 g/mol. Find original NaOH molar and mass concentrations.",
      [
        { id: "c", label: "NaOH/mol dm⁻³", answer: 0.16 },
        { id: "mass", label: "NaOH/g dm⁻³", answer: 6.4 },
      ],
      "HCl n=0.00400 mol=NaOH n; c=0.00400/0.0250=0.160 mol/dm³; mass concentration=0.160×40=6.40 g/dm³.",
      "Use the molar mass of the UNKNOWN named solute.",
      m(
        "mass",
        "Change the named solute and reaction before choosing its molar mass.",
      ),
    ),
    p(
      "g-volume",
      "Reverse the question",
      "Initial record: 25.0 cm³ H2SO4 at 0.0500 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH amount and the volume of 0.100 mol/dm³ NaOH required for complete reaction.",
      [
        { id: "amount", label: "NaOH/mol", answer: 0.0025 },
        { id: "volume", label: "NaOH/cm³", answer: 25 },
      ],
      "Acid n=0.00125 mol; NaOH n=2×0.00125=0.00250 mol; V=0.00250/0.100=0.0250 dm³=25.0 cm³.",
      "First find required NaOH amount, then divide by its concentration.",
      m(
        "volume",
        "Double titrant concentration while retaining the required amount.",
      ),
    ),
  ],
  practice: [
    n(
      "p-reading",
      "Nonzero start",
      "A burette starts at 2.35 cm³ and ends at 24.85 cm³. Find delivered solution volume.",
      22.5,
      "cm³",
      "24.85−2.35=22.50 cm³.",
      "Use the difference.",
    ),
    n(
      "p-mean",
      "Use supplied accepted readings",
      "A protocol accepts titres within a total span of 0.10 cm³. The rough trial is 20.80 cm³; accepted repeats are 19.95,20.00,20.05 cm³. Find the mean accepted titre.",
      20,
      "cm³",
      "(19.95 + 20.00 + 20.05)/3=20.00 cm³;exclude the stated rough trial.",
      "Average only the explicitly accepted repeats.",
    ),
    n(
      "p-known",
      "Known reagent amount",
      "18.0 cm³ NaOH at 0.150 mol/dm³ reacts. Find NaOH amount.",
      0.0027,
      "mol",
      "0.150×0.0180=0.00270 mol.",
      "Convert volume before n=cV.",
    ),
    n(
      "p-one",
      "One-to-one moles",
      "HCl + NaOH → NaCl + H2O. Find HCl amount reacting completely with 0.00270 mol NaOH.",
      0.0027,
      "mol",
      "HCl:NaOH=1:1.",
      "Read coefficients.",
    ),
    n(
      "p-half",
      "Half the known amount",
      "H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find acid amount reacting with 0.00600 mol NaOH.",
      0.003,
      "mol",
      "0.00600×1/2=0.00300 mol.",
      "Acid coefficient over alkali coefficient.",
    ),
    n(
      "p-double",
      "Twice the known amount",
      "H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH amount required by 0.00180 mol H2SO4.",
      0.0036,
      "mol",
      "0.00180×2=0.00360 mol.",
      "Now the unknown is NaOH.",
    ),
    n(
      "p-barium",
      "Different hydroxide formula",
      "2HCl + Ba(OH)2 → BaCl2 + 2H2O. Find HCl amount reacting completely with 0.00220 mol Ba(OH)2.",
      0.0044,
      "mol",
      "0.00220×2=0.00440 mol HCl.",
      "Read the supplied balanced equation.",
    ),
    n(
      "p-hcl",
      "Original acid concentration",
      "25.0 cm³ HCl reacts with 22.5 cm³ NaOH at 0.120 mol/dm³. HCl + NaOH → NaCl + H2O. Find HCl concentration.",
      0.108,
      "mol/dm³",
      "Known n=0.120×0.0225=0.00270 mol; acid n=same; c=0.00270/0.0250=0.108 mol/dm³.",
      "Divide by original acid volume.",
    ),
    n(
      "p-sulfuric",
      "Acid with two equivalents",
      "20.0 cm³ H2SO4 reacts with 16.0 cm³ NaOH at 0.150 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find acid concentration.",
      0.06,
      "mol/dm³",
      "NaOH n=0.00240 mol; acid n=0.00120 mol; c=0.00120/0.0200=0.0600 mol/dm³.",
      "Apply1/2 before dividing.",
    ),
    n(
      "p-base",
      "Unknown alkali concentration",
      "25.0 cm³ NaOH reacts with 15.0 cm³ H2SO4 at 0.100 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH concentration.",
      0.12,
      "mol/dm³",
      "Acid n=0.00150 mol; NaOH n=0.00300 mol; c=0.00300/0.0250=0.120 mol/dm³.",
      "The unknown NaOH amount is twice acid amount.",
    ),
    n(
      "p-nitric",
      "From mass units",
      "HNO3 mass concentration is 4.41 g/dm³;M=63 g/mol. Find its molar concentration.",
      0.07,
      "mol/dm³",
      "4.41/63=0.0700 mol/dm³.",
      "Divide mass concentration by molar mass.",
    ),
    n(
      "p-naoh-mass",
      "Named alkali mass",
      "NaOH concentration is 0.120 mol/dm³;M=40 g/mol. Find mass concentration.",
      4.8,
      "g/dm³",
      "0.120×40=4.80 g/dm³.",
      "Multiply by NaOH M.",
    ),
    n(
      "p-acid-mass",
      "Named acid mass",
      "H2SO4 concentration is 0.0600 mol/dm³;M=98 g/mol. Find mass concentration.",
      5.88,
      "g/dm³",
      "0.0600×98=5.88 g/dm³.",
      "Do not use water molar mass.",
    ),
    n(
      "p-reverse-one",
      "Required one-to-one volume",
      "25.0 cm³ HCl at 0.160 mol/dm³ reacts with NaOH at 0.200 mol/dm³. HCl + NaOH → NaCl + H2O. Find NaOH volume required.",
      20,
      "cm³",
      "HCl n=0.00400 mol=NaOH n; V=0.00400/0.200=0.0200 dm³=20.0 cm³.",
      "Required amount divided by titrant c.",
    ),
    n(
      "p-reverse-two",
      "Required two-to-one volume",
      "20.0 cm³ H2SO4 at 0.0800 mol/dm³ reacts with NaOH at 0.100 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH volume required.",
      32,
      "cm³",
      "Acid n=0.00160 mol; NaOH n=0.00320 mol; V=0.00320/0.100=0.0320 dm³=32.0 cm³.",
      "Use the reaction factor before n/c.",
    ),
    c(
      "p-cancellation",
      "A valid shortened method",
      "In c(unknown)=c(known)×V(known)/V(unknown)×coefficient ratio, when may both numeric volumes be left in cm³?",
      "When both volumes use matching cm³ units",
      {
        "Whenever one volume uses dm³":
          "Different units do not cancel correctly.",
        "Never, even when their common conversion cancels":
          "A correct ratio can cancel the same factor 1000.",
      },
      "In the complete ratio, the two /1000 conversion factors cancel. A standalone n=cV still needs dm³ for mol/dm³.",
      "Distinguish a volume ratio from an amount calculation.",
    ),
    c(
      "p-equal-volume",
      "Equal reacting volumes",
      "Equal volumes of H2SO4 and NaOH react completely. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Compare original concentrations.",
      "H2SO4 concentration is half NaOH concentration",
      {
        "Their concentrations must be equal": "The mole ratio is 1:2.",
        "H2SO4 concentration is twice NaOH concentration":
          "This inverts the ratio.",
      },
      "Equal volumes mean c ratios match mole ratios; acid:NaOH=1:2.",
      "Equation ratio still matters.",
    ),
    w(
      "p-denominator",
      "Explain the sample volume",
      "25.0 cm³ HCl reacts with 20.0 cm³ NaOH at 0.100 mol/dm³. HCl + NaOH → NaCl + H2O. Explain why dividing 0.00200 mol HCl by 0.0450 dm³ gives the wrong original acid concentration.",
      "The 45.0 cm³ is the combined reacted mixture, not original HCl solution. Original acid V=0.0250 dm³ gives c=0.0800 mol/dm³.",
      [
        "Identify the combined volume.",
        "Use original 25.0 cm³ acid sample.",
        "Show 0.00200/0.0250=0.0800 mol/dm³.",
      ],
    ),
    w(
      "p-wrong-ratio",
      "Repair a one-to-one assumption",
      "25.0 cm³ HCl reacts with 22.0 cm³ Ba(OH)2 at 0.100 mol/dm³. 2HCl + Ba(OH)2 → BaCl2 + 2H2O. A student obtains0.0880 mol/dm³ by assuming1:1. Explain the repair.",
      "Ba(OH)2 n=0.00220 mol; HCl n=2×0.00220=0.00440 mol; c=0.00440/0.0250=0.176 mol/dm³. The original answer omitted the2:1 acid:base factor.",
      [
        "Calculate known 0.00220 mol.",
        "Apply2:1 to HCl.",
        "Obtain0.176 mol/dm³ and identify omitted factor.",
      ],
    ),
    w(
      "p-overshoot",
      "Predict a bias",
      "Assume correct known titrant concentration, sample volume and balanced equation. A student overshoots the suitable indicator endpoint and uses the excessive titre to infer the original unknown concentration. Explain the direction of error.",
      "An excessive titre overestimates known reacting moles, so the stoichiometric inferred unknown amount and concentration are too high. It does not prove the original solution became more concentrated.",
      [
        "Larger titre raises calculated known n.",
        "Reaction factor carries bias to unknown n.",
        "Fixed sample volume makes inferred c too high.",
      ],
    ),
    w(
      "p-shift",
      "Explain unchanged delivery",
      "One titration runs from 1.40 to 21.40 cm³ and another from 4.80 to 24.80 cm³ using the same titrant concentration. Explain why the calculated delivered amount is unchanged.",
      "Both differences are 20.00 cm³, so the same concentration times0.02000 dm³ gives the same delivered moles. Final readings alone differ and are not titres.",
      [
        "Subtract each initial reading.",
        "Both give 20.00 cm³.",
        "Use same c and delivered V rather than final readings.",
      ],
    ),
  ],
  checkForms: [
    [
      p(
        "ca-first",
        "Fresh reacting amounts",
        "25.0 cm³ H2SO4 reacts with 28.0 cm³ NaOH at 0.150 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH and acid amounts.",
        [
          { id: "base", label: "NaOH/mol", answer: 0.0042 },
          { id: "acid", label: "H2SO4/mol", answer: 0.0021 },
        ],
        "NaOH=0.150×0.0280=0.00420 mol; acid=0.00210 mol.",
        "Convert then apply1/2.",
      ),
      n(
        "ca-c",
        "Fresh acid concentration",
        "Using25.0 cm³ H2SO4 and28.0 cm³ NaOH at 0.150 mol/dm³, H2SO4 + 2NaOH → Na2SO4 + 2H2O, find acid concentration.",
        0.084,
        "mol/dm³",
        "0.00420/2/0.0250=0.0840 mol/dm³.",
        "Use original acid volume.",
      ),
      n(
        "ca-mass",
        "Fresh acid mass concentration",
        "H2SO4 has concentration0.0840 mol/dm³ and M=98 g/mol. Find mass concentration.",
        8.232,
        "g/dm³",
        "0.0840×98=8.232 g/dm³.",
        "Retain intermediate precision.",
      ),
      n(
        "ca-volume",
        "Fresh required volume",
        "20.0 cm³ HNO3 at 0.180 mol/dm³ requires NaOH at 0.120 mol/dm³. HNO3 + NaOH → NaNO3 + H2O. Find NaOH volume.",
        30,
        "cm³",
        "0.180×0.0200=0.00360 mol; V=0.00360/0.120=0.0300 dm³=30.0 cm³.",
        "Required moles divided by titrant concentration.",
      ),
      w(
        "ca-written",
        "Fresh wrong denominator",
        "A student uses original acid n but divides by the combined acid + titrant volume to report original acid concentration. Explain the error and direction of bias, assuming both volumes are positive.",
        "The denominator must be original acid sample volume. Combined volume is larger, so the reported original concentration is too low; it is not a valid residual acid calculation after reaction.",
        [
          "Match n and V to original acid.",
          "Combined volume too large.",
          "Calculated original c too low.",
        ],
      ),
    ],
    [
      p(
        "cb-first",
        "Alternative reacting amounts",
        "20.0 cm³ HCl reacts with 16.0 cm³ Ba(OH)2 at 0.125 mol/dm³. 2HCl + Ba(OH)2 → BaCl2 + 2H2O. Find base and acid amounts.",
        [
          { id: "base", label: "Ba(OH)2/mol", answer: 0.002 },
          { id: "acid", label: "HCl/mol", answer: 0.004 },
        ],
        "Base=0.125×0.0160=0.00200 mol; acid=0.00400 mol.",
        "Apply2:1 HCl:base.",
      ),
      n(
        "cb-c",
        "Alternative acid concentration",
        "20.0 cm³ HCl reacts with 16.0 cm³ Ba(OH)2 at 0.125 mol/dm³. 2HCl + Ba(OH)2 → BaCl2 + 2H2O. Find original HCl concentration.",
        0.2,
        "mol/dm³",
        "0.00400/0.0200=0.200 mol/dm³.",
        "Original acid volume in dm³.",
      ),
      n(
        "cb-mass",
        "Alternative acid mass concentration",
        "HCl has concentration0.200 mol/dm³;M=36.5 g/mol. Find mass concentration.",
        7.3,
        "g/dm³",
        "0.200×36.5=7.30 g/dm³.",
        "Use HCl molar mass.",
      ),
      n(
        "cb-volume",
        "Alternative required volume",
        "15.0 cm³ H2SO4 at 0.0800 mol/dm³ reacts with NaOH at 0.200 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH volume required.",
        12,
        "cm³",
        "Acid=0.00120 mol; NaOH=0.00240 mol; V=0.0120 dm³=12.0 cm³.",
        "Use the 2:1 factor.",
      ),
      w(
        "cb-written",
        "Alternative titre reasoning",
        "Two same-concentration burette trials have initial/final readings2.60/19.60 cm³ and5.30/22.30 cm³. Explain whether delivered moles differ.",
        "Both delivered volumes are 17.00 cm³. Same c gives same delivered n; final readings alone cannot compare delivered amount.",
        ["Subtract both pairs.", "Same17.00 cm³.", "Same c means same n."],
      ),
    ],
  ],
  reviewForms: [
    [
      n(
        "ra-titre",
        "Delayed delivered volume",
        "Initial burette reading3.65 cm³;final 22.15 cm³. Find delivered volume.",
        18.5,
        "cm³",
        "22.15−3.65=18.50 cm³.",
        "Subtract initial.",
      ),
      n(
        "ra-concentration",
        "Delayed one-to-one concentration",
        "20.0 cm³ HCl reacts with 24.0 cm³ NaOH at 0.0750 mol/dm³. HCl + NaOH → NaCl + H2O. Find HCl concentration.",
        0.09,
        "mol/dm³",
        "0.0750×0.0240/0.0200=0.0900 mol/dm³.",
        "n=cV then original acid volume.",
      ),
      n(
        "ra-volume",
        "Delayed reverse ratio",
        "10.0 cm³ H2SO4 at 0.120 mol/dm³ requires0.150 mol/dm³ NaOH. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find NaOH volume.",
        16,
        "cm³",
        "Acid=0.00120 mol; NaOH=0.00240 mol; V=0.0160 dm³=16.0 cm³.",
        "Apply reaction factor before n/c.",
      ),
    ],
    [
      n(
        "rb-titre",
        "Other delayed volume",
        "Initial burette reading0.80 cm³;final 17.05 cm³. Find delivered volume.",
        16.25,
        "cm³",
        "17.05−.80=16.25 cm³.",
        "Use the difference.",
      ),
      n(
        "rb-concentration",
        "Other delayed ratio",
        "25.0 cm³ H2SO4 reacts with 30.0 cm³ NaOH at 0.0800 mol/dm³. H2SO4 + 2NaOH → Na2SO4 + 2H2O. Find acid concentration.",
        0.048,
        "mol/dm³",
        "Base=0.00240 mol; acid=0.00120 mol; c=0.0480 mol/dm³.",
        "Use acid:base 1:2.",
      ),
      n(
        "rb-mass",
        "Other delayed mass units",
        "NaOH concentration is 0.0900 mol/dm³;M=40 g/mol. Find mass concentration.",
        3.6,
        "g/dm³",
        "0.0900×40=3.60 g/dm³.",
        "Use named solute M.",
      ),
    ],
  ],
};
for (const [from, to] of Object.entries({
  "p-reading": "r-titre",
  "p-sulfuric": "r-ratio",
  "p-base": "r-ratio",
  "p-acid-mass": "r-mass",
})) {
  titrationCalculationsJourney.practice.find(
    (q) => q.id === `tc-v1-${from}`,
  )!.followUp = `tc-v1-${to}`;
}

titrationCalculationsJourney.guided[0].openingHint = true;
